<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ผศ.ดร.สิวะโชติ ศรีสุทธิยากร">

<title>2758688 ML PRIN APPLN - Modelling Process</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../documents/03TreeModels.html" rel="next">
<link href="../documents/01basicConcepts.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="2758688 ML PRIN APPLN - Modelling Process">
<meta property="og:description" content="กระบวนการพัฒนา machine learning models อาจจำแนกได้เป็นสองส่วน ส่วนแรกคือส่วนของการพัฒนาโมเดล และส่วนที่สองคือส่วนของการนำโมเดลไปใช้งาน">
<meta property="og:site-name" content="2758688 ML PRIN APPLN">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Modelling Process</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://github.com/ssiwacho/2758688_ML" title="GitHub ของรายวิชา" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="https://posit.co/download/rstudio-desktop/" title="RStudio" class="sidebar-tool px-1"><i class="bi bi-code-square"></i></a>
</div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">Course information</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course-overview.html" class="sidebar-item-text sidebar-link">Overview</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">Schedule</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../course-lecturer.html" class="sidebar-item-text sidebar-link">Instructor</a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">เนื้อหารายสัปดาห์</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../documents/01basicConcepts.html" class="sidebar-item-text sidebar-link">Wk01 Intro to ML</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../documents/02MLProcess.html" class="sidebar-item-text sidebar-link active">Wk02 ML Process</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../documents/03TreeModels.html" class="sidebar-item-text sidebar-link">Wk03 Decision Trees</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../documents/04Regularization.html" class="sidebar-item-text sidebar-link">Wk04 Regularization</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../documents/05RandomForest.html" class="sidebar-item-text sidebar-link">Wk05 Random Forest</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">สารบัญ</h2>
   
  <ul>
  <li><a href="#บทท-3-กระบวนการพฒนา-machine-learning-models" id="toc-บทท-3-กระบวนการพฒนา-machine-learning-models" class="nav-link active" data-scroll-target="#บทท-3-กระบวนการพฒนา-machine-learning-models">บทที่ 3 กระบวนการพัฒนา Machine Learning Models</a>
  <ul class="collapse">
  <li><a href="#bias-and-variance-in-ml-models" id="toc-bias-and-variance-in-ml-models" class="nav-link" data-scroll-target="#bias-and-variance-in-ml-models">3.1 Bias and Variance in ML models</a></li>
  <li><a href="#underfitting-overfitting-และ-good-fit-models" id="toc-underfitting-overfitting-และ-good-fit-models" class="nav-link" data-scroll-target="#underfitting-overfitting-และ-good-fit-models">3.2 Underfitting, Overfitting และ Good fit models</a></li>
  <li><a href="#training-validation-and-test-dataset" id="toc-training-validation-and-test-dataset" class="nav-link" data-scroll-target="#training-validation-and-test-dataset">3.3 Training, validation, and Test Dataset</a></li>
  <li><a href="#data-partitioning" id="toc-data-partitioning" class="nav-link" data-scroll-target="#data-partitioning">3.4 Data Partitioning</a>
  <ul class="collapse">
  <li><a href="#ชดขอมล-mpg" id="toc-ชดขอมล-mpg" class="nav-link" data-scroll-target="#ชดขอมล-mpg">ชุดข้อมูล <code>mpg</code></a></li>
  <li><a href="#การแบงขอมลดวยการสมอยางงาย" id="toc-การแบงขอมลดวยการสมอยางงาย" class="nav-link" data-scroll-target="#การแบงขอมลดวยการสมอยางงาย">การแบ่งข้อมูลด้วยการสุ่มอย่างง่าย</a></li>
  <li><a href="#การแบงขอมลดวยการสมแบบชนภม" id="toc-การแบงขอมลดวยการสมแบบชนภม" class="nav-link" data-scroll-target="#การแบงขอมลดวยการสมแบบชนภม">การแบ่งข้อมูลด้วยการสุ่มแบบชั้นภูมิ</a></li>
  </ul></li>
  <li><a href="#การสมซำ-resampling" id="toc-การสมซำ-resampling" class="nav-link" data-scroll-target="#การสมซำ-resampling">3.5 การสุ่มซ้ำ (resampling)</a>
  <ul class="collapse">
  <li><a href="#k-fold-cross-validation-และวธการอน-ๆ-ทเกยวของ" id="toc-k-fold-cross-validation-และวธการอน-ๆ-ทเกยวของ" class="nav-link" data-scroll-target="#k-fold-cross-validation-และวธการอน-ๆ-ทเกยวของ">K-fold Cross-Validation และวิธีการอื่น ๆ ที่เกี่ยวข้อง</a></li>
  <li><a href="#monte-carlo-cross-validation" id="toc-monte-carlo-cross-validation" class="nav-link" data-scroll-target="#monte-carlo-cross-validation">Monte Carlo Cross-Validation</a></li>
  <li><a href="#bootstraping" id="toc-bootstraping" class="nav-link" data-scroll-target="#bootstraping">Bootstraping</a></li>
  </ul></li>
  <li><a href="#tidymodels-framework" id="toc-tidymodels-framework" class="nav-link" data-scroll-target="#tidymodels-framework">3.6 Tidymodels Framework</a>
  <ul class="collapse">
  <li><a href="#fitting-linear-regression-using-parsnip" id="toc-fitting-linear-regression-using-parsnip" class="nav-link" data-scroll-target="#fitting-linear-regression-using-parsnip">Fitting Linear Regression using parsnip</a></li>
  <li><a href="#fitting-classification-models-logistic-regression-using-parsnip" id="toc-fitting-classification-models-logistic-regression-using-parsnip" class="nav-link" data-scroll-target="#fitting-classification-models-logistic-regression-using-parsnip">Fitting Classification models (logistic regression) using parsnip</a></li>
  </ul></li>
  <li><a href="#scikit-learn-library" id="toc-scikit-learn-library" class="nav-link" data-scroll-target="#scikit-learn-library">3.6 Scikit-Learn library</a></li>
  <li><a href="#สรป" id="toc-สรป" class="nav-link" data-scroll-target="#สรป">สรุป</a></li>
  </ul></li>
  <li><a href="#บทท-4-การเตรยมขอมล-data-preprocessing" id="toc-บทท-4-การเตรยมขอมล-data-preprocessing" class="nav-link" data-scroll-target="#บทท-4-การเตรยมขอมล-data-preprocessing">บทที่ 4 การเตรียมข้อมูล (data preprocessing)</a>
  <ul class="collapse">
  <li><a href="#ภาพรวมและความสำคญของ-data-preprocessing" id="toc-ภาพรวมและความสำคญของ-data-preprocessing" class="nav-link" data-scroll-target="#ภาพรวมและความสำคญของ-data-preprocessing">4.1 ภาพรวมและความสำคัญของ Data Preprocessing</a></li>
  <li><a href="#ประเภทของ-data-preprocessing" id="toc-ประเภทของ-data-preprocessing" class="nav-link" data-scroll-target="#ประเภทของ-data-preprocessing">4.2 ประเภทของ Data Preprocessing</a>
  <ul class="collapse">
  <li><a href="#การทำความสะอาดขอมล-data-cleaning" id="toc-การทำความสะอาดขอมล-data-cleaning" class="nav-link" data-scroll-target="#การทำความสะอาดขอมล-data-cleaning">การทำความสะอาดข้อมูล (data cleaning)</a></li>
  <li><a href="#การแปลงขอมล-data-transformation" id="toc-การแปลงขอมล-data-transformation" class="nav-link" data-scroll-target="#การแปลงขอมล-data-transformation">การแปลงข้อมูล (data transformation)</a></li>
  <li><a href="#การคดเลอกตวแปร-feature-selection" id="toc-การคดเลอกตวแปร-feature-selection" class="nav-link" data-scroll-target="#การคดเลอกตวแปร-feature-selection">การคัดเลือกตัวแปร (feature selection)</a></li>
  </ul></li>
  <li><a href="#พนฐาน-recipe-สำหรบทำ-data-preprocessing" id="toc-พนฐาน-recipe-สำหรบทำ-data-preprocessing" class="nav-link" data-scroll-target="#พนฐาน-recipe-สำหรบทำ-data-preprocessing">4.3 พื้นฐาน <code>recipe</code> สำหรับทำ Data Preprocessing</a>
  <ul class="collapse">
  <li><a href="#การดาวนโหลดและตดตง-package" id="toc-การดาวนโหลดและตดตง-package" class="nav-link" data-scroll-target="#การดาวนโหลดและตดตง-package">การดาวน์โหลดและติดตั้ง package</a></li>
  <li><a href="#ขนตอนการทำ-data-preprocessing-ดวย-recipe" id="toc-ขนตอนการทำ-data-preprocessing-ดวย-recipe" class="nav-link" data-scroll-target="#ขนตอนการทำ-data-preprocessing-ดวย-recipe">ขั้นตอนการทำ data preprocessing ด้วย recipe</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Modelling Process</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ผศ.ดร.สิวะโชติ ศรีสุทธิยากร </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="บทท-3-กระบวนการพฒนา-machine-learning-models" class="level1">
<h1>บทที่ 3 กระบวนการพัฒนา Machine Learning Models</h1>
<p>กระบวนการพัฒนา machine learning models อาจจำแนกได้เป็นสองส่วน ส่วนแรกคือส่วนของการพัฒนาโมเดล และส่วนที่สองคือส่วนของการนำโมเดลไปใช้งาน</p>
<p>ส่วนการพัฒนาโมเดลมีกระบวนการพัฒนาแสดงไว้ในรูป 15 จากรูปจะเห็นว่าเริ่มตั้งแต่การเก็บรวบรวมข้อมูล การจัดการข้อมูล จากนั้นจะมีการแบ่งชุดข้อมูลออกเป็นส่วน traning dataset และ test dataset ข้อมูลส่วนที่เป็น traning dataset จะถูกนำมาพัฒนาการเรียนรู้/ความสามารถในการทำนายของโมเดล ผ่านอัลกอริทึมต่าง ๆ จากนั้นจะเลือกอัลกอริทึมที่มีประสิทธิภาพสูงที่สุด (ประเมินจาก test dataset) ไปใช้งาน ทั้งนี้การจะนำโมเดลทำนายไปใช้งานได้นั้นจะต้องมีบันทึกโมเดลที่พัฒนาขึ้นเพื่อนำไปเรียกใช้ต่อไป</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1728379488.png" class="img-fluid figure-img" alt="Modeling Process"></p>
<p></p><figcaption class="figure-caption">Modeling Process</figcaption><p></p>
</figure>
</div>
<p>ลักษณะเฉพาะในกระบวนการพัฒนาโมเดลทำนายคือ การดำเนินงานในหลายขั้นตอน เช่น การจัดการข้อมูล การ fit และปรับแต่งโมเดล หรือการคัดเลือกโมเดลทำนายที่ดีที่สุด ไม่ได้มีแนวทางหรือกฎเกณฑ์ที่ชัดเจนตายตัวว่าต้องดำเนินการอย่างไร นอกจากนี้กระบวนการดังกล่าวยังมีลักษณะเป็นแบบทวนซ้ำไปมา รูป 16 แสดงตัวอย่างการดำเนินงานของผู้วิเคราะห์เพื่อพัฒนาโมเดลทำนายโมเดลหนึ่ง</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1908104112.png" class="img-fluid figure-img" style="width:70.0%" alt="ตัวอย่างขั้นตอนการพัฒนาโมเดลทำนาย (ที่มา : Max Kuhn and Kjell Johnson (2019))"></p>
<p></p><figcaption class="figure-caption">ตัวอย่างขั้นตอนการพัฒนาโมเดลทำนาย (ที่มา : Max Kuhn and Kjell Johnson (2019))</figcaption><p></p>
</figure>
</div>
<p>จากรูปข้างต้นจะเห็นว่ากระบวนการเริ่มต้นด้วยกากการวิเคราะห์เพื่อสำรวจข้อมูล (exploratory data analysis: EDA) ก่อน (จุด a) โดยที่ EDA เป็นเทคนิคที่ผู้วิเคราะห์ใช้เพื่อทำความเข้าใจคุณลักษณะสำคัญของตัวแปรต่าง ๆ ภายในชุดข้อมูล ซึ่งประกอบด้วย (1) การวิเคราะห์สถานะและการแจกแจงของตัวแปร (2) การวิเคราะห์ความสัมพันธ์ระหว่างตัวแปรตามกับตัวแปรอิสระ รวมทั้งความสัมพันธ์ระหว่างตัวแปรอิสระ (3) การวิเคราะห์รูปแบบการสูญหายของข้อมูล และ (4) ความผิดปกติที่อาจเกิดขึ้นในข้อมูล กระบวนการในส่วนของการสำรวจนี้เป็นกระบวนการทวนซ้ำและอาจมีการสลับไปมาระหว่างการใช้ทัศนภาพข้อมูลเชิงสำรวจ และการใช้เทคนิคการวิเคราะห์เชิงปริมาณ (จุด b) เข้ามาช่วย สารสนเทศที่ได้จากกระบวนส่วนนี้จะสามารถใช้เป็นแนวทางเพื่อจัดข้อมูลของตัวแปรอิสระให้เหมาะสมและมีประสิทธิภาพสูงที่สำหรับการพัฒนาโมเดลทำนายต่อไป เรียกขั้นตอนนี้ว่า feature engineering (จุด c) เมื่อสิ้นสุดขั้นตอนนี้ผลผลิตที่ควรได้คือชุดข้อมูลต้นแบบที่ประกอบด้วยตัวแปรตาม และตัวแปรอิสระที่ผ่านการคัดเลือกหรือทำ feature engineering มาแล้ว และอยู่ในรูปแบบที่พร้อมจะนำไปวิเคราะห์</p>
<p>เมื่อได้ชุดข้อมูลต้นแบบมาเรียบร้อยแล้ว ผู้วิเคราะห์จะนำชุดข้อมูลดังกล่าวไปเป็นต้นแบบให้อัลกอริทึมการเรียนรู้ของเครื่องหลาย ๆ ตัวได้เรียนรู้ เพื่อพัฒนาเป็นโมเดลทำนาย (จุด d) จากรูปจะเห็นว่าอัลกอริทึมที่ถูกเลือกมาใช้จำนวน 4 อัลกอริทึม ทั้งนี้อัลกอริทึมส่วนใหญ่มักมีส่วนประกอบที่เรียกว่า hyperparameters ที่ต้องกำหนดค่าด้วยการปรับแต่ง (tuning) จากรูปจะเห็นว่าการเรียนรู้ในแต่ละอัลกอริทึมจะมีขั้นตอนของการเรียนรู้ และการปรับแต่ง hyperparameters ที่ต้องดำเนินการแบบทวนซ้ำสลับไปมาจนกระทั่งได้โมเดลที่มีประสิทธิภาพสูงสุด ทั้งนี้เมื่อได้โมเดลดังกล่าวแล้ว ผู้วิเคราะห์จะนำโมเดลที่พัฒนาได้ไปประเมินประสิทธิภาพการทำนายของโมเดล การดำเนินงานในส่วนนี้จะมีการใช้ทั้งการวิเคราะห์เชิงปริมาณผ่านค่าสถิติต่าง ๆ เช่น evaluation metrics ต่าง ๆ ที่ใช้ประเมินประสิทธิภาพการทำนาย รวมทั้งยังอาจมีการใช้ EDA อีก เพื่อวิเคราะห์ประสิทธิภาพ หรือข้อจำกัดของแต่ละโมเดลในการทำนายผลลัพธ์ที่ต้องการ (จุด e และ f)</p>
<p>สารสนเทศที่ได้จากการวิเคราะห์ประสิทธิภาพของโมเดลจะเป็นตัวกำหนดการดำเนินงานต่อไปของผู้วิเคราะห์ โดยอาจจำแนกเป็นสองกรณี กรณีแรกคือหากโมเดลมีประสิทธิภาพในการทำนายสูงอยู่ระดับที่สามารถนำไปใช้งานได้แล้วผู้วิเคราะห์จะหยุดการดำเนินงานไว้ที่ขั้นตอนนี้แล้วนำโมเดลดังกล่าวไปใช้งานต่อไป กรณีที่สองหากโมเดลทำนายที่พัฒนาขึ้นยังมีประสิทธิภาพไม่ถึงเกณฑ์ที่กำหนด ผู้วิเคราะห์สามารถใช้สารสนเทศจาก EDA ในจุด f ประกอบการคัดเลือกโมเดลเบื้องต้น และปรับแต่งโมเดลรวมทั้งอาจดำเนินการทำ feature engineering อีกครั้งหนึ่งเพื่อเพิ่มประสิทธิภาพการทำนายให้กับโมเดล (จุด h) เมื่อได้โมเดลสุดท้ายแล้วผู้วิเคราะห์สามารถเปรียบเทียบประสิทธิภาพระหว่างโมเดลคู่แข่งขันโดยใข้ชุดข้อมูลทดสอบ (test dataset) แล้วเลือกโมเดลที่ดีที่สุดไปใช้งาน</p>
<p>ส่วนของการนำโมเดลไปใช้งาน ต้องทำความเข้าใจว่า ML model ที่พัฒนาขึ้นนั้นเป็นเหมือนสมองซึ่งต้องเข้าไปอยู่ในโปรแกรมหรือ application สักตัวหนึ่ง โดยโปรแกรมดังกล่าวจะมีหน้าที่หลัก ๆ เช่นมี interface สำหรับรับข้อมูลจากผู้ใช้ เพื่อนำไปประมวลผลด้วยโมเดลทำนายที่เราสร้างขึ้น และรายงานผลการทำนาย/จำแนก ที่ได้จากโมเดลให้แก่ผู้ใช้ ทั้งนี้โปรแกรมดังกล่าวยังอาจมีส่วนอื่น ๆ ที่ยอมให้ผู้ใช้เลือกหรือปรับแต่งการทำงานของโปรแกรมได้ ทั้งนี้ขึ้นอยู่กับวัตถุประสงค์การใช้งาน ตัวอย่างด้านล่างแสดงโปรแกรมทำนายผลการเรียนของนิสิต <a href="https://siwachoat.shinyapps.io/reportandpredict/?_ga=2.42051557.1707159165.1666195773-1113918738.1613372414&amp;utm_source=KruRooTeller">KruRooTeller</a></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1909139629.png" class="img-fluid figure-img" style="width:90.0%" alt="ระบบ KruRooTeller"></p>
<p></p><figcaption class="figure-caption">ระบบ KruRooTeller</figcaption><p></p>
</figure>
</div>
<p>เนื้อหาส่วนที่เหลือของบทเรียนนี้จะกล่าวถึงกระบวนการในส่วนของการพัฒนา supervised learning models โดยจะกล่าวถึงมโนทัศน์ที่จำเป็นก่อน จากนั้นจึงกล่าวถึงกระบวนการพัฒนาโมเดลดังกล่าว รายละเอียดมีดังนี้</p>
<div style="page-break-after: always;"></div>
<section id="bias-and-variance-in-ml-models" class="level2">
<h2 class="anchored" data-anchor-id="bias-and-variance-in-ml-models">3.1 Bias and Variance in ML models</h2>
<p>พิจารณารูป 18 แสดงการ fit โมเดลทำนาย 3 แบบกับชุดข้อมูลฝึกหัดชุดหนึ่ง จะเห็นว่าแต่ละโมเดลมีความสามารถในการเรียนรู้ความสัมพันธ์ที่เกิดขึ้นในชุดข้อมูลแตกต่างกัน ความแตกต่างระหว่างค่าจริงของตัวแปรตามในชุดข้อมูลฝึกหัดกับค่าทำนายที่ได้จากโมเดล เรียกว่า <strong>ความลำเอียง (bias)</strong> <strong>จากรูป 16 ผู้อ่านคิดว่าโมเดลใดที่มีประสิทธิภาพในการทำนายสูงที่สุดเพราะเหตุใด ?</strong></p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">regression model on training dataset</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>พิจารณารูป 19 ผู้วิเคราะห์ได้นำโมเดลทำนายทั้ง 3 แบบ ที่พัฒนาจากชุดข้อมูลฝึกหัดมาใช้ทำนายข้อมูลใหม่ที่โมเดลทั้ง 3 ไม่เคยได้เรียนรู้มาก่อน ความแตกต่างระหว่างค่าจริงของตัวแปรตามในชุดข้อมูลใหม่ (หรือชุดข้อมูลที่ไม่ได้ใช้ในขั้นการพัฒนาโมเดล) กับค่าทำนายของโมเดล เรียกว่า <strong>ความแปรปรวน (variance)</strong> ความแปรปรวนของโมเดลทั้ง 3 เป็นอย่างไร?</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">regression model on new dataset</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>จากตัวอย่างข้างต้นจะเห็นว่า ถึงแม้จะสามารถพัฒนาโมเดลทำนายให้สามารถเรียนรู้ความสัมพันธ์ภายในชุดข้อมูลฝึกหัดได้เป็นอย่างดี (มีความลำเอียงต่ำที่สุดแล้ว) แต่ก็ไม่ใช่เงื่อนไขเพียงพอที่จะสรุปได้ว่าโมเดลทำนายดังกล่าวจะมีประสิทธิภาพในการทำนายได้ดีในกรณีทั่วไป การตรวจสอบอีกชั้นหนึ่งคือตรวจสอบความแปรปรวนของโมเดลทำนาย โดยนำโมเดลดังกล่าวไปทำนายชุดข้อมูลที่ไม่เคยได้เรียนรู้มาก่อน โมเดลที่มีทั้งความลำเอียงและความแปรปรวนต่ำจึงเป็นโมเดลที่มีประสิทธิภาพที่จะนำไปใช้ในกรณีทั่วไป</p>
<p>ในเชิงอุดมคติ ผู้วิเคราะห์ต้องการให้ทั้งความลำเอียง และความแปรปรวนมีค่าต่ำที่สุดเท่าที่จะสามารถต่ำได้ แต่ในความเป็นจริงความคลาดเคลื่อนทั้งสองไม่ควบคุมให้ต่ำที่สุดพร้อมกันได้ <strong>(เพราะอะไร?)</strong> รูป 20 ด้านล่างแสดงความสัมพันธ์ระหว่างความลำเอียง และความแปรปรวน ซึ่งจะเห็นว่ามีการแปรผกผันซึ่งกันและกัน โมเดลที่มีความลำเอียงสูงมีแนวโน้มที่จะมีความแปรปรวนต่ำ และในทางกลับกันโมเดลที่มีความลำเอียงต่ำจะมีแนวโน้มที่มีความแปรปรวนสูง <strong>ดังนั้นวัตถุประสงค์ของการพัฒนาโมเดลจึงเป็นการหาจุดที่ดีที่สุดที่ทำให้ความคลาดเคลื่อนทั้งสองอยู่ในจุดที่ต่ำที่สุดเท่าที่จะเป็นไปได้</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-712567945.png" class="img-fluid figure-img" style="width:60.0%" alt="bias and variance trace-off"></p>
<p></p><figcaption class="figure-caption">bias and variance trace-off</figcaption><p></p>
</figure>
</div>
</section>
<section id="underfitting-overfitting-และ-good-fit-models" class="level2">
<h2 class="anchored" data-anchor-id="underfitting-overfitting-และ-good-fit-models">3.2 Underfitting, Overfitting และ Good fit models</h2>
<p>หากจำแนกโมเดลทำนายที่ถูกพัฒนาขึ้นตามประสิทธิภาพการทำนายของโมเดล อาจจำแนกได้เป็น 3 ประเภท ได้แก่</p>
<ol type="1">
<li>underfitting models คือโมเดลที่มีความลำเอียงสูง ความลำเอียงเป็นความคลาดเคลื่อนที่เป็นระบบ อันเนื่องมาจากโมเดลทำนายที่พัฒนาขึ้นยังไม่สามารถเรียนรู้แนวโน้มหรือรูปแบบความสัมพันธ์หลักระหว่างตัวแปรภายในชุดข้อมูลฝึกหัดได้ดีเพียงพอ จากรูป 21 ซ้ายมือ จะเห็นว่าแนวโน้มความสัมพันธ์ตามธรรมชาติระหว่างตัวแปรตามกับตัวแปรอิสระคือความสัมพันธ์เชิงเส้นโค้ง แต่โมเดลทำนายที่พัฒนาขึ้นอยู่ในรูปแบบเส้นตรง ความแตกต่างระหว่างรูปแบบความสัมพันธ์ดังกล่าวก่อให้เกิดความลำเอียงขึ้น และเรียกโมเดลที่มีความลำเอียงในระดับที่มากเกินไปนี้ว่า underfitting model</li>
<li>overfitting models คือโมเดลที่มีความแปรปรวนสูง ความแปรปรวนเกิดขึ้นจากการที่โมเดลทำนายที่พัฒนาขึ้นสามารถเรียนรู้ความสัมพันธ์ในชุดข้อมูลฝึกหัดได้ดีมากเกินไป จนขาดความยืดหยุ่นในการนำโมเดลดังกล่าวไปใช้ในกรณีทั่วไป ดังตัวอย่างในรูป 21 ขวามือ จากรูปจะเห็นว่าโมเดลสามารถเรียนรู้ความสัมพันธ์ได้เกือบสมบูรณ์ แต่หากนำโมเดลนี้ไปใช้ทำนายข้อมูลใหม่ที่อยู่นอกเหนือจากชุดข้อมูลที่โมเดลนี้ได้เรียนรู้มีแนวโน้มสูงที่จะเกิดความคลาดเคลื่อนในการทำนาย</li>
<li>good fit models คือโมเดลที่สามารถสมดุลความลำเอียงและความแปรปรวนให้มีค่าต่ำที่สุดเท่าที่จะเป็นไปได้</li>
</ol>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1638148101.png" class="img-fluid figure-img" alt="underfitting, good fit, and overfitting model"></p>
<p></p><figcaption class="figure-caption">underfitting, good fit, and overfitting model</figcaption><p></p>
</figure>
</div>
</section>
<section id="training-validation-and-test-dataset" class="level2">
<h2 class="anchored" data-anchor-id="training-validation-and-test-dataset">3.3 Training, validation, and Test Dataset</h2>
<p>จาก concept ข้างต้นจะเห็นว่าในกระบวนการพัฒนาโมเดลผู้วิเคราะห์จะให้ความสำคัญกับประสิทธิภาพในการทำนายของโมเดลเฉพาะด้านความลำเอียงไม่ได้ ยังต้องคำนึงถึงด้านความแปรปรวนด้วย การพัฒนาโมเดลการเรียนรู้ของเครื่องจึงจะมีแค่ชุดข้อมูลฝึกหัดไม่ได้ ยังต้องมีชุดข้อมูลอีกชุดหนึ่งเพื่อเอาไว้ตรวจสอบความแปรปรวนของโมเดลด้วย ในเชิงเทคนิคเรียกชุดข้อมูลนี้ว่า <strong>ชุดข้อมูลทดสอบ (test dataset)</strong></p>
<p>ภายในอัลกอริทึม supervised learning จะมีส่วนประกอบหลัก ๆ ได้แก่ อัลกอริทึม พารามิเตอร์ และ ไฮเปอร์พารามิเตอร์</p>
<ul>
<li><p><strong>อัลกอริทึม</strong> เป็นส่วนของวิธีการเรียนรู้ของสำหรับแต่ละการเรียนรู้ของเครื่องที่ใช้ในการเรียนรู้หรือสกัดสารสนเทศจากข้อมูลในชุดข้อมูลฝึกหัด</p></li>
<li><p><strong>พารามิเตอร์</strong> <strong>(parameters)</strong> ส่วนที่ทำให้การเรียนรู้ของเครื่อง fit กับข้อมูล กล่าวง่าย ๆ คือค่าของพารามิเตอร์ที่เปลี่ยนแปลงไป จะทำให้รูปแบบการเรียนรู้มีการเปลี่ยนไป ค่าพารามิเตอร์นี้สามารถประมาณได้จากข้อมูลด้วยวิธีการทางสถิติ/คณิตศาสตร์ ตัวอย่างของพารามิเตอร์เช่น ใน linear regression model มีพารามิเตอร์คือ สัมประสิทธิ์จุดตัดแกน และสัมประสิทธิ์ความชัน เป็นต้น อย่างไรก็ตามบางอัลกอริทึมไม่ได้มีพารามิเตอร์ของโมเดล เช่น K-NN เป็นต้น</p></li>
<li><p><strong>ไฮเปอร์พารามิเตอร์ (Hyperparameters)</strong> เป็นพารามิเตอร์ประเภทหนึ่งในอัลกอริทึมการเรียนรู้ของเครื่อง พารามิเตอร์ประเภทนี้ไม่สามารถประมาณค่าจากข้อมูลโดยตรงด้วยวิธีการทางสถิติ แต่จะใช้การกำหนด/ปรับแต่งค่าโดยตัวผู้วิเคราะห์เอง <strong>ในเชิงเทคนิคเรียกการปรับแต่งค่าดังกล่าวว่า hyperparameter tuning</strong> การปรับแต่งค่าของ hyperparameter ดังกล่าวจะใช้วิธีการทดลองกำหนดค่า hyperparameter จำนวนหนึ่งให้กับอัลกอริทึม จากนั้นเลือกใช้ค่า hyperparameter ที่ทำให้ค่าประสิทธิภาพของโมเดลทำนายสูงที่สุด ทั้งนี้การพิจารณาประสิทธิภาพดังกล่าวจะพิจารณาบนชุดข้อมูลอีกชุดหนึ่งที่เรียกว่า <strong>validation dataset</strong></p></li>
</ul>
<p>จากที่กล่าวข้างต้นจะเห็นว่าในกระบวนการพัฒนาโมเดลการเรียนรู้ของเครื่อง ต้องการชุดข้อมูลทั้งหมดจำนวน 3 ชุด ได้แก่ training, validation และ test dataset โดยที่ training และ validation dataset เป็นชุดข้อมูลที่ใช้ในระยะพัฒนาการเรียนรู้ของโมเดลให้มีประสิทธิภาพสูงสุด ส่วน test dataset เป็นชุดข้อมูลที่ใช้ตรวจสอบประสิทธิภาพด้านความเป็นนัยทั่วไปแต่จะไม่ได้มีส่วนเกี่ยวข้องกับระยะการพัฒนาการเรียนรู้ของโมเดล</p>
<div style="page-break-after: always;"></div>
</section>
<section id="data-partitioning" class="level2">
<h2 class="anchored" data-anchor-id="data-partitioning">3.4 Data Partitioning</h2>
<p>ในทางปฏิบัติผู้วิเคราะห์มักมีข้อมูลต้นฉบับเพียงชุดเดียวเท่านั้นแต่ละใช้การแบ่งส่วนข้อมูลโดยใช้วิธีการสุ่มตัวอย่าง (random sampling) เพื่อสร้าง training, validation และ test dataset รูปด้านล่างแสดงลักษณะการแบ่งส่วนข้อมูล</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-2117384298.png" class="img-fluid figure-img" style="width:40.0%" alt="training, validation และ testing dataset"></p>
<p></p><figcaption class="figure-caption">training, validation และ testing dataset</figcaption><p></p>
</figure>
</div>
<p>โดยปกติการแบ่งส่วนข้อมูลดังกล่าวไม่ได้มีกฎเกณฑ์ตายตัวว่าควรแบ่งส่วนใดอย่างละเท่าไหร่ โดยปกติผู้วิเคราะห์มักกำหนดสัดส่วนระหว่าง training + validation dataset กับ test dataset เป็น 80 : 20, 75 : 25, 70 : 30, 60: 40 หรือ 50: 50 ขึ้นอยู่กับว่าชุดข้อมูลต้นฉบับที่มีนั้นมีขนาดใหญ่มากเพียงใด นอกจากนี้การแบ่งส่วนข้อมูลด้วยวิธีการสุ่มตัวอย่างอาจจำแนกเป็น 2 วิธีการ วิธีการแรกคือการสุ่มตัวอย่างแบบง่าย (simple random sampling: SRS) และวิธีการที่สองคือการสุ่มตัวอย่างแบบชั้นภูมิ (stratified random sampling)</p>
<section id="ชดขอมล-mpg" class="level3">
<h3 class="anchored" data-anchor-id="ชดขอมล-mpg">ชุดข้อมูล <code>mpg</code></h3>
<p>ชุดข้อมูลที่ใช้เป็นตัวอย่างในหัวข้อนี้จะใช้ dataset <code>mpg</code> ที่เป็นชุดข้อมูลตัวอย่างซึ่งถูกติดตั้งมาพร้อมกับการติดตั้งโปรแกรม R อยู่แล้ว ผู้วิเคราะห์สามารถเรียกดูข้อมูลภายในชุดข้อมูลดังกล่าวได้โดยใช้คำสั่งพื้นฐานต่าง ๆ เช่น <code>head()</code>, <code>str()</code>, <code>glimpse()</code> หรือ <code>summary()</code> เป็นต้น</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mpg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
  manufacturer model displ  year   cyl trans      drv     cty   hwy fl    class 
  &lt;chr&gt;        &lt;chr&gt; &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; 
1 audi         a4      1.8  1999     4 auto(l5)   f        18    29 p     compa…
2 audi         a4      1.8  1999     4 manual(m5) f        21    29 p     compa…
3 audi         a4      2    2008     4 manual(m6) f        20    31 p     compa…
4 audi         a4      2    2008     4 auto(av)   f        21    30 p     compa…
5 audi         a4      2.8  1999     6 auto(l5)   f        16    26 p     compa…
6 audi         a4      2.8  1999     6 manual(m5) f        18    26 p     compa…</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(mpg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 234
Columns: 11
$ manufacturer &lt;chr&gt; "audi", "audi", "audi", "audi", "audi", "audi", "audi", "…
$ model        &lt;chr&gt; "a4", "a4", "a4", "a4", "a4", "a4", "a4", "a4 quattro", "…
$ displ        &lt;dbl&gt; 1.8, 1.8, 2.0, 2.0, 2.8, 2.8, 3.1, 1.8, 1.8, 2.0, 2.0, 2.…
$ year         &lt;int&gt; 1999, 1999, 2008, 2008, 1999, 1999, 2008, 1999, 1999, 200…
$ cyl          &lt;int&gt; 4, 4, 4, 4, 6, 6, 6, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 8, 8, …
$ trans        &lt;chr&gt; "auto(l5)", "manual(m5)", "manual(m6)", "auto(av)", "auto…
$ drv          &lt;chr&gt; "f", "f", "f", "f", "f", "f", "f", "4", "4", "4", "4", "4…
$ cty          &lt;int&gt; 18, 21, 20, 21, 16, 18, 18, 18, 16, 20, 19, 15, 17, 17, 1…
$ hwy          &lt;int&gt; 29, 29, 31, 30, 26, 26, 27, 26, 25, 28, 27, 25, 25, 25, 2…
$ fl           &lt;chr&gt; "p", "p", "p", "p", "p", "p", "p", "p", "p", "p", "p", "p…
$ class        &lt;chr&gt; "compact", "compact", "compact", "compact", "compact", "c…</code></pre>
</div>
</div>
</section>
<section id="การแบงขอมลดวยการสมอยางงาย" class="level3">
<h3 class="anchored" data-anchor-id="การแบงขอมลดวยการสมอยางงาย">การแบ่งข้อมูลด้วยการสุ่มอย่างง่าย</h3>
<p>การแบ่งด้วย simple random sampling เป็นการแบ่งโดยสุ่มข้อมูลตามจำนวนที่กำหนดออกมาเป็นชุดข้อมูล training dataset หรือ test dataset โดยการสุ่มดังกล่าวมีข้อสมมุติว่าหน่วยข้อมูลทุกหน่อยในชุดข้อมูลต้นฉบับมีโอกาสที่จะถูกสุ่มขึ้นมาเท่ากันทั้งหมด การแบ่งข้อมูลด้วยวิธีการนี้ใน R สามารถทำได้หลายวิธี แต่ในบทความนี้จะใช้วิธีที่อยู่ภายใต้ framework ของ tidymodels การแบ่งข้อมูลด้วยวิธีการดังกล่าวมีสองขั้นตอน <strong>ขั้นแรก</strong> คือการสร้างกรอบของการแบ่งข้อมูลออกเป็น training และ test data สามารถทำได้ด้วยฟังก์ชัน <code>initial_split()</code> ของ package rsample อาร์กิวเมนท์สำคัญที่จะต้องระบุในฟังก์ชันได้แก่ <code>data</code> และ <code>prop</code><strong>ขั้นที่สอง</strong> คือการแบ่งข้อมูลตามกรอบในขั้นตอนแรก โดยจะใช้ฟังก์ชัน <code>training()</code> เพื่อแบ่งชุด training dataset ออกมา และใช้ฟังก์ชัน <code>testing()</code> เพื่อแบ่งชุดข้อมูล test dataset ออกมา</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import rsample</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rsample)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># generate sampling frame</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>mpg_split1 <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="at">data =</span> mpg, <span class="at">prop =</span> <span class="fl">0.75</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>mpg_split1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;175/59/234&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create training and test dataset</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>train_srs <span class="ot">&lt;-</span> mpg_split1 <span class="sc">%&gt;%</span> <span class="fu">training</span>()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>test_srs <span class="ot">&lt;-</span> mpg_split1 <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="การแบงขอมลดวยการสมแบบชนภม" class="level3">
<h3 class="anchored" data-anchor-id="การแบงขอมลดวยการสมแบบชนภม">การแบ่งข้อมูลด้วยการสุ่มแบบชั้นภูมิ</h3>
<p>การแบ่งชุดข้อมูลด้วยการสุ่มแบบชั้นภูมิสามารถทำได้ด้วยฟังก์ชัน <code>initial_split()</code> เช่นเดียวกัน แต่จะต้องมีการระบุอาร์กิวเมนท์ของฟังก์ชันเพิ่มเติมได้แก่ <code>strata</code> เพื่อระบุตัวแปรตามหรือตัวแปรเกณฑ์ที่จะใช้แบ่งชั้นภูมิก่อนการสุ่มตัวอย่าง และ <code>breaks</code> ใช้กำหนดจำนวนอันตรภาคชั้นของตัวแปรตามหรือตัวแปรเกณฑ์ที่จะใช้แบ่งชั้นภูมิหากตัวแปรดังกล่าวเป็นตัวแปรเชิงปริมาณ ค่าเริ่มต้นของอาร์กิวเมนท์นี้กำหนดให้ <code>breaks = 4</code>ตัวอย่างต่อไปนี้แสดงการแบ่งชุดข้อมูล training และ test ด้วยการสุ่มแบบชั้นภูมิ</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>mpg_split2 <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="at">data =</span> mpg, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">prop =</span> <span class="fl">0.75</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">strata =</span> <span class="st">"hwy"</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">breaks =</span> <span class="dv">10</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>train_str <span class="ot">&lt;-</span> mpg_split2 <span class="sc">%&gt;%</span> <span class="fu">training</span>()</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>test_str <span class="ot">&lt;-</span> mpg_split2 <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>รูปด้านล่างแสดงการเปรียบเทียบการแจกแจงของตัวแปรตามระหว่างชุดข้อมูลต้นฉบับ (full dataset), training และ test dataset ที่แบ่งด้วยวิธีการสุ่มตัวอย่างแบบง่าย และแบบชั้นภูมิ</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">เปรียบเทียบระหว่าง SRS กับ STR</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>การสุ่มแบบชั้นภูมิเหมาะสำหรับการพัฒนา classification models เมื่อสัดส่วนของค่าที่เป็นไปได้ของตัวแปรตามมีความแตกต่างกันมาก ๆ หรือมีบางค่าสังเกตของตัวแปรตามที่มีสัดส่วนการเกิดที่น้อยเมื่อเปรียบเทียบกับค่าสังเกตอื่น ๆ (imbalanced outcome) นอกจากนี้ยังเหมาะกับการพัฒนา regression models เมื่อตัวแปรตามมีลักษณะการแจกแจงแบบเบ้ขวา</p>
</section>
</section>
<section id="การสมซำ-resampling" class="level2">
<h2 class="anchored" data-anchor-id="การสมซำ-resampling">3.5 การสุ่มซ้ำ (resampling)</h2>
<p>อัลกอริทึมการเรียนรู้ของเครื่องหลายตัวมี hyperparameters ที่หากมีการกำหนดค่าที่เหมาะสมจะช่วยพัฒนาการเรียนรู้ได้ดีขึ้นและช่วยให้โมเดลทำนายมีประสิทธิภาพการทำนายที่สูงขึ้นได้ อย่างไรก็ตาม hyperparameters ดังกล่าวไม่สามารถประมาณได้โดยตรงจากข้อมูล แต่ต้องอาศัยการกำหนดค่าเองโดยผู้วิเคราะห์ ดังนั้นในระหว่างการพัฒนาโมเดลจึงมีความจำเป็นที่ผู้วิเคราะห์จะต้องทราบประสิทธิภาพการทำนายของโมเดลเมื่อมีการกำหนดค่า hyperparameters ต่าง ๆ เพื่อใช้เป็นสารสนเทศประกอบการกำหนดค่า hyperparameters ดังกล่าว</p>
<p>ด้วยเหตุผลเดียวกับการประเมินประสิทธิภาพของโมเดลด้วยชุดข้อมูลทดสอบ การประเมินประสิทธิภาพในระยะของการพัฒนาโมเดลดังกล่าวไม่ช่วยใช้ข้อมูลจากชุดข้อมูลฝึกหัด เพราะจะทำให้ค่าประสิทธิภาพดังกล่าวมีค่าสูงเกินความเป็นจริงและอาจทำให้การกำหนดค่า hyperparameters มีความคลาดเคลื่อน เพื่อแก้ปัญหาดังกล่าวจึงมีการใช้เทคนิคการสุ่มซ้ำ (resampling) ในการสุ่มชุดข้อมูลย่อยจากชุดข้อมูลฝึกหัด โดยแบ่งชุดข้อมูลฝึกหัดออกเป็นสองชุดข้อมูลย่อย อาจเรียกว่าชุดข้อมูลสำหรับวิเคราะห์ (analysis) ต่อไปจะเรียกว่า traning dataset และชุดข้อมูลสำหรับสำหรับประเมินประสิทธิภาพ (assessment) ซึ่งต่อไปจะเรียกว่า validation dataset ดังรูป 24</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-468626522.png" class="img-fluid figure-img" alt="resampling strategy"></p>
<p></p><figcaption class="figure-caption">resampling strategy</figcaption><p></p>
</figure>
</div>
<p>เนื่องจากเทคนิคการสุ่มซ้ำเป็นการสุ่มแบบที่มีการใส่คืน (sampling with replacement) จึงทำให้ในระยะของการพัฒนาโมเดลผู้วิเคราะห์สามารถทวนซ้ำการสุ่มซ้ำดังกล่าวเพื่อสร้าง training และ validation dataset ได้จำนวนหลายชุด การดำเนินการดังกล่าวช่วยให้การประเมินประสิทธิภาพของโมเดลทำนายภายใต้เงื่อนไขของการกำหนด hyperparameters ต่าง ๆ สามารถทำได้อย่างแม่นยำ</p>
<p>ปัจจุบันมีเทคนิคการสุ่มซ้ำสำหรับการพัฒนาโมเดลทำนายดังกล่าวหลายตัว ได้แก่ K-fold Cross-Validation, Monte Carlo Cross-Validation, Bootstrapping และ Rolling Origin Forecasting รายละเอียดมีดังนี้</p>
<section id="k-fold-cross-validation-และวธการอน-ๆ-ทเกยวของ" class="level3">
<h3 class="anchored" data-anchor-id="k-fold-cross-validation-และวธการอน-ๆ-ทเกยวของ">K-fold Cross-Validation และวิธีการอื่น ๆ ที่เกี่ยวข้อง</h3>
<p>เป็นเทคนิคการสุ่มซ้ำที่นิยมใช้กันอย่างแพร่หลาย เทคนิคนี้จะแบ่งชุดข้อมูล traning dataset โดยใช้การสุ่มแบบใส่คืนออกเป็นข้อมูลชุดย่อยจำนวน K ชุด จากนั้นจะดำเนินการวิเคราะห์และประเมินประสิทธิภาพของโมเดลจำนวน K ครั้ง โดยที่แต่ละครั้งที่จะมีการหมุนเวียนใช้ชุดข้อมูลจำนวน K-1 ชุดเพื่อวิเคราะห์ และใช้ชุดข้อมูลที่เหลืออีก 1 ชุดเพื่อประเมินประสิทธิภาพ</p>
<p>รูป 25 แสดงตัวอย่างของ 5-fold cross-validation จากรูปจะเห็นว่ามีการสุ่มเพื่อแบ่งชุดข้อมูลฝึกหัดออกเป็น 5 ชุดย่อย จากนั้นทวนซ้ำการดำเนินการวิเคราะห์และประเมินประสิทธิภาพของโมเดลจำนวน 5 ครั้ง โดยที่ในแต่ละครั้งจะใช้ชุดข้อมูลย่อยจำนวน 4 ชุด เป็น training dataset เพื่อสร้างโมเดลทำนาย และใช้อีก 1 ชุดที่เหลือเป็น validation dataset เพื่อตรวจสอบประสิทธิภาพของโมเดลทำนาย จากรูปจะเห็นว่าในแต่ละครั้งจะมีการหมุนเวียนชุดข้อมูลที่จะใช้เป็น training และ validation ไปเรื่อย ๆ จนครบ การดำเนินการดังกล่าวจะทำให้ผู้วิเคราะห์มีค่าสถิติที่ใช้ประเมินประสิทธิภาพของโมเดลจำนวน 5 ค่า ผู้วิเคราะห์จะใช้ผลการวิเคราะห์จากค่าสถิติดังกล่าว เช่น ค่าเฉลี่ยของ RMSE หรือ R square ในการประเมินประสิทธิภาพของโมเดลภายใต้เงื่อนไขต่าง ๆ เช่น ภายใต้การกำหนดค่า hyperparameters ต่าง ๆ เป็นต้น</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1150746472.png" class="img-fluid figure-img" alt="5-fold CV (ที่มา : https://towardsdatascience.com/cross-validation-k-fold-vs-monte-carlo-e54df2fc179b)"></p>
<p></p><figcaption class="figure-caption">5-fold CV (ที่มา : https://towardsdatascience.com/cross-validation-k-fold-vs-monte-carlo-e54df2fc179b)</figcaption><p></p>
</figure>
</div>
<p>เนื่องจาก K-fold CV สุ่มเพื่อแบ่งชุดข้อมูลในครั้งแรกเพียงครั้งเดียว และใช้การหมุนเวียนชุดข้อมูลย่อยที่ได้จากการสุ่มดังกล่าวเพื่อวิเคราะห์และประเมินประสิทธิภาพของโมเดล จึงทำให้หน่วยข้อมูลแต่ละหน่วยมีโอกาสที่จะปรากฎอยู่ใน validation dataset ได้เพียงครั้งเดียวดังตัวอย่างในรูป 26 ข้อจำกัดนี้ทำให้ค่าประมาณประสิทธิภาพของโมเดลทำนายที่มีแนวโน้มจะมีความแปรปรวนมากที่สุดเมื่อเปรียบเทียบกับ resampling วิธีการอื่น ๆ การที่จะลดทอนความแปรปรวนดังกล่าวให้น้อยลงสามารถทำได้ด้วยการเพิ่มจำนวน K ให้มากขึ้น โดยจากการศึกษาพบว่าการกำหนดให้ K มีค่าตั้งแต่ 10 ขึ้นไป จะช่วยลดทอนความแปรปรวนของการประเมินประสิทธิภาพได้ อย่างไรก็ตาม K-fold CV ก็ยังมีแนวโน้มที่จะมีความแปรปรวนดังกล่าวมากกว่าการใช้การสุ่มซ้ำแบบอื่นอยู่ดี</p>
<p>อีกข้อจำกัดหนึ่งของการทำ K-fold CV คือการกำหนดค่า K จำนวนมากจะทำให้การประมวลผลต้องดำเนินการหลายรอบและต้องใช้เวลาและทรัพยากรในการประมวลผลที่มากขึ้น ในกรณีที่ข้อมูลและโมเดลมีความซับซ้อนการประมวลผลในขั้นตอนนี้อาจใช้เวลานานหลายชั่วโมงหรือเป็นวันซึ่งอาจไม่คุ้มค่าที่จะดำเนินการในลักษณะดังกล่าว โดยในกรณีที่กำหนดให้ K = n เมื่อ n คือจำนวนหน่วยข้อมูลทั้งหมดจะเรียกการสุ่มนี้ว่า leave-one-out CV (LOOCV) ที่เป็นกรณีสุดโต่งที่สุดของการทำ K fold CV ปัจจุบัน LOOCV ไม่ค่อยถูกใช้งานแล้วเนื่องจากใช้เวลาและทรัพยากรอย่างมาก</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-998799574.png" class="img-fluid figure-img" alt="10-fold CV จากชุดข้อมูลที่มีหน่วยข้อมูลจำนวน 32 หน่วย (ที่มา : Boehmke, and Greenwell (2020))"></p>
<p></p><figcaption class="figure-caption">10-fold CV จากชุดข้อมูลที่มีหน่วยข้อมูลจำนวน 32 หน่วย (ที่มา : Boehmke, and Greenwell (2020))</figcaption><p></p>
</figure>
</div>
<p>เพื่อแก้ปัญหาของ K-fold CV ข้างต้นถึงมีการพัฒนาเทคนิคอีกตัวหนึ่งเรียกว่า repeated K-fold cross-validation เทคนิคดังกล่าวเป็นการทำ K-fold CV ซ้ำ ๆ หลาย ๆ รอบ วิธีการนี้ทำให้หน่วยข้อมูลแต่ละหน่วยสามารถปรากฎอยู่ใน validation dataset ได้มากกว่าหนึ่งครั้ง ซึ่งช่วยให้ความแปรปรวนในการประมาณค่าประสิทธิภาพของโมเดลทำนายลดลงได้</p>
</section>
<section id="monte-carlo-cross-validation" class="level3">
<h3 class="anchored" data-anchor-id="monte-carlo-cross-validation">Monte Carlo Cross-Validation</h3>
<p>ในขณะที่ K-fold CV เป็นวิธีการที่ยอมให้หน่วยข้อมูลแต่ละหน่วยปรากฎใน validation dataset ได้เพียงครั้งเดียว แต่ในทางกลับกัน Monte Carlo CV (MCCV) จะสร้างชุดข้อมูลย่อย K ชุดที่ยอมให้มีหน่วยข้อมูลที่ร่วมกันได้ซึ่งทำให้หน่วยข้อมูลแต่ละหน่วยสามารถปรากฎอยู่ใน validation dataset มากกว่าหนึ่งครั้งและช่วยลดทอนความแปรปรวนในการประมาณค่าประสิทธิภาพของโมเดลลงได้ โดย MCCV มีขั้นตอนการดำเนินการดังนี้</p>
<div style="page-break-after: always;"></div>
<ol type="1">
<li>แบ่งชุดข้อมูลที่จะนำมาพัฒนาโมเดลออกเป็นสองส่วน ได้แก่ ส่วน training dataset และ validation dataset (อาจใช้สัดส่วน 70:30, 80:20, … ตามที่ผู้วิเคราะห์เห็นว่าเหมาะสม)</li>
<li>นำข้อมูลใน training dataset ไปดำเนินการวิเคราะห์ และใช้ validation dataset เพื่อประเมินประสิทธิภาพของโมเดล จากนั้นเก็บค่าประสิทธิภาพดังกล่าวไว้</li>
<li>ทวนซ้ำขั้นตอนที่ 1. ใหม่ การทวนซ้ำอาจทำเป็นจำนวน 100, 500 หรือ 1,000 รอบ ซึ่งเมื่อครบตามจำนวนรอบที่กำหนดแล้วผู้วิเคราะห์จะนำค่าประมาณประสิทธิภาพจากแต่ละรอบมาหาค่าเฉลี่ย</li>
</ol>
<p>รูป 27 แสดงตัวอย่างของการทำ MCCV จำนวน 100 รอบ</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-103001330.png" class="img-fluid figure-img" alt="Monte Carlo CV จำนวน 100 รอบ (ที่มา : https://towardsdatascience.com/cross-validation-k-fold-vs-monte-carlo-e54df2fc179b)"></p>
<p></p><figcaption class="figure-caption">Monte Carlo CV จำนวน 100 รอบ (ที่มา : https://towardsdatascience.com/cross-validation-k-fold-vs-monte-carlo-e54df2fc179b)</figcaption><p></p>
</figure>
</div>
<p>รูป 28 แสดงการเปรียบเทียบผลที่ได้จากการแบ่งชุดข้อมูลระหว่าง 10-fold CV กับ 10 resample MCCV (โดยกำหนดให้สัดส่วนการสุ่มเป็น 90:10) ของชุดข้อมูลต้นฉบับที่มีจำนวน 20 หน่วย จากรูปจะเห็นว่าหน่วยข้อมูลมีโอกาสปรากฎใน validation dataset ได้เพียงครั้งเดียวเมื่อใช้ 10-fold CV แต่สามารถปรากฎได้มากกว่าหนึ่งครั้งเมื่อใช้ 10 resample MCCV</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1721863239.png" class="img-fluid figure-img" alt="ผลที่ได้จากการแบ่งชุดข้อมูลระหว่าง 10-fold CV กับ 10 resample MCCV (โดยกำหนดให้สัดส่วนการสุ่มเป็น 90:10) ของชุดข้อมูลต้นฉบับที่มีจำนวน 20 หน่วย (ที่มา : Max Kuhn and Kjell Johnson (2019))"></p>
<p></p><figcaption class="figure-caption">ผลที่ได้จากการแบ่งชุดข้อมูลระหว่าง 10-fold CV กับ 10 resample MCCV (โดยกำหนดให้สัดส่วนการสุ่มเป็น 90:10) ของชุดข้อมูลต้นฉบับที่มีจำนวน 20 หน่วย (ที่มา : Max Kuhn and Kjell Johnson (2019))</figcaption><p></p>
</figure>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="bootstraping" class="level3">
<h3 class="anchored" data-anchor-id="bootstraping">Bootstraping</h3>
<p>กำหนดให้ชุดข้อมูลต้นฉบับมีขนาด n หน่วย <strong>bootstrap sample</strong> คือตัวอย่างสุ่มขนาด n หน่วย (เท่ากับชุดข้อมูลต้นฉบับ) ที่ได้จากการสุ่มตัวอย่างอย่างง่ายแบบใส่คืน (simple random sampling with replacement) จากชุดข้อมูลต้นฉบับ จากลักษณะของการสุ่มตัวอย่างแบบ bootstrap ข้างต้นจะได้ว่า ความน่าจะเป็นที่หน่วยข้อมูลแต่ละหน่วยจะถูกเลือกในการสุ่มข้อมูลตัวที่ <span class="math inline">\(i\)</span> โดยที่ <span class="math inline">\(i = 1,2,3,...,n\)</span> จะมีค่าเท่ากับ <span class="math inline">\(P(select_i) = \frac{1}{n}\)</span> ซึ่งทำให้ความน่าจะเป็นที่หน่วยข้อมูลจะไม่ถูกเลือกในการสุ่มครั้งที่ <span class="math inline">\(i\)</span> เท่ากับ <span class="math inline">\(P(not \ select)=1-\frac{1}{n}\)</span> ดังนั้นความน่าจะเป็นที่หน่วยข้อมูลแต่ละหน่วยจะอยู่ในตัวอย่างแบบ bootstrap จะมีค่าเท่ากับ <span class="math inline">\((1-\frac{1}{n})^n\)</span> เมื่อ <span class="math inline">\(n \rightarrow \infty\)</span> จะได้ว่าความน่าจะเป็นที่หน่วยข้อมูลแต่ละหน่วยจะปรากฎอยู่ในตัวอย่างแบบ bootstrap มีค่าเท่ากับ 63.2% (การพิสูจน์ใช้คุณสมบัติของ Taylor series) รูป 29 ด้านล่างแสดงลักษณะของตัวอย่างแบบ bootstrap</p>
<p><img src="images/image-1881794685.png" class="img-fluid"></p>
<p>ในกระบวนการพัฒนาโมเดลทำนาย จะใช้ตัวอย่าง bootstrap เป็นชุดข้อมูลสำหรับวิเคราะห์ และใช้ชุดข้อมูลที่เหลือที่ไม่ได้ถูกสุ่มไว้ในตัวอย่าง bootstrap เป็นชุดข้อมูลสำหรับประเมินประสิทธิภาพของโมเดลทำนายระหว่างการพัฒนาโมเดล (เทียบเท่ากับ validation dataset) โดยจะเรียกตัวอย่างที่ไม่ได้ถูกสุ่มไว้ในตัวอย่าง bootstrap ในแต่ละรอบว่า <strong>out-of-bag sample (OOB)</strong></p>
<p>จากคุณลักษณะของตัวอย่าง bootstrap ที่หน่วยข้อมูลแต่ละหน่วยมีโอกาสปรากฏอยู่ในชุดข้อมูล bootstrap ได้มากกว่า 1 ชุด จึงทำให้การประมาณค่าประสิทธิภาพของโมเดลที่ได้จากการสุ่มซ้ำแบบ bootstrap มีแนวโน้มที่จะมีความแปรปรวนต่ำกว่าการสุ่มซ้ำแบบ k-fold CV อย่างไรก็ตามในกรณีที่ข้อมูลต้นฉบับมีขนาดเล็กการสุ่มซ้ำแบบ boostrap มีแนวโน้มที่จะให้ค่าประมาณประสิทธิภาพของโมเดลที่ลำเอียง จึงควรใช้เทคนิคการสุ่มซ้ำแบบ bootstrap เมื่อข้อมูลมีขนาดใหญ่เพียงพอ (n &gt; 1000) (Boehmke, B., &amp; Greenwell, B., 2020)</p>
</section>
</section>
<section id="tidymodels-framework" class="level2">
<h2 class="anchored" data-anchor-id="tidymodels-framework">3.6 Tidymodels Framework</h2>
<p>ปัจจุบันมีเครื่องมือที่ช่วยให้ผู้วิเคราะห์สามารถพัฒนา machine model ได้หลายตัว บทเรียนนี้จะกล่าวถึงการใช้โปรแกรม R เพื่อพัฒนา ML model ดังกล่าว ทั้งนี้ต้องทำความเข้าใจก่อนว่า การทำงานบน R แม้จะเป็นปัญหาเดียวกัน ชุดข้อมูลเดียวกัน แต่ผู้วิเคราะห์ต่างคนกันก็มีทางที่จะดำเนินการด้วยวิธีการที่แตกต่างกันได้ (ใน Python หรือโปรแกรมอื่น ๆ ก็เช่นเดียวกัน) วิธีการหนึ่งใน R ที่สามารถ modeling ได้ง่ายและมีประสิทธิภาพคือการใช้ <strong>tidymodels framework</strong> ดังรูป 23</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-258190158.png" class="img-fluid figure-img" style="width:80.0%" alt="tidymodel framework"></p>
<p></p><figcaption class="figure-caption">tidymodel framework</figcaption><p></p>
</figure>
</div>
<ul>
<li><p><strong>package-rsample</strong> ใช้ในงาน resampling ข้อมูล เช่นการสร้าง training/validation/test dataset การสร้าง cross-validation dataset หรือการสร้าง bootstrape dataset ซึ่งได้กล่าวการใช้งานเบื้องต้นไปแล้ว</p></li>
<li><p><strong>package-recipes</strong> ใช้แปลง/แก้ปัญหาที่เกิดขึ้นในข้อมูลของตัวแปรที่ใช้ในการพัฒนาโมเดล ขั้นตอนนี้เรียกว่า feature engineering</p></li>
<li><p><strong>package-parsnip</strong> ใช้ fit machine learning กับข้อมูล</p></li>
<li><p><strong>package-Tune</strong> และ <strong>package-dials</strong> มีฟังก์ชันที่อำนวยความสะดวกในการ fine tune hyperparameter ของโมเดลเพื่อเพิ่มประสิทธิภาพการทำนายของโมเดลให้สูงที่สุด</p></li>
<li><p><strong>package-yardstick</strong> มีฟังก์ชันของ metric ที่ใช้ประเมินประสิทธิภาพของโมเดลทำนาย</p></li>
</ul>
<p>tidymodels ถูกพัฒนาขึ้นโดยได้รับการออกแบบให้สามารถทำซ้ำกระบวนการพัฒนาโมเดลได้ง่าย โดยใช้ไวยกรณ์ของภาษาในลักษณะเดียวกัน และถูกออกแบบโดยเน้นใช้กับ supervised learning เป็นหลัก ผู้ใช้งานไม่จำเป็นต้องติดตั้งทุก package ในข้างต้นด้วยตนเอง แต่ติดตั้งเพียง package-tidymodels ก็สามารถใช้งานทุก package ภายใต้ framework ดังกล่าวได้แล้ว โดยการพิมพ์คำสั่งต่อไปนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidymodels"</span>) <span class="co"># ดาวน์โหลดและติดตั้ง tidymodels</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels) <span class="co"># เรียกใช้ tidymodels</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.0.0 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.3     ✔ recipes      1.0.2
✔ dials        1.1.0     ✔ tune         1.0.1
✔ infer        1.0.4     ✔ workflows    1.1.2
✔ modeldata    1.0.1     ✔ workflowsets 1.0.0
✔ parsnip      1.0.3     ✔ yardstick    1.1.0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ gridExtra::combine() masks dplyr::combine()
✖ scales::discard()    masks purrr::discard()
✖ dplyr::filter()      masks stats::filter()
✖ recipes::fixed()     masks stringr::fixed()
✖ dplyr::lag()         masks stats::lag()
✖ yardstick::spec()    masks readr::spec()
✖ recipes::step()      masks stats::step()
• Dig deeper into tidy modeling with R at https://www.tmwr.org</code></pre>
</div>
</div>
<section id="fitting-linear-regression-using-parsnip" class="level3">
<h3 class="anchored" data-anchor-id="fitting-linear-regression-using-parsnip">Fitting Linear Regression using parsnip</h3>
<p><img src="images/image-538379331.png" class="img-fluid" style="width:30.0%"></p>
<p>การ fit machine learning model กับข้อมูลด้วย R ในยุคเริ่มแรกค่อนข้างมีความยากลำบากพอสมควร เพราะ R ไม่ได้มี package ที่เป็น framework รวมสำหรับการ fit ML model ดังกล่าว การที่จะ fit ML model ในงานหนึ่ง ๆ ผู้วิเคราะห์อาจจะต้องยุ่งเกี่ยวกับ package จำนวนมาก เช่น</p>
<ul>
<li><p>package rpart สำหรับ fit decision tree</p></li>
<li><p>package glmnet สำหรับ fit regularized regression model</p></li>
<li><p>package knn สำหรับ fit K-NN model</p></li>
</ul>
<p>โดย package ที่แตกต่างกันมักมีแนวคิดและไวยกรณ์การเขียนคำสั่งที่แตกต่างกัน ทำให้เป็นอุปสรรคต่อการทำงานโดยเฉพาะการทำซ้ำในอนาคต จากปัญหานี้ tidymodels จึงมีการพัฒนา package parsnip ขึ้นเพื่อเป็น interface สำหรับใช้ package ใน R ที่เกี่ยวข้องกับการ fit supervised learning ทั้งนี้ parsnip ได้ถูกออกแบบมาให้การสั่งงานทั้งหมดอยู่ภายใต้ไวยกรณ์แบบเดียวกัน ปัจจุบันการ fit ML models ใน R จึงดำเนินการได้ง่ายขึ้นอย่างมาก</p>
<p>ขั้นตอนการ fit ML models ด้วย parsnip มี 2 ขั้นตอน ได้แก่ การระบุโมเดล และการประมวลผล รายละเอียดมีดังนี้</p>
<section id="การระบโมเดล-model-specification" class="level4">
<h4 class="anchored" data-anchor-id="การระบโมเดล-model-specification">(1) การระบุโมเดล (model specification)</h4>
<p>การระบุโมเดลใน parsnip มีส่วนประกอบ 3 ส่วนที่จำเป็นได้แก่</p>
<ul>
<li><p><strong>model type</strong> หรืออัลกอริทึมการเรียนรู้ของเครื่องที่ผู้วิเคราะห์จะใช้ในการทำงาน</p></li>
<li><p><strong>engine</strong> หรือ package ของ R ที่จะใช้สำหรับประมวลผล model type ที่เลือก</p></li>
<li><p><strong>mode</strong> สำหรับกำหนดว่าปัญหาที่ทำงานด้วยอยู่นี้เป็น regression หรือ classification</p></li>
</ul>
<p>รายละเอียดว่าผู้วิเคราะห์สามารถกำหนด model type, engine และ mode แบบใดได้บ้างและต้องกำหนดอย่างไร สามารถศึกษาได้จาก <a href="https://www.tidymodels.org/find/parsnip/" class="uri">https://www.tidymodels.org/find/parsnip/</a> รูป 24 ด้านล่างแสดงค้นหาสำหรับอัลกอริทึม linear regression จากผลการค้นหาในรูปด้านล่างจะเห็นว่าการ fit linear regression ด้วย parsnip สามารถทำได้ด้วย model type คือ <code>linear_reg()</code> เมื่อพิจารณาในคอลัมน์ engine จะเห็นว่าการ fit linear regression มี engine จำนวนมากที่สามารถใช้เพื่อประมาณค่าพารามิเตอร์ของโมเดลได้ engine ดังกล่าวจริง ๆ แล้วคือ package ต่าง ๆ ของ R ที่ใช้ประมวลผล mode type ที่เลือกไว้ได้ ผู้อ่านจะเห็นว่า model type แบบ <code>linear_reg</code> มี engine ที่สามารถใช้ประมวลผลได้จำนวนมาก ซึ่งมีความเหมือนและความแตกต่างกัน เนื้อหาส่วนนี้มีความละเอียดพอสมควรจึงจะกล่าวถึงในบท regression model ต่อไป</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-33185451.png" class="img-fluid figure-img" style="width:70.0%" alt="parsnip manual"></p>
<p></p><figcaption class="figure-caption">parsnip manual</figcaption><p></p>
</figure>
</div>
<p>ในคู่มือข้างต้นยังมีเครื่องมือให้ค้นหาการกำหนดอาร์กิวเมนท์ของฟังก์ชัน model type ในข้างต้น จากรูป 25 จะเห็นรายละเอียดในการกำหนดอาร์กิวเมนท์ของฟังก์ชัน <code>linear_reg()</code> เมื่อกำหนด engine ในลักษณะต่าง ๆ</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1313501193.png" class="img-fluid figure-img" style="width:70.0%" alt="argument ในฟังก์ชัน model type"></p>
<p></p><figcaption class="figure-caption">argument ในฟังก์ชัน model type</figcaption><p></p>
</figure>
</div>
<div style="page-break-after: always;"></div>
<p>ความหมายของการกำหนดอาร์กิวเมนท์แต่ละค่าสามารถศึกษาได้จากคู่มือของฟังก์ชัน <code>linear_reg()</code> ซึ่งสามารถกด hyperlink จากคู่มือได้เลย (คู่มือ <a href="https://parsnip.tidymodels.org/reference/linear_reg.html"><code>linear_reg()</code></a>)</p>
<p>เอกสารเพิ่มเติมเกี่ยวกับ package parsnip</p>
<ul>
<li><p><a href="https://cran.r-project.org/web/packages/parsnip/parsnip.pdf" class="uri">https://cran.r-project.org/web/packages/parsnip/parsnip.pdf</a></p></li>
<li><p><a href="https://cran.r-project.org/web/packages/parsnip/vignettes/parsnip.html" class="uri">https://cran.r-project.org/web/packages/parsnip/vignettes/parsnip.html</a></p></li>
</ul>
<p>สมมุติว่าผู้วิเคราะห์ต้องการพัฒนาโมเดลการเรียนรู้ของเครื่องด้วยอัลกอริทึม linear regression โดยมีตัวแปรตามคือ <code>hwy</code> และตัวแปรอิสระเพียง 1 ตัวได้แก่ <code>cty</code> ตัวอย่างคำสั่งต่อไปนี้แสดงการกำหนดโมเดลการเรียนรู้ด้วย parsnip ดังกล่าว</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>lm_model <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">%&gt;%</span>        <span class="co"># model type</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">set_engine</span>(<span class="st">"lm"</span>) <span class="sc">%&gt;%</span>  <span class="co"># model engine</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>              <span class="fu">set_mode</span>(<span class="st">"regression"</span>) <span class="co"># model mode</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="การประมวลผล" class="level4">
<h4 class="anchored" data-anchor-id="การประมวลผล">(2) การประมวลผล</h4>
<p>เมื่อกำหนดโมเดลการเรียนรู้แล้วขั้นตอนถัดไปคือการนำ model specification ดังกล่าว ไปดำเนินการประมวลผล โดยส่งผ่านไปยังฟังก์ชัน <code>fit()</code> ซึ่งมีอาร์กิวเมนท์สำคัญ 2 ตัวได้แก่ model formula และ training dataset ที่จะใช้สำหรับฝึกหัดโมเดล</p>
<p>การเขียน model formula จะเขียนอยู่ในรูปของ <code>y ~ x1+x2+x3+…</code> โดยที่ <code>y</code> คือตัวแปรตาม ส่วน <code>x1, x2, x3 ,…</code> คือตัวแปรอิสระภายในชุดข้อมูลฝึกหัด และสัญลักษณ์ <code>~</code> หมายความว่า “regress on” ในกรณีที่ต้องการใช้ตัวแปรที่เหลือในชุดข้อมูลทั้งหมดเป็นตัวแปรทำนาย สามารถเขียน model formula สั้น ๆ ได้ดังนี้ `y ~ .` ตัวอย่างต่อไปนี้แสดงการส่งผ่าน model specification <code>lm_model</code> ในข้างต้นไปประมวลผล</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fit_lm <span class="ot">&lt;-</span> lm_model <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">fit</span>(hwy <span class="sc">~</span> cty,  <span class="co"># model formula</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> train_str) <span class="co"># training dataset</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>fit_lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = hwy ~ cty, data = data)

Coefficients:
(Intercept)          cty  
      1.056        1.324  </code></pre>
</div>
</div>
</section>
<section id="การเรยกดคาประมาณพารามเตอรของ-ml-model" class="level4">
<h4 class="anchored" data-anchor-id="การเรยกดคาประมาณพารามเตอรของ-ml-model">(3) การเรียกดูค่าประมาณพารามิเตอร์ของ ML model</h4>
<p>อย่างไรก็ตาม tidymodels มีฟังก์ชัน <code>tidy()</code> ซึ่งช่วยสร้างตารางสรุปผลลัพธ์จากการประมาณค่าพารามิเตอร์หรือการเรียนรู้ของโมเดลทำนายที่ใช้ให้อยู่ในรูปแบบเดียวกัน ดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(fit_lm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  term        estimate std.error statistic  p.value
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)     1.06    0.537       1.97 5.10e- 2
2 cty             1.32    0.0307     43.1  3.64e-94</code></pre>
</div>
</div>
<p>ภายใต้ framework ของ tidymodels จะใช้ฟังก์ชันใน package parsnip เพื่อ fitting model ทำนายดังกล่าว package ดังกล่าว จุดเด่นของ parsnip คือถูกออกแบบมาเพื่อเป็น interface สำหรับ fit supervised learning model ที่มีรูปแบบการใช้คำสั่งเป็นไวยกรณ์แบบเดียว</p>
</section>
<section id="prediction" class="level4">
<h4 class="anchored" data-anchor-id="prediction">(4) Prediction</h4>
<p>ผู้วิเคราะห์สามารถนำโมเดลที่ผ่านการ train เรียบร้อยแล้วไปใช้หาค่าทำนาย โดยส่งผ่านโมเดลที่ train แล้ว (ในที่นี้คือ <code>fit_lm</code>) ไปยังฟังก์ชัน <code>predict()</code> ที่มีอาร์กิวเมนท์สำคัญคือ <code>new_data</code> ตัวอย่างด้านล่างแสดงนำ <code>fit_lm</code> ไปทำนายตัวแปร <code>hwy</code> ในชุดข้อมูลทดสอบ ผลลัพธ์ที่ได้จากการทำนายจะเป็นตารางแบบ tibble ที่แต่ละ row คือค่าทำนายของหน่วยข้อมูลใน row เดียวกันกับใน <code>test_str</code> ดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>hwy_pred <span class="ot">&lt;-</span> fit_lm <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">predict</span>(<span class="at">new_data =</span> test_str)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>hwy_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 1
   .pred
   &lt;dbl&gt;
 1  28.9
 2  27.5
 3  20.9
 4  23.6
 5  19.6
 6  19.6
 7  24.9
 8  23.6
 9  20.9
10  20.9
# … with 50 more rows</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>เมื่อได้ค่าทำนายในชุดข้อมูลทดสอบมาแล้ว ขั้นตอนถัดไปคือการประเมินประสิทธิภาพของโมเดลทำนาย โดยทั่วไปผู้วิเคราะห์มักจะรวมค่าทำนายที่ได้ (ในที่นี้คือ <code>hwy_pred</code>) ไปไว้อยู่ภายในชุดข้อมูลทดสอบ การดำเนินการนี้สามารถทำได้หลายวิธีการขึ้นอยู่กับว่าถนัดจะดำเนินการแบบนี้ ในตัวอย่างนี้จะใช้ฟังก์ชัน <code>bind_cols()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test_str <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>                  dplyr<span class="sc">::</span><span class="fu">select</span>(hwy, cty) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">bind_cols</span>(hwy_pred)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>test_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 60 × 3
     hwy   cty .pred
   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
 1    29    21  28.9
 2    28    20  27.5
 3    24    15  20.9
 4    25    17  23.6
 5    20    14  19.6
 6    17    14  19.6
 7    29    18  24.9
 8    24    17  23.6
 9    22    15  20.9
10    21    15  20.9
# … with 50 more rows</code></pre>
</div>
</div>
</section>
<section id="evaluating-models-using-yardstick" class="level4">
<h4 class="anchored" data-anchor-id="evaluating-models-using-yardstick">(5) Evaluating models using yardstick</h4>
<p>การคำนวณค่าประสิทธิภาพของโมเดลทำนายแบบ regression ภายใต้ tidymodels framework สามารถทำได้ง่าย ๆ โดยใช้ฟังก์ชันจาก package yardstick ได้แก่ <code>rmse()</code> และ <code>rsq()</code> ตัวอย่างต่อไปนี้แสดงการเขียนคำสั่งเพื่อคำนวณ metric ทั้งสอง</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rmse</span>(<span class="at">truth =</span> hwy, <span class="at">estimate =</span> .pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rmse    standard        1.63</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rsq</span>(<span class="at">truth =</span> hwy, <span class="at">estimate =</span> .pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 rsq     standard       0.911</code></pre>
</div>
</div>
<p>ผลลัพธ์ข้างต้นเมื่อพิจารณาค่า RMSE พบว่าโมเดลทำนายที่พัฒนาขึ้นมีความคลาดเคลื่อนในการทำนายค่าของตัวแปร <code>hwy</code> โดยเฉลี่ย 1.64 หน่วย และเมื่อพิจารณาจากค่า R square พบว่ามีค่าเท่ากับ .913 แสดงว่าค่าจริงของ <code>hwy</code> กับค่าทำนายมีความผันแปรร่วมกันคิดเป็นร้อยละ 91.3 ซึ่งอยู่ในระดับที่สูงมาก ผลการวิเคราะห์นี้จึงบ่งชี้ว่าโมเดลทำนายที่พัฒนาขึ้นสามารถใช้ทำนายคะแนน <code>hwy</code> ได้ดี</p>
<p>นอกจาก metric ที่เป็นค่าสถิติแล้วยังมี metric ที่เป็น visualization ด้วย เช่นในกรณีของ regression model สามารถใช้ R squared plots เพื่อประเมินความสอดคล้องกันระหว่างค่าจริงของตัวแปรตามกับค่าทำนายได้ การสร้าง R squared plot ใน R สามารถทำได้หลายวิธี ทั้งการใช้ฟังก์ชัน <code>plot()</code> ของ package graphic เหมือนกับตัวอย่างในบทที่ 2 นอกจากนี้ยังสามารถใช้ package ggplot2 เพื่อสร้างแผนภาพดังกล่าวได้เหมือนกัน</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create R squared plot using graphic package</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> test_results<span class="sc">$</span>hwy, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">y =</span> test_results<span class="sc">$</span>.pred,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"predicted value"</span>,</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"actual value"</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">1</span>,<span class="at">b=</span><span class="dv">1</span>, <span class="at">lty=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">"steelblue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="336"></p>
</div>
</div>
<p>ในกรณีที่ต้องการใช้ ggplot2 สามารถเขียนคำสั่งได้ดังนี้</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create R squared plot using ggplot2 package</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>()<span class="sc">+</span>  <span class="co"># create 2D plane</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> hwy, <span class="co"># create scatter plot</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">y =</span> .pred))<span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept=</span><span class="dv">1</span>, <span class="at">slope=</span><span class="dv">1</span>, <span class="at">linetype=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">"steelblue"</span>)<span class="sc">+</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_obs_pred</span>()<span class="sc">+</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text=</span><span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">R squared plot via ggplot2</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>ผลการวิเคราะห์จาก R square plot ข้างต้นแสดงให้เห็นว่าโมเดลสามารถทำนายค่าของตัวแปร <code>hwy</code> ได้ค่อนข้างดี อย่างไรก็ตามหากพิจารณาเปรียบเทียบความสัมพันธ์ระหว่างค่าจริงกับค่าทำนายจะพบว่าโมเดลนี้มีแนวโน้มให้ค่าทำนายที่ต่ำกว่าความเป็นจริง (underestimate)</p>
<p><strong>คำถาม เราได้เรียน</strong> linear regression มาพอสมควรแล้ว โดยหากจำได้จะทราบว่า linear regression เป็นโมเดลทางสถิติที่มีข้อตกลงเบื้องต้นที่ค่อนข้างเข้มงวด ได้แก่ independence, homoscedasticity, normality, no multicollinearity, no outlier, … คำถามคือในการพัฒนา ML model ดังกล่าวจำเป็นมั้ยที่จะต้องตรวจสอบข้อตกลงเบื้องต้นดังกล่าว เพราะอะไร?</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="fitting-classification-models-logistic-regression-using-parsnip" class="level3">
<h3 class="anchored" data-anchor-id="fitting-classification-models-logistic-regression-using-parsnip">Fitting Classification models (logistic regression) using parsnip</h3>
<p>หัวข้อนี้จะใช้ tidymodels framework เพื่อ fit logistic regression model สำหรับทำนายชุดข้อมูล ชุดข้อมูลที่ใช้ชื่อ <code>classification.csv</code> <a href="https://github.com/ssiwacho/2758688_ML/blob/79a225047656cb9a22a4e1b78835b8bdd91a1d26/week%201/classification.csv">สามารถดาวน์โหลดได้ที่นี่</a> ชุดข้อมูลนี้มีตัวแปรตามที่สนใจคือ <code>Class</code> ซึ่งเป็นสถานะการ dropout ออกจากระบบ LMS ของนักเรียน ส่วนที่เหลือเป็นตัวแปรที่คาดว่าจะนำมาเป็นตัวแปรอิสระ</p>
<section id="การนำเขาและสำรวจขอมล" class="level4">
<h4 class="anchored" data-anchor-id="การนำเขาและสำรวจขอมล">(1) การนำเข้าและสำรวจข้อมูล</h4>
<p>ในกรณีนี้นำเข้าข้อมูล <code>classfication.csv</code> ด้วยฟังก์ชัน <code>read.csv()</code> จากนั้นสำรวจข้อมูลเบื้องต้นด้วยฟังก์ชัน <code>glimpse()</code> ได้ผลเป็นดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># import</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/ssiwacho/2758688_ML/main/week%201/classification.csv"</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="co"># explore dataset</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 208
Columns: 62
$ X     &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…
$ V1    &lt;dbl&gt; 0.0200, 0.0453, 0.0262, 0.0100, 0.0762, 0.0286, 0.0317, 0.0519, …
$ V2    &lt;dbl&gt; 0.0371, 0.0523, 0.0582, 0.0171, 0.0666, 0.0453, 0.0956, 0.0548, …
$ V3    &lt;dbl&gt; 0.0428, 0.0843, 0.1099, 0.0623, 0.0481, 0.0277, 0.1321, 0.0842, …
$ V4    &lt;dbl&gt; 0.0207, 0.0689, 0.1083, 0.0205, 0.0394, 0.0174, 0.1408, 0.0319, …
$ V5    &lt;dbl&gt; 0.0954, 0.1183, 0.0974, 0.0205, 0.0590, 0.0384, 0.1674, 0.1158, …
$ V6    &lt;dbl&gt; 0.0986, 0.2583, 0.2280, 0.0368, 0.0649, 0.0990, 0.1710, 0.0922, …
$ V7    &lt;dbl&gt; 0.1539, 0.2156, 0.2431, 0.1098, 0.1209, 0.1201, 0.0731, 0.1027, …
$ V8    &lt;dbl&gt; 0.1601, 0.3481, 0.3771, 0.1276, 0.2467, 0.1833, 0.1401, 0.0613, …
$ V9    &lt;dbl&gt; 0.3109, 0.3337, 0.5598, 0.0598, 0.3564, 0.2105, 0.2083, 0.1465, …
$ V10   &lt;dbl&gt; 0.2111, 0.2872, 0.6194, 0.1264, 0.4459, 0.3039, 0.3513, 0.2838, …
$ V11   &lt;dbl&gt; 0.1609, 0.4918, 0.6333, 0.0881, 0.4152, 0.2988, 0.1786, 0.2802, …
$ V12   &lt;dbl&gt; 0.1582, 0.6552, 0.7060, 0.1992, 0.3952, 0.4250, 0.0658, 0.3086, …
$ V13   &lt;dbl&gt; 0.2238, 0.6919, 0.5544, 0.0184, 0.4256, 0.6343, 0.0513, 0.2657, …
$ V14   &lt;dbl&gt; 0.0645, 0.7797, 0.5320, 0.2261, 0.4135, 0.8198, 0.3752, 0.3801, …
$ V15   &lt;dbl&gt; 0.0660, 0.7464, 0.6479, 0.1729, 0.4528, 1.0000, 0.5419, 0.5626, …
$ V16   &lt;dbl&gt; 0.2273, 0.9444, 0.6931, 0.2131, 0.5326, 0.9988, 0.5440, 0.4376, …
$ V17   &lt;dbl&gt; 0.3100, 1.0000, 0.6759, 0.0693, 0.7306, 0.9508, 0.5150, 0.2617, …
$ V18   &lt;dbl&gt; 0.2999, 0.8874, 0.7551, 0.2281, 0.6193, 0.9025, 0.4262, 0.1199, …
$ V19   &lt;dbl&gt; 0.5078, 0.8024, 0.8929, 0.4060, 0.2032, 0.7234, 0.2024, 0.6676, …
$ V20   &lt;dbl&gt; 0.4797, 0.7818, 0.8619, 0.3973, 0.4636, 0.5122, 0.4233, 0.9402, …
$ V21   &lt;dbl&gt; 0.5783, 0.5212, 0.7974, 0.2741, 0.4148, 0.2074, 0.7723, 0.7832, …
$ V22   &lt;dbl&gt; 0.5071, 0.4052, 0.6737, 0.3690, 0.4292, 0.3985, 0.9735, 0.5352, …
$ V23   &lt;dbl&gt; 0.4328, 0.3957, 0.4293, 0.5556, 0.5730, 0.5890, 0.9390, 0.6809, …
$ V24   &lt;dbl&gt; 0.5550, 0.3914, 0.3648, 0.4846, 0.5399, 0.2872, 0.5559, 0.9174, …
$ V25   &lt;dbl&gt; 0.6711, 0.3250, 0.5331, 0.3140, 0.3161, 0.2043, 0.5268, 0.7613, …
$ V26   &lt;dbl&gt; 0.6415, 0.3200, 0.2413, 0.5334, 0.2285, 0.5782, 0.6826, 0.8220, …
$ V27   &lt;dbl&gt; 0.7104, 0.3271, 0.5070, 0.5256, 0.6995, 0.5389, 0.5713, 0.8872, …
$ V28   &lt;dbl&gt; 0.8080, 0.2767, 0.8533, 0.2520, 1.0000, 0.3750, 0.5429, 0.6091, …
$ V29   &lt;dbl&gt; 0.6791, 0.4423, 0.6036, 0.2090, 0.7262, 0.3411, 0.2177, 0.2967, …
$ V30   &lt;dbl&gt; 0.3857, 0.2028, 0.8514, 0.3559, 0.4724, 0.5067, 0.2149, 0.1103, …
$ V31   &lt;dbl&gt; 0.1307, 0.3788, 0.8512, 0.6260, 0.5103, 0.5580, 0.5811, 0.1318, …
$ V32   &lt;dbl&gt; 0.2604, 0.2947, 0.5045, 0.7340, 0.5459, 0.4778, 0.6323, 0.0624, …
$ V33   &lt;dbl&gt; 0.5121, 0.1984, 0.1862, 0.6120, 0.2881, 0.3299, 0.2965, 0.0990, …
$ V34   &lt;dbl&gt; 0.7547, 0.2341, 0.2709, 0.3497, 0.0981, 0.2198, 0.1873, 0.4006, …
$ V35   &lt;dbl&gt; 0.8537, 0.1306, 0.4232, 0.3953, 0.1951, 0.1407, 0.2969, 0.3666, …
$ V36   &lt;dbl&gt; 0.8507, 0.4182, 0.3043, 0.3012, 0.4181, 0.2856, 0.5163, 0.1050, …
$ V37   &lt;dbl&gt; 0.6692, 0.3835, 0.6116, 0.5408, 0.4604, 0.3807, 0.6153, 0.1915, …
$ V38   &lt;dbl&gt; 0.6097, 0.1057, 0.6756, 0.8814, 0.3217, 0.4158, 0.4283, 0.3930, …
$ V39   &lt;dbl&gt; 0.4943, 0.1840, 0.5375, 0.9857, 0.2828, 0.4054, 0.5479, 0.4288, …
$ V40   &lt;dbl&gt; 0.2744, 0.1970, 0.4719, 0.9167, 0.2430, 0.3296, 0.6133, 0.2546, …
$ V41   &lt;dbl&gt; 0.0510, 0.1674, 0.4647, 0.6121, 0.1979, 0.2707, 0.5017, 0.1151, …
$ V42   &lt;dbl&gt; 0.2834, 0.0583, 0.2587, 0.5006, 0.2444, 0.2650, 0.2377, 0.2196, …
$ V43   &lt;dbl&gt; 0.2825, 0.1401, 0.2129, 0.3210, 0.1847, 0.0723, 0.1957, 0.1879, …
$ V44   &lt;dbl&gt; 0.4256, 0.1628, 0.2222, 0.3202, 0.0841, 0.1238, 0.1749, 0.1437, …
$ V45   &lt;dbl&gt; 0.2641, 0.0621, 0.2111, 0.4295, 0.0692, 0.1192, 0.1304, 0.2146, …
$ V46   &lt;dbl&gt; 0.1386, 0.0203, 0.0176, 0.3654, 0.0528, 0.1089, 0.0597, 0.2360, …
$ V47   &lt;dbl&gt; 0.1051, 0.0530, 0.1348, 0.2655, 0.0357, 0.0623, 0.1124, 0.1125, …
$ V48   &lt;dbl&gt; 0.1343, 0.0742, 0.0744, 0.1576, 0.0085, 0.0494, 0.1047, 0.0254, …
$ V49   &lt;dbl&gt; 0.0383, 0.0409, 0.0130, 0.0681, 0.0230, 0.0264, 0.0507, 0.0285, …
$ V50   &lt;dbl&gt; 0.0324, 0.0061, 0.0106, 0.0294, 0.0046, 0.0081, 0.0159, 0.0178, …
$ V51   &lt;dbl&gt; 0.0232, 0.0125, 0.0033, 0.0241, 0.0156, 0.0104, 0.0195, 0.0052, …
$ V52   &lt;dbl&gt; 0.0027, 0.0084, 0.0232, 0.0121, 0.0031, 0.0045, 0.0201, 0.0081, …
$ V53   &lt;dbl&gt; 0.0065, 0.0089, 0.0166, 0.0036, 0.0054, 0.0014, 0.0248, 0.0120, …
$ V54   &lt;dbl&gt; 0.0159, 0.0048, 0.0095, 0.0150, 0.0105, 0.0038, 0.0131, 0.0045, …
$ V55   &lt;dbl&gt; 0.0072, 0.0094, 0.0180, 0.0085, 0.0110, 0.0013, 0.0070, 0.0121, …
$ V56   &lt;dbl&gt; 0.0167, 0.0191, 0.0244, 0.0073, 0.0015, 0.0089, 0.0138, 0.0097, …
$ V57   &lt;dbl&gt; 0.0180, 0.0140, 0.0316, 0.0050, 0.0072, 0.0057, 0.0092, 0.0085, …
$ V58   &lt;dbl&gt; 0.0084, 0.0049, 0.0164, 0.0044, 0.0048, 0.0027, 0.0143, 0.0047, …
$ V59   &lt;dbl&gt; 0.0090, 0.0052, 0.0095, 0.0040, 0.0107, 0.0051, 0.0036, 0.0048, …
$ V60   &lt;dbl&gt; 0.0032, 0.0044, 0.0078, 0.0117, 0.0094, 0.0062, 0.0103, 0.0053, …
$ Class &lt;chr&gt; "drop", "drop", "drop", "drop", "drop", "drop", "drop", "drop", …</code></pre>
</div>
</div>
<p>จากผลการสำรวจข้างต้น จงตอบคำถามต่อไปนี้ ชุดข้อมูล <code>classification.csv</code> …</p>
<ul>
<li><p>มีหน่วยข้อมูลจำนวนกี่หน่วย?</p></li>
<li><p>มีตัวแปรจำนวนกี่ตัวแปร</p></li>
<li><p>การแจกแจงของตัวแปรตามเป็นอย่างไร?</p></li>
<li><p>type ของตัวแปรที่จัดเก็บใน <code>dat</code> ข้างต้นมีแบบไหนบ้าง เหมาะสมแล้วหรือไม่ที่จะนำไปวิเคราะห์ logistic regression ต่อไป</p></li>
</ul>
</section>
<section id="การแบงชดขอมล" class="level4">
<h4 class="anchored" data-anchor-id="การแบงชดขอมล">(2) การแบ่งชุดข้อมูล</h4>
<p>ในทำนองเดียวกับการพัฒนา regression models ผู้วิเคราะห์ต้องแบ่งชุดข้อมูล <code>dat</code> ออกเป็นสองส่วนได้แก่ ส่วน training dataset เพื่อพัฒนาโมเดล และ test dataset เพื่อตรวจสอบประสิทธิภาพของโมเดล</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>dat<span class="sc">$</span>Class <span class="ot">&lt;-</span> <span class="fu">factor</span>(dat<span class="sc">$</span>Class, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"drop"</span>, <span class="st">"stay"</span>))</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>class_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="at">data=</span> dat,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">prop=</span><span class="fl">0.8</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">strata =</span> Class)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> class_split <span class="sc">%&gt;%</span> <span class="fu">training</span>()</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span>  class_split <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="การประมวลผลและสำรวจโมเดล" class="level4">
<h4 class="anchored" data-anchor-id="การประมวลผลและสำรวจโมเดล">(3) การประมวลผลและสำรวจโมเดล</h4>
<p>เมื่อแบ่งชุดข้อมูลแล้วขั้นตอนต่อมาคือการพัฒนาโมเดลทำนาย ในที่นี้จะใช้ logistic regression ก่อน</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>logistic_reg <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>(<span class="at">engine =</span><span class="st">"glm"</span>,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>                             <span class="at">mode =</span> <span class="st">"classification"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>fit_logistic <span class="ot">&lt;-</span> logistic_reg <span class="sc">%&gt;%</span> </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">fit</span>(Class <span class="sc">~</span> . , <span class="at">data=</span>train[,<span class="sc">-</span><span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: algorithm did not converge</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>เราสามารถวิเคราะห์สัมประสิทธิถดถอยของตัวแปรอิสระในโมเดลได้ โดยใช้ data visualization มาช่วย เช่น</p>
<div class="cell" data-fit.height="4">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fit_logistic<span class="sc">$</span>fit <span class="sc">%&gt;%</span> </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>          <span class="fu">coef</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>            <span class="fu">data.frame</span>(<span class="at">coef=</span> .)<span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">""</span> ,<span class="at">y=</span>coef))<span class="sc">+</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.7</span>, <span class="at">fill =</span> <span class="st">"grey"</span>)<span class="sc">+</span></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>                <span class="fu">geom_jitter</span>(<span class="at">width=</span><span class="fl">0.1</span>)<span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="288"></p>
<p></p><figcaption class="figure-caption">boxplot ของสัมประสิทธิ์การถดถอยใน logistic regression</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>เราจะเห็นว่าโมเดลทำนายที่พัฒนาขึ้นข้างต้น มีตัวแปรอิสระที่น่าจะใช้ทำนายตัวแปรตาม <code>Class</code> ได้ เยอะมาก ปัจจัยนี้อาจเป็นสาเหตุหนึ่งที่ทำให้การประมาณค่าพารามิเตอร์ของโมเดลเกิดปัญหาไม่ลู่เข้า การแก้ปัญหาดังกล่าวอาจทำการคัดเลือกตัวแปรอิสระที่ไม่จำเป็นออกไปจากโมเดล ซึ่งจะเห็นว่าเป็นงานที่ค่อนข้างเหนื่อยเพราะมีตัวแปรอิสระเยอะพอสมควรในชุดข้อมูลนี้ อีกวิธีการหนึ่งคือใช้เทคนิค regularization ซึ่งสามารถทำได้โดยเปลี่ยน <code>engine = "glmnet"</code> เนื้อหาส่วนนี้จะกล่าวถึงอีกครั้งในบทต่อไป</p>
<div style="page-break-after: always;"></div>
</section>
<section id="การคำนวณคาทำนายจากโมเดล" class="level4">
<h4 class="anchored" data-anchor-id="การคำนวณคาทำนายจากโมเดล">(4) การคำนวณค่าทำนายจากโมเดล</h4>
<p>ในกรณีนี้สมมุติว่าโมเดลทำนาย logistic regression ไม่ได้มีปัญหาอะไรและจะนำไปสู่ขั้นตอนการตรวจสอบคุณภาพในชุดข้อมูลทดสอบ ในทำนองเดียวกับ regression models การตรวจสอบประสิทธิภาพในการทำนายของโมเดล ผู้วิเคราะห์ต้องมี (1) ค่าสังเกตจริงของตัวแปรตามในชุดข้อมูลทดสอบ และ (2) ค่าทำนายที่ได้จากโมเดลทำนายในชุดข้อมูลทดสอบ</p>
<p>การคำนวณค่าทำนายจากโมเดลสามารถทำได้ด้วยฟังก์ชัน <code>predict()</code> เช่นเดียวกับ regression models อย่างไรก็ตามใน classfication models สามารถคำนวณค่าทำนายได้ 2 ประเภทหลัก ได้แก่ ค่าความน่าจะเป็น (probability) ของการเกิดเหตุการณ์/ผลลัพธ์ที่สนใจในตัวแปรตามของหน่วยข้อมูล และค่าทำนายประเภท/ผลลัพธ์ในตัวแปรตามของหน่วยข้อมูล โดยในกรณีที่ต้องการค่าทำนายเป็นค่าความน่าจะเป็นให้กำหนดอาร์กิวเมนท์ <code>type = "prob"</code> ส่วนในกรณีที่ต้องการค่าทำนายเป็นประเภทในตัวแปรตามให้กำหนดอาร์กิวเมนท์ <code>type = "class"</code></p>
<section id="กรณกำหนด-type-prob" class="level5">
<h5 class="anchored" data-anchor-id="กรณกำหนด-type-prob">กรณีกำหนด <code>type = "prob"</code></h5>
<p>การกำหนดลักษณะนี้จะได้ค่าความน่าจะเป็นซึ่งสามารถนำไปคำนวณเป็นค่าทำนายประเภทของหน่วยข้อมูลได้โดยการกำหนดคะแนนจุดตัดหรือค่า threshold ซึ่งโดยปกติมักกำหนดให้ค่า threshold = 0.5 ตัวอย่างคำสั่งต่อไปนี้แสดงการคำนวณค่าความน่าจะเป็นดังกล่าว รวมทั้งการแปลงค่าความน่าจะเป็นที่ได้โดยการกำหนด threshold เป็น 0.2, 0.5 และ 0.8 ตามลำดับ ทั้งนี้หากโมเดลที่มีประสิทธิภาพไม่คงที่เมื่อเปลี่ยนค่า threshold จะบ่งชี้ว่าโมเดลดังกล่าวมีประสิทธิภาพการทำนายที่ไม่ดีนัก กล่าวคือ เป็นโมเดลที่ไม่ชัดเจนในการทำนาย ในทางกลับกันโมเดลที่มีค่าทำนายประเภทของหน่วยข้อมูลที่คงเส้นคงวา เมื่อกำหนดค่า threshold แตกต่างกัน บ่งชี้ว่าโมเดลดังกล่าวเป็นโมเดลที่มีประสิทธิภาพในการทำนายสูง</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># predicted value</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_logistic, </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">new_data =</span> test[,<span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type=</span><span class="st">"prob"</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>pred_class_thres0<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob[,<span class="dv">1</span>] <span class="sc">&gt;=</span><span class="fl">0.2</span>,<span class="st">"drop"</span>, <span class="st">"stay"</span>))</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>pred_class_thres0<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob[,<span class="dv">1</span>] <span class="sc">&gt;=</span><span class="fl">0.5</span>,<span class="st">"drop"</span>, <span class="st">"stay"</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>pred_class_thres0<span class="fl">.8</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(pred_prob[,<span class="dv">1</span>] <span class="sc">&gt;=</span><span class="fl">0.8</span>,<span class="st">"drop"</span>, <span class="st">"stay"</span>))</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred_class_thres0<span class="fl">.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pred_class_thres0.2
drop stay 
  18   25 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred_class_thres0<span class="fl">.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pred_class_thres0.5
drop stay 
  18   25 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred_class_thres0<span class="fl">.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>pred_class_thres0.8
drop stay 
  18   25 </code></pre>
</div>
</div>
<p>ผลการวิเคราะห์ข้างต้นแสดงให้เห็นว่าค่าทำนายประเภทของหน่วยข้อมูลไม่มีการเปลี่ยนแปลงเมื่อกำหนด threshold เท่ากับ 0.2, 0.5 และ 0.8 ซึ่งบ่งชี้ว่าโมเดลทำนายมีแนวโน้มที่จะให้ค่าทำนายที่คงเส้นคงวา อย่างไรก็ตามการวิเคราะห์เพียง 3 จุดของ threshold เป็นการวิเคราะห์ที่ค่อนข้างหยาบ ส่วนท้ายของหัวข้อนี้จะกล่าวถึงการใช้ ROC curve เพื่อวิเคราะห์ประสิทธิภาพของโมเดลบนแต่ละค่าของ threshold ดังกล่าว</p>
</section>
<section id="กรณกำหนด-type-class" class="level5">
<h5 class="anchored" data-anchor-id="กรณกำหนด-type-class">กรณีกำหนด <code>type = "class"</code></h5>
<p>เมื่อกำหนดให้ <code>type = "class"</code> ฟังก์ชัน <code>predict()</code> จะทำนายประเภทของหน่วยข้อมูลโดยใช้ค่า threshold = 0.5 ดังนั้นหากผู้วิเคราะห์ต้องการใช้ threshold ค่านี้อยู่แล้ว การกำหนดอาร์กิวเมนท์ลักษณะนี้จะช่วยลดขั้นตอนการทำงานลงได้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>pred_class2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_logistic, </span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">new_data =</span> test[,<span class="sc">-</span><span class="dv">1</span>],</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">type=</span><span class="st">"class"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(pred_class2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 1
  .pred_class
  &lt;fct&gt;      
1 stay       
2 drop       
3 stay       
4 drop       
5 drop       
6 stay       </code></pre>
</div>
</div>
<p>จะเห็นว่าผลการทำนายประเภทที่ได้จากฟังก์ชัน <code>predict()</code> อยู่ในรูปชุดข้อมูลแบบ tibble โดยคอลัมน์ที่เก็บค่าทำนายจะใช้ชื่อ <code>.pred_class</code> และมีสถานะเป็นตัวแปรแบบ factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(pred_class2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>.pred_class
drop stay 
  18   25 </code></pre>
</div>
</div>
</section>
</section>
<section id="การประเมนประสทธภาพการทำนายของโมเดล" class="level4">
<h4 class="anchored" data-anchor-id="การประเมนประสทธภาพการทำนายของโมเดล">(5) การประเมินประสิทธิภาพการทำนายของโมเดล</h4>
<p>package yardstick มีฟังก์ชัน <code>conf_mat()</code> ที่ทำหน้าที่เหมือนกับฟังก์ชัน <code>confusionMatrix()</code> โดยอาร์กิวเมนท์สำคัญของฟังก์ชันนี้ได้แก่ <code>data</code> ที่เป็น data.frame หรือ tibble ที่ต้องมีคอลัมน์ของค่าจริงของตัวแปรตาม และค่าทำนายของตัวแปรตามให้เรียบร้อย <code>truth</code> คืออาร์กิวเมนท์สำหรับระบุว่าคอลัมน์ไหนคือค่าจริงของตัวแปรตาม และ <code>estimate</code> คือคอลัมน์ที่ใช้ระบุว่าคอลัมน์ไหนคือค่าทำนายของตัวแปรตาม ทั้งนี้ตัวแปรตามและค่าทำนายจะต้องเก็บอยู่ในรูปแบบ factor</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># combine .pred_class column to test dataset</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(Class) <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>          <span class="fu">bind_cols</span>(pred_class2, pred_prob)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(<span class="at">data =</span> test_results, <span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Truth
Prediction drop stay
      drop   15    3
      stay    5   20</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># accuracy</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">accuracy</span>(<span class="at">data =</span> test_results, <span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.814</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># sensitivity</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sens</span>(<span class="at">data =</span> test_results, <span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 sens    binary          0.75</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specificity</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">spec</span>(<span class="at">data =</span> test_results, <span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 spec    binary         0.870</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># define metric set function</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>custom_metric<span class="ot">&lt;-</span><span class="fu">metric_set</span>(accuracy, sens, spec)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">custom_metric</span>(<span class="at">data =</span> test_results, <span class="at">truth =</span> Class, <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.814
2 sens     binary         0.75 
3 spec     binary         0.870</code></pre>
</div>
</div>
<p>นอกจากนี้ยังสามารถใช้ฟังก์ชัน <code>summary()</code> กับผลลัพธ์ที่ได้จาก <code>conf_mat()</code> เพื่อเรียกดูค่าสถิติของ confusion matrix คล้ายกับฟังก์ชัน <code>confusionMatrix()</code> ของ package caret ที่ได้กล่าวถึงในหัวข้อ 2.4</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(<span class="at">data =</span> test_results, </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth =</span> Class, </span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">estimate =</span> .pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 3
   .metric              .estimator .estimate
   &lt;chr&gt;                &lt;chr&gt;          &lt;dbl&gt;
 1 accuracy             binary         0.814
 2 kap                  binary         0.624
 3 sens                 binary         0.75 
 4 spec                 binary         0.870
 5 ppv                  binary         0.833
 6 npv                  binary         0.8  
 7 mcc                  binary         0.626
 8 j_index              binary         0.620
 9 bal_accuracy         binary         0.810
10 detection_prevalence binary         0.419
11 precision            binary         0.833
12 recall               binary         0.75 
13 f_meas               binary         0.789</code></pre>
</div>
</div>
<div style="page-break-after: always;"></div>
<p>รายละเอียดของ metric ต่าง ๆ สามารถศึกษาเพิ่มเติมได้จากเอกสารที่เกี่ยวกับ package yardstick</p>
<ul>
<li><p>https://cran.r-project.org/web/packages/yardstick/yardstick.pdf</p></li>
<li><p>https://yardstick.tidymodels.org/</p></li>
<li><p>https://cran.r-project.org/web/packages/yardstick/vignettes/metric-types.html</p></li>
</ul>
</section>
<section id="การนำเสนอประสทธภาพการทำนายของโมเดลดวยทศนภาพขอมล" class="level4">
<h4 class="anchored" data-anchor-id="การนำเสนอประสทธภาพการทำนายของโมเดลดวยทศนภาพขอมล">(6) การนำเสนอประสิทธิภาพการทำนายของโมเดลด้วยทัศนภาพข้อมูล</h4>
<p>การวิเคราะห์ประสิทธิภาพการทำนายของ classification models สามารถทำได้ด้วยทัศนภาพข้อมูลหลายตัว ซึ่งบางตัวช่วยให้สารสนเทศเชิงลึกประกอบการปรับแต่งโมเดลทำนายแก่ผู้วิเคราะห์ได้เป็นอย่างดี เนื้อหาประกอบด้วย การใช้ heatmap แผนภาพ mosaic และ ROC Curve รายละเอียดมีดังนี้</p>
<section id="แผนทความรอน-heatmap-ของ-confusion-matrix" class="level5">
<h5 class="anchored" data-anchor-id="แผนทความรอน-heatmap-ของ-confusion-matrix">แผนที่ความร้อน (heatmap) ของ confusion matrix</h5>
<p>ทัศนภาพนี้เหมาะสำหรับ classification model ที่มีการจำแนกประเภทจำนวนหลาย ๆ ประเภท การสร้างแผนที่ความร้อนดังกล่าวสามารถสร้างได้โดยการส่งค่า confusion matrix ที่สร้างจากฟังก์ชัน <code>conf_mat()</code> ไปยังฟังก์ชัน <code>autoplot()</code> และในฟังก์ชัน <code>autoplot()</code> ให้กำหนดอาร์กิวเมนท์ <code>type = "heatmap"</code> ดังตัวอย่างต่อไปนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(<span class="at">data =</span> test_results, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth =</span> Class, </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">estimate =</span> .pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(<span class="at">type =</span> <span class="st">"heatmap"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="288"></p>
<p></p><figcaption class="figure-caption">plotting the confusion matrix using Heatmap</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>จากรูป 27 จะเห็นว่าแผนที่ความร้อนที่สร้างขึ้นจะใช้ความเข้มของสีแสดงความถี่ในแต่ละประเภทของการทำนาย โดยในรูปตัวอย่างพบว่าโมเดลทำนายมีแนวโน้มที่จะทำนายได้อย่างถูกต้องเป็นส่วนใหญ่</p>
<div style="page-break-after: always;"></div>
</section>
<section id="แผนภาพโมเสก-mosaic-plot" class="level5">
<h5 class="anchored" data-anchor-id="แผนภาพโมเสก-mosaic-plot">แผนภาพโมเสก (mosaic plot)</h5>
<p>ทัศนภาพนี้จะแสดงผลลัพธ์ในมิติของ sensitivity หรือ specificity การสร้างแผนภาพโมเสกจาก confusion matrix สามารถใช้ฟังก์ชัน <code>autoplot()</code> เช่นเดียวกับการสร้างแผนที่ความร้อน แต่ให้กำหนดอาร์กิวเมนท์ <code>type = mosaic</code> ดังตัวอย่างต่อไปนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(<span class="at">data =</span> test_results, </span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth =</span> Class, </span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">estimate =</span> .pred_class) <span class="sc">%&gt;%</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>(<span class="at">type =</span> <span class="st">"mosaic"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="288"></p>
<p></p><figcaption class="figure-caption">plotting the confusion matrix using Masaic plot</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>จากรูป 28 เมื่อพิจารณาในคอลัมน์แรกจะพบว่าเป็นคอลัมน์ที่แสดง sensitivity ของโมเดล (เนื่องจากโมเดลทำนายมุ่งที่จะทำนายกลุ่ม dropout ดังนั้นกลุ่มนี้จึงเป็นพวก positive ของโมเดล) ส่วนคอลัมน์ที่สองแสดง specificity ของโมเดล ซึ่งมีค่าอยู่ในระดับสูงทั้งสอง metrics</p>
</section>
<section id="roc-curve" class="level5">
<h5 class="anchored" data-anchor-id="roc-curve">ROC curve</h5>
<p>ดังที่ได้กล่าวไว้ก่อนแล้วข้างต้นว่าคุณสมบัติที่ดีของโมเดลทำนายอย่างหนึ่งคือการที่สามารถให้ค่าทำนายประเภทของหน่วยข้อมูลที่คงเส้นคงวาบนแต่ละระดับของค่า threshold การตรวจสอบประสิทธิภาพด้านนี้อย่างละเอียดควรดำเนินการวิเคราะห์ประสิทธิภาพในการทำนายของโมเดลเมื่อกำหนดค่า threshold ตั้งแต่ 0.00 ถึง 1.00 การดำเนินการดังกล่าวด้วย R ในสมัยก่อนผู้วิเคราะห์จำเป็นจะต้องเขียนฟังก์ชันเพื่อทวนซ้ำการทำนายในแต่ละค่า threshold แต่ในปัจจุบันหากใช้ package yardstick ผู้วิเคราะห์สามารถใช้ฟังก์ชัน <code>roc_curve()</code> เพื่อช่วยทำการวิเคราะห์นี้ได้ อาร์กิวเมนท์ของฟังก์ชันนี้ประกอบด้วย ค่าจริงของตัวแปรตามในชุดข้อมูลทดสอบ และค่าประมาณความน่าจะเป็นของการเกิดผลลัพธ์ที่สนใจ (positive type) ในตัวแปรตาม</p>
<div style="page-break-after: always;"></div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> Class, .pred_drop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Returning more (or less) than 1 row per `summarise()` group was deprecated in
dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()`
  always returns an ungrouped data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the yardstick package.
  Please report the issue at &lt;]8;;https://github.com/tidymodels/yardstick/issueshttps://github.com/tidymodels/yardstick/issues]8;;&gt;.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 3
    .threshold specificity sensitivity
         &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
 1 -Inf              0            1   
 2    2.22e-16       0            1   
 3    8.95e- 9       0.783        0.75
 4    6.23e- 6       0.826        0.75
 5    9.00e- 1       0.870        0.75
 6    9.81e- 1       0.913        0.75
 7    1.00e+ 0       0.913        0.7 
 8    1.00e+ 0       0.913        0.65
 9    1   e+ 0       0.913        0.6 
10  Inf              1            0   </code></pre>
</div>
</div>
<p>ข้อดีของฟังก์ชัน <code>roc_curve()</code> คือฟังก์ชันจะกำหนด grid หรือช่วงของค่า threshold ที่เหมาะสมกับข้อมูลซึ่งช่วย output ที่ไม่จำเป็นลงได้ จากตารางข้างต้นจะเห็นว่าถ้าไม่นับกรณีที่กำหนด threshold อย่างสุดโต่งคือ 0 หรือ 1 ประสิทธิภาพของโมเดลทำนายที่พัฒนาขึ้นนี้มีค่า sensitivity และ specificity มากกว่า 0.75 เกือบทุกกรณี</p>
<p>อย่างไรก็ตามในกรณีทั่วไปผลลัพธ์จากตารางข้างต้นอาจมีจำนวนมากจนเป็นการยากที่จะดำเนินการวิเคราะห์ ผู้วิเคราะห์จึงมักนิยมแปลงผลการวิเคราะห์ในตารางดังกล่าวให้เป็นแผนภาพ ROC curve ที่เป็นการพล็อตคู่อันดับของ FPR = 1 - specificity กับ sensitivity ที่คำนวณได้จากแต่ละค่าของ threshold โดยให้ค่า sensitivity อยู่บนแกน Y และค่า FPR อยู่บนแกน X รูปต่อไปนี้แสดงตัวอย่างของ ROC curve</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1255912826.png" class="img-fluid figure-img" alt="ตัวอย่าง ROC Curve"></p>
<p></p><figcaption class="figure-caption">ตัวอย่าง ROC Curve</figcaption><p></p>
</figure>
</div>
<div style="page-break-after: always;"></div>
<p>โมเดลทำนายที่ดีควรมี ROC curve ที่ลู่เข้าไปใกล้คู่อันดับ (0.00,1.00) เนื่องจากคู่อันดับดังกล่าวเป็นจุดที่โมเดลมี FPR = 0.00 และมี sensitivity = 1.00 หรือเป็นจุดที่ดีที่สุดที่เป็นไปได้ (optimal point) ส่วนโมเดลที่มีประสิทธิภาพต่ำจะเป็นโมเดลที่มี Roc curve ลู่เข้าหาหรือมีลักษณะใกล้เคียงกับเส้นอ้างอิง <span class="math inline">\(y=x\)</span> ซึ่งแสดงว่าโมเดลทำนายมีประสิทธิภาพในการทำนายที่ใกล้เคียงกับการเดาสุ่มแบบโยนเหรียญหัวก้อย</p>
<p>จากรูป 30 จะเห็นว่าโมเดลตัวอย่างทางด้านซ้ายมีแนวโน้มที่จะมีประสิทธิภาพในการทำนายสูงกว่าโมเดลตัวอย่างทางด้านขวา ทั้งนี้เป็นเพราะ ROC curve ของโมเดลทางซ้ายมีแนวโน้มลู่เข้าไปหาคู่อันดับ (0.00,1.00) มากกว่าโมเดลทางขวามือ สำหรับการสร้าง ROC curve ด้วย R สามารถทำได้โดยส่งผ่านผลลัพธ์ที่ได้จากฟังก์ชัน <code>roc_curve()</code> ในข้างต้นไปในฟังก์ชัน <code>autoplot()</code> ดังตัวอย่างต่อไปนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> Class, .pred_drop) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="384"></p>
<p></p><figcaption class="figure-caption">ROC Curve</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>ผลการวิเคราะห์ ROC curve จากรูป 31 สามารถสรุปได้อย่างไร?</p>
</section>
<section id="area-under-curve-auc" class="level5">
<h5 class="anchored" data-anchor-id="area-under-curve-auc">Area Under Curve (AUC)</h5>
<p>พื้นที่ใต้โค้ง ROC (area under curve: AUC) ถูกใช้เป็น metric อีกตัวหนึ่งสำหรับประเมินประสิทธิภาพในการทำนายของโมเดล ที่คำนวณจากพื้นที่ใต้โค้งของกราฟ ROC โดยโมเดลทำนายที่มีค่า AUC สูงเข้าใกล้ 1.00 จะเป็นโมเดลที่มีแนวโน้มจะมีประสิทธิภาพในการทำนายสูง ส่วนโมเดลที่มีค่า AUC เข้าใกล้ 0.5 มีแนวโน้มที่จะมีประสิทธิภาพในการทำนายต่ำใกล้เคียงกับการเดาสุ่ม จากความหมายดังกล่าวจะเห็นว่าค่า AUC สามารถใช้เป็น metric แทนการอ่านผลจากกราฟ ROC โดยตรงได้</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/image-1194220562.png" class="img-fluid figure-img" alt="Area Under Curve (AUC)"></p>
<p></p><figcaption class="figure-caption">Area Under Curve (AUC)</figcaption><p></p>
</figure>
</div>
<div style="page-break-after: always;"></div>
<p>การคำนวณค่า AUC ด้วย R สามารถทำได้โดยใช้ฟังก์ชัน <code>roc_auc()</code> ที่มีอาร์กิวเมนท์เหมือนกับฟังก์ชัน <code>roc_curve()</code> จากตัวอย่าง logistic regression จะได้ว่าผลการวิเคราะห์ AUC เป็นดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span> <span class="fu">roc_auc</span>(<span class="at">truth =</span> Class, .pred_drop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.809</code></pre>
</div>
</div>
<p>ตารางต่อไปนี้แสดงเกณฑ์การพิจารณาค่า AUC ข้างต้น โดยจำแนกเกรดของโมเดลออกเป็น 5 ระดับตามค่าของ AUC ได้แก่ ดีมาก (A) ดี (B) ไปจนถึงยอมรับไม่ได้ (F)</p>
<table class="table">
<caption>AUC criterion</caption>
<thead>
<tr class="header">
<th>AUC</th>
<th>แปลผล</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>[0.9 , 1.0]</td>
<td>ดีมาก (A)</td>
</tr>
<tr class="even">
<td>[0.8 , 0.9)</td>
<td>ดี (B)</td>
</tr>
<tr class="odd">
<td>[0.7 , 0.8)</td>
<td>พอใช้ (C)</td>
</tr>
<tr class="even">
<td>[0.6 , 0.7)</td>
<td>แย่ (D)</td>
</tr>
<tr class="odd">
<td>[0.5 , 0.6)</td>
<td>ยอมรับไม่ได้ (F)</td>
</tr>
</tbody>
</table>
</section>
</section>
</section>
</section>
<section id="scikit-learn-library" class="level2">
<h2 class="anchored" data-anchor-id="scikit-learn-library">3.6 Scikit-Learn library</h2>
<p>scikit-learn เป็น library สำหรับวิเคราะห์ machine learning model ในโปรแกรมภาษา Python ซึ่งมีจุดเด่นคือเป็น library สำหรับพัฒนา machine learning model ที่มีประสิทธิภาพและสามารถใช้งานได้ง่าย นอกจากนี้ยังสามารถทำงานร่วมกับ library Numpy, SciPy, Pandas และ matplotlib</p>
<p>coming soon …</p>
</section>
<section id="สรป" class="level2">
<h2 class="anchored" data-anchor-id="สรป">สรุป</h2>
<p>บทเรียนนี้ผู้อ่านได้เห็นภาพของกระบวนการพัฒนา regression models ซึ่งเป็น supervised learning ประเภทหนึ่งโดยเป็นการดำเนินงานภายใต้ tidymodels framework เกือบทั้งหมด โดยยังขาดในส่วนของการจัดการข้อมูลหรือที่เรียกว่า feature engineering และส่วนการปรับแต่งค่า hyperparameters ของโมเดลทำนาย ซึ่งจะกล่าวรายละเอียดทั้งหมดในบทเรียนถัดไป</p>
</section>
</section>
<section id="บทท-4-การเตรยมขอมล-data-preprocessing" class="level1">
<h1>บทที่ 4 การเตรียมข้อมูล (data preprocessing)</h1>
<blockquote class="blockquote">
<p>Garbage in, garbage out …</p>
</blockquote>
<p>จากบทที่ 3 ผู้อ่านจะเห็นว่าข้อมูลเป็นปัจจัยนำเข้าที่สำคัญมากในการพัฒนาโมเดลการเรียนรู้ของเครื่อง การนำข้อมูลที่เป็นขยะเข้าสู่โมเดลผลลัพธ์ที่ได้ย่อมเป็นขยะ ข้อมูลที่เป็นขยะถึงแม้จะได้รับการจัดการที่ดีมากแค่ไหนก็ตาม เมื่อนำเข้าสู่โมเดล ผลลัพธ์ที่ได้ก็ยังเป็นขยะเหมือนเดิม นอกจากนี้ถึงแม้ผู้วิเคราะห์จะมีข้อมูลที่ดีแต่หากมีการจัดการที่ไม่ดี เมื่อนำเข้าสู่โมเดลก็อาจจะได้ผลลัพธ์ที่ไม่ดีเท่าที่ควรหรืออาจจะเป็นขยะเหมือนเดิมก็ได้ ดังนั้นการมีข้อมูลที่ดีและมีการจัดการอย่างเหมาะสมจึงเป็นสิ่งที่สำคัญที่ผู้พัฒนาโมเดลการเรียนรู้ของเครื่องควรให้ความสำคัญ</p>
<section id="ภาพรวมและความสำคญของ-data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="ภาพรวมและความสำคญของ-data-preprocessing">4.1 ภาพรวมและความสำคัญของ Data Preprocessing</h2>
<p><strong>การเตรียมข้อมูล (Data preprocessing)</strong> เป็นคำศัพท์เชิงเทคนิคที่ใช้เรียกกระบวนการต่าง ๆ ที่ผู้วิเคราะห์ดำเนินการกับข้อมูลก่อนที่จะนำข้อมูลไปวิเคราะห์ในอัลกอริทึมการเรียนรู้ โดยมีวัตถุประสงค์เพื่อให้การเรียนรู้ของอัลกอริทึมต่าง ๆ สามารถทำได้สำเร็จและมีประสิทธิภาพ การเตรียมข้อมูลมีหลายวิธีการ โดยแต่ละวิธีการเหมาะกับสถานการณ์และเงื่อนไขที่แตกต่างกัน อย่างไรก็ตามเราอาจจำแนกการเตรียมข้อมูลออกได้เป็น 2 ประเภท ได้แก่ การเตรียมข้อมูลงตามข้อตกลงเบื้องต้นของอัลกอริทึมการเรียนรู้ และการเตรียมเพื่อใช้ประโยชน์จากข้อมูลให้มีประสิทธิภาพสูงที่สุด</p>
<p><strong>(1) การเตรียมข้อมูลตามข้อตกลงเบื้องต้นของอัลกอริทึมการเรียนรู้</strong> เป็นการจัดระเบียบหรือจัดกระทำข้อมูล (tidying and manipulating data) เพื่อให้ข้อมูลดิบมีความพร้อมหรืออยู่ในรูปแบบที่สอดคล้องกับความต้องการของอัลกอริทึมการเรียนรู้ที่เลือกใช้ การละเลยการจัดการข้อมูลดังกล่าวอาจส่งผลให้การเรียนรู้ของอัลกอริทึมมีความผิดพลาด หรือไม่สามารถเรียนรู้ชุดข้อมูลดังกล่าวได้ ตัวอย่างต่อไปนี้แสดงการเตรียมข้อมูลเพื่อให้สอดคล้องกับข้อตกลงเบื้องต้นของอัลกอริทึมการเรียนรู้</p>
<ul>
<li><p>การจัดรูปแบบตารางข้อมูล (reshaping data) เพื่อให้ได้ตารางข้อมูลที่อยู่ในรูปแบ tidydata</p></li>
<li><p>การเปลี่ยนสถานะของตัวแปรตัวอักษร (character variable) ใน R ให้เป็นตัวแปรแบบ factor</p></li>
<li><p>การทดแทนค่าสูญหาย (missing value imputation) เพื่อทดแทนค่าสูญหายก่อนจะนำไปวิเคราะห์</p></li>
<li><p>ในโมเดล multiple linear regression มีข้อตกลงเบื้องต้นที่สำคัญหลายข้อ เช่น ต้องไม่มีปัญหา heteroscedasticity และ multicollinearity ซึ่งหากเกิดปัญหาดังกล่าวขึ้นอย่างน้อยหนึ่งอย่าง ผู้วิเคราะห์จำเป็นต้องดำเนินการแก้ไขปัญหาดังกล่าวให้เรียบร้อยก่อนที่จะทำการวิเคราะห์ข้อมูล เช่น (1) อาจใช้การแปลงค่าตัวแปรด้วย logarithm หรือใช้การแปลงแบบ Box-Cox transformation เพื่อแก้ปัญหา heteroscedasticity และ (2) อาจใช้การตัดตัวแปรอิสระที่มีความสัมพันธ์กันเองสูง ๆ ออกจากโมเดล หรือใช้การสกัดองค์ประกอบหลัก (PCA) เพื่อแก้ปัญหา multicollinearity เป็นต้น</p></li>
<li><p>สำหรับอัลกอริทึม K-NN และ regularized regression ผู้วิเคราะห์จำเป็นต้องแปลงคะแนนของตัวแปรอิสระทั้งหมดให้เป็นหน่วยคะแนนมาตรฐานก่อน เพื่อให้อัลกอริทึมดังกล่าวสามารถเรียนรู้รูปแบบความสัมพันธ์ระหว่างตัวแปรในชุดข้อมูลได้โดยไม่มีปัจจัยเกี่ยวกับหน่วยข้อมูลมาเป็นตัวแทรกซ้อนและก่อให้เกิดความผิดพลาดในการเรียนรู้</p></li>
</ul>
<div style="page-break-after: always;"></div>
<p>ผู้อ่านจะเห็นว่าการทำ data preprocessing ประเภทนี้จำเป็นต้องทำตามข้อตกลงเบื้องต้นของโมเดล ทั้งนี้เพื่อให้โมเดลหรืออัลกอริทึมการเรียนรู้สามารถทำงานได้อย่างถูกต้อง หากผู้วิเคราะห์ละเลยการดำเนินการในส่วนนี้อาจส่งผลให้ผลการเรียนรู้ของอัลกอริทึมมีความผิดพลาด และประสบความล้มเหลวในการพัฒนาโมเดลทำนายที่ต้องการ โดยทั่วไปการจัดกระทำข้อมูลอาจจำแนกเป็น การแปลงค่าของตัวแปรจัดประเภทให้เป็นตัวแปรดัมมี (dummy) การตัดตัวแปรที่มีความแปรปรวนน้อยหรือความแปรปรวนเท่ากับ 0 ออกจากชุดข้อมูล (zv) การทดแทนค่าสูญหาย (impute) การแก้ปัญหา multicollinearity (decorrelate) การแปลงคะแนนตัวแปรให้อยู่ในสเกลมาตรฐาน (normalized) และการแปลงค่าของตัวแปรให้มีการแจกแจงที่สมมาตรหรือใกล้เคียง (transform)</p>
<p>ตารางต่อไปนี้แสดงตัวอย่าง checklist ของการจัดกระทำข้อมูลที่ควรดำเนินการในแต่ละอัลกอริทึมการเรียนรู้</p>
<table class="table">
<caption>Checklist การจัดกระทำข้อมูลของอัลกอริทึมการเรียนรู้ต่าง ๆ</caption>
<colgroup>
<col style="width: 27%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 16%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>อัลกอริทึม</th>
<th>dummy</th>
<th>zv</th>
<th>impute</th>
<th>decorrelate</th>
<th>normalized</th>
<th>transform</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>linear regression</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>no</td>
<td>maybe</td>
</tr>
<tr class="even">
<td>binary logistic</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>no</td>
<td>maybe</td>
</tr>
<tr class="odd">
<td>multinomial logistic</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>no</td>
<td>maybe</td>
</tr>
<tr class="even">
<td>K-NN</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>maybe</td>
<td>yes</td>
<td>yes</td>
</tr>
<tr class="odd">
<td>naive bayes</td>
<td>no</td>
<td>yes</td>
<td>yes</td>
<td>maybe</td>
<td>no</td>
<td>no</td>
</tr>
<tr class="even">
<td>decision tree (CART)</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>maybe</td>
<td>no</td>
<td>no</td>
</tr>
<tr class="odd">
<td>decision tree (C5)</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>no</td>
</tr>
<tr class="even">
<td>pls regression</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>no</td>
<td>yes</td>
<td>yes</td>
</tr>
<tr class="odd">
<td>MARS</td>
<td>yes</td>
<td>no</td>
<td>yes</td>
<td>maybe</td>
<td>no</td>
<td>maybe</td>
</tr>
<tr class="even">
<td>SVM</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
</tr>
<tr class="odd">
<td>random forest</td>
<td>no</td>
<td>maybe</td>
<td>yes</td>
<td>maybe</td>
<td>no</td>
<td>no</td>
</tr>
<tr class="even">
<td>bagging tree</td>
<td>no</td>
<td>no</td>
<td>no</td>
<td>maybe</td>
<td>no</td>
<td>no</td>
</tr>
<tr class="odd">
<td>bagging MARS</td>
<td>yes</td>
<td>no</td>
<td>yes</td>
<td>maybe</td>
<td>no</td>
<td>maybe</td>
</tr>
<tr class="even">
<td>boosting tree</td>
<td>no</td>
<td>maybe</td>
<td>yes</td>
<td>maybe</td>
<td>no</td>
<td>no</td>
</tr>
</tbody>
</table>
<p><strong>(2) การเตรียมเพื่อใช้ประโยชน์จากข้อมูลให้มีประสิทธิภาพสูงที่สุด</strong> อาจกล่าวว่าเป็นขั้นตอนที่ทำภายหลังจากการเตรียมข้อมูลให้เป็นไปตามข้อตกลงเบื้องต้นของอัลกอริทึมแล้ว การเตรียมข้อมูลส่วนนี้ไม่ได้เป็นเงื่อนไขจำเป็นของการพัฒนาโมเดลทำนาย แต่อาจเป็นเงื่อนไขที่เพียงพอจะทำให้การพัฒนาโมเดลทำนายประสบความสำเร็จ กล่าวคือได้โมเดลทำนายที่มีประสิทธิภาพในการทำนายสูง การดำเนินการส่วนโดยปกติเป็นการจัดกระทำข้อมูลของตัวแปรอิสระ (independent variables) หรือที่นักวิทยาการข้อมูลมักใช้คำว่า features ให้มีความเหมาะสมกับบบริบทของปัญหาซึ่งจะช่วยให้การเรียนรู้ของโมเดลทำได้อย่างมีประสิทธิภาพมากขึ้น อาจเรียกการเตรียมข้อมูลประเภทนี้ว่า feature engineering</p>
<p>การทำ feature engineering มีลักษณะเด่นที่สำคัญคือเป็นการดำเนินการที่ไม่ได้ขึ้นกับอัลกอริทึมการเรียนรู้แต่ขึ้นกับบริบทของปัญหาหรือข้อมูลที่ผู้วิเคราะห์มี ดังนั้นการที่ผู้วิเคราะห์จะตัดสินใจเลือกว่าจะใช้การจัดการข้อมูลแบบใดกับตัวแปรอิสระภายในชุดข้อมูลอาจต้องพิจารณาในหลายมิติร่วมกัน เช่น สภาพของข้อมูล ตัวเลือกทั้งหมดที่เป็นไปได้ในการจัดกระทำข้อมูลของตัวแปร ลักษณะ/รูปแบบของความสัมพันธ์ในธรรมชาติระหว่างตัวแปรตามกับตัวแปรอิสระ ในหลาย ๆ ครั้งอาจจะต้องใช้หลักเหตุผลรวมทั้งศึกษาค้นคว้าเอกสารงานวิจัยหรือทฤษฎีที่เกี่ยวข้องกับตัวแปรที่กำลังดำเนินงานอยู่ นอกจากนี้การสัมภาษณ์หรือเก็บรวบรวมข้อมูลจากผู้เกี่ยวข้อง เจ้าของข้อมูล หรือผู้มีส่วนได้ส่วนเสีย (stakeholder) อาจให้สารสนเทศที่เป็นประโยชน์ต่อการดำเนินงานในส่วนนี้ จะเห็นว่าการเตรียมข้อมูลลักษณะนี้ต้องใช้ทักษะมากกว่าการเตรียมข้อมูลประเภทแรกค่อนข้างมาก และมีลักษณะที่เป็น data-driven ซึ่งการดำเนินงานจะมีลักษณะทวนซ้ำเพื่อสังเกตผลลัพธ์และปรับแต่งการจัดกระทำตัวแปรเพื่อให้ประสิทธิภาพในการทำนายมีค่าสูงที่สุดเท่าที่จะเป็นไปได้ ทั้งนี้เพื่อให้เข้าใจลักษณะและประสิทธิภาพของการทำ feature engineering มากขึ้น ขอให้ผู้อ่านลองพิจารณาตัวอย่างต่อไปนี้</p>
<div class="cell">

</div>
<p>ชุดข้อมูล <code>logistic.csv</code> ดาวน์โหลดได้จาก <a href="https://raw.githubusercontent.com/ssiwacho/2758688_ML/main/week2/logistic.csv" class="uri">https://raw.githubusercontent.com/ssiwacho/2758688_ML/main/week2/logistic.csv</a> ประกอบด้วยข้อมูลของตัวแปรตาม <code>y</code> คือสถานะการเลื่อนตำแหน่งของพนักงาน (promated และ not promoted) ส่วนตัวแปรอิสระมี 2 ตัวได้แก่ อายุของพนักงาน (<code>age</code>) และประสิทธิภาพในการทำงาน (<code>performance</code>) วัตถุประสงค์ของผู้วิเคราะห์คือพัฒนาโมเดลทำนายการได้เลื่อนตำแหน่งของพนักงานด้วยตัวแปรอิสระทั้งสองตัวดังกล่าว</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/ssiwacho/2758688_ML/main/week2/logistic.csv"</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,000
Columns: 4
$ X           &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,…
$ age         &lt;dbl&gt; 35.73, 42.92, 57.10, 46.28, 59.89, 47.25, 58.40, 52.44, 55…
$ performance &lt;dbl&gt; 8.57928964, 7.99899950, 7.10855428, 3.04652326, 6.25812906…
$ y           &lt;chr&gt; "not promoted", "not promoted", "promoted", "promoted", "p…</code></pre>
</div>
</div>
<p>ผลการสำรวจข้อมูลเบื้องต้นพบว่าชุดข้อมูล <code>dat</code> ที่นำเข้ามามีตัวแปรที่ไม่เกี่ยวข้องคือ <code>X</code> ซึ่งควรเอาออกจากชุดข้อมูล และตัวแปรตาม <code>y</code> อยู่ในรูปแบบของตัวแปรตัวอักษรซึ่งควรเปลี่ยนให้เป็นตัวแปรแบบ factor ก่อน การดำเนินการแก้ไขปัญหาดังกล่าวเป็นการจัดกระทำข้อมูลให้สอดคล้องกับการวิเคราะห์ด้วยอัลกอริทึม logistic regression ในโปรแกรม R จัดอยู่ในกลุ่มการเตรียมข้อมูลประเภทแรกดังที่ได้กล่าวไปแล้ว คำสั่งต่อไปนี้เป็นการเตรียมข้อมูลดังกล่าว</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>X) <span class="sc">%&gt;%</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">y =</span> <span class="fu">factor</span>(y, <span class="at">levels=</span><span class="fu">c</span>(<span class="st">"promoted"</span>,<span class="st">"not promoted"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>เมื่อจัดการกับข้อมูลดังกล่าวแล้ว ผู้วิเคราะห์ทำการแบ่งชุดข้อมูลออกเป็นสองชุด ได้แก่ ชุดข้อมูลฝึกหัด และชุดข้อมูลทดสอบ จากนั้นดำเนินการสำรวจความสัมพันธ์ระหว่างตัวแปรตามกับตัวแปรอิสระด้วยทัศนภาพข้อมูล</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>dat_split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(dat, <span class="at">prop =</span> <span class="fl">0.7</span>, <span class="at">strata =</span> y)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>dat_split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;1399/601/2000&gt;</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> dat_split <span class="sc">%&gt;%</span> <span class="fu">training</span>()</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> dat_split <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="co"># data exploring</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>performance))<span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">col=</span>y))<span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>            <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="576"></p>
<p></p><figcaption class="figure-caption">ผลการสำรวจข้อมูลเบื้องต้น</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>ผลการสำรวจความสัมพันธ์ระหว่างตัวแปรด้วยทัศนภาพข้อมูลข้างต้น จะเห็นว่าสามารถจำแนกพนักงานด้วยสายตาออกได้เป็น 3 กลุ่มอย่างค่อนข้างชัดเจน กลุ่มแรกคือกลุ่มที่มีประสิทธิภาพในการทำงานต่ำกว่า 0 คะแนน ซึ่งเกือบทั้งหมดไม่ได้รับการเลื่อนตำแหน่ง กลุ่มที่สองคือกลุ่มพนักงานที่ประสิทธิภาพการทำงานสูงกว่า 0 คะแนน แต่ไม่ได้รับการเลื่อนตำแหน่ง ในจำนวนนี้พบว่าส่วนใหญ่เป็นพนักงานที่มีอายุยังน้อย และกลุ่มที่สามคือกลุ่มพนักงานที่ประสิทธิภาพการทำงานสูงกว่า 0 และได้รับการเลื่อนตำแหน่ง ซึ่งในจำนวนนี้พบว่าส่วนใหญ่เป็นพนักงานที่มีอายุมาก</p>
<p>ขั้นตอนถัดมาผู้วิเคราะห์นำชุดข้อมูลฝึกหัดที่สร้างขึ้นไปให้อัลกอริทึมเรียนรู้จากนั้นทำการตรวจสอบประสิทธิภาพการทำนายของโมเดลในชุดข้อมูลทดสอบด้วย package parsnip ดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>fit_logistic1 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">set_mode</span>(<span class="st">"classification"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">fit</span>(y <span class="sc">~</span> ., <span class="at">data=</span>train)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate predicted values</span></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_logistic1, </span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">new_data =</span> test,</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_logistic1, </span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">new_data =</span> test,</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(y)<span class="sc">%&gt;%</span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>                <span class="fu">bind_cols</span>(pred, pred_prob)</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a><span class="co"># evaluate model</span></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(<span class="at">data =</span> test_results,</span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth =</span> y,</span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">estimate =</span> .pred_class)<span class="sc">%&gt;%</span></span>
<span id="cb71-19"><a href="#cb71-19" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 13 × 3
   .metric              .estimator .estimate
   &lt;chr&gt;                &lt;chr&gt;          &lt;dbl&gt;
 1 accuracy             binary         0.812
 2 kap                  binary         0.341
 3 sens                 binary         0.324
 4 spec                 binary         0.955
 5 ppv                  binary         0.677
 6 npv                  binary         0.828
 7 mcc                  binary         0.375
 8 j_index              binary         0.278
 9 bal_accuracy         binary         0.639
10 detection_prevalence binary         0.108
11 precision            binary         0.677
12 recall               binary         0.324
13 f_meas               binary         0.438</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># roc curve</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span> </span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(<span class="at">truth =</span> y,</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">estimate =</span> .pred_promoted)<span class="sc">%&gt;%</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">autoplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">ROC Curve ของ logistic regression</figcaption><p></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>test_results <span class="sc">%&gt;%</span> </span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">roc_auc</span>(<span class="at">truth =</span> y,</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">estimate =</span> .pred_promoted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.752</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># decision boundary</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">18</span>,<span class="dv">60</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">age =</span> x1,<span class="at">performance =</span> x2)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>bg.dat<span class="ot">&lt;-</span><span class="fu">data.frame</span>(grid) <span class="sc">%&gt;%</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_logistic1, grid, <span class="at">type=</span><span class="st">"class"</span>),</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">pred_prob =</span> <span class="fu">predict</span>(fit_logistic1, grid, <span class="at">type=</span><span class="st">"prob"</span>))</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> bg.dat, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>performance, <span class="at">col=</span>.pred_class), </span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> test, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span> performance, <span class="at">col=</span>y), <span class="at">shape=</span><span class="dv">16</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">col=</span><span class="st">"test dataset"</span>, <span class="at">fill=</span><span class="st">"Decision Boundary"</span>)<span class="sc">+</span></span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text=</span><span class="fu">element_text</span>(<span class="at">family=</span><span class="st">"ChulaCharasNew"</span>))<span class="sc">+</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="528"></p>
<p></p><figcaption class="figure-caption">Decision Boundary ของ logistic regression</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>ผลการพัฒนาโมเดลทำนายด้วยอัลกอริทึม logistic regression ในข้างต้นจะเห็นว่ายังไม่ประสบความสำเร็จ โดยจากรูปจะเห็นว่าพื้นที่การตัดสินใจของโมเดลทำนายอยู่บริเวณมุมขวาบนของ feature space ซึ่งยังมีความคลาดเคลื่อนอยู่มาก เมื่อพิจารณาผลการวิเคราะห์จาก confusion matrix ประกอบพบว่าโมเดลมีความไว (sensitivity) ในการทำนายการเลื่อนตำแหน่งเท่ากับ .324 ซึ่งอยู่ในระดับต่ำ แต่มีความจำเพาะ (specificity) เท่ากับ .955 ซึ่งอยู่ในระดับสูงมาก อย่างไรก็ตามค่าความจำเพาะที่สูงดังกล่าวเป็นผลมาจากการที่โมเดลมี sensitivity ต่ำมากนั่นเอง นอกจากนี้เมื่อพิจารณา AUC ของ ROC curve พบว่ามีค่าเท่ากับ .752 แสดงว่าในภาพรวมโมเดลมีประสิทธิภาพการทำนายอยู่ในระดับพอใช้</p>
<p>จากปัญหาที่พบเราสามารถแก้ปัญหาได้หลายวิธีการ วิธีการแรก ๆ ที่ควรดำเนินการคือการทำ feature engineering จากผลการสำรวจความสัมพันธ์ระหว่างตัวแปรตามกับตัวแปรอิสระในรูป 33 จะเห็นว่าการเลื่อนตำแหน่งของพนักงานไม่ได้ขึ้นกับอายุและประสิทธิภาพในการทำนายแบบเป็นเส้นตรง กล่าวคือพนักงานอายุเยอะไม่จำเป็นต้องได้เลื่อนตำแหน่งเสมอไป และพนักงานที่มีประสิทธิภาพการทำงานที่ดีก็ไม่จำเป็นที่จะต้องได้เลื่อนตำแหน่งเสมอไปเช่นกัน แต่พนักงานที่มีแนวโน้มจะได้เลื่อนตำแหน่งคือพนักงานที่มีประสิทธิภาพการทำงานดีและมีอายุ จากข้อสังเกตนี้แสดงให้เห็นว่ามีอิทธิพลปฏิสัมพันธ์ระหว่างอายุกับประสิทธิภาพการทำนายต่อการเลื่อนตำแหน่ง</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>fit_logistic2 <span class="ot">&lt;-</span> <span class="fu">logistic_reg</span>() <span class="sc">%&gt;%</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">set_engine</span>(<span class="st">"glm"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">set_mode</span>(<span class="st">"classification"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">fit</span>(y <span class="sc">~</span> . <span class="sc">+</span> age<span class="sc">*</span>performance, <span class="at">data=</span>train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.822
2 sens     binary         0.375
3 spec     binary         0.953</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">ROC Curve ของ logistic regression ที่มีอิทธิพลปฏิสัมพันธ์</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 3
  .metric .estimator .estimate
  &lt;chr&gt;   &lt;chr&gt;          &lt;dbl&gt;
1 roc_auc binary         0.801</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># decision boundary</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">18</span>,<span class="dv">60</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">age =</span> x1,<span class="at">performance =</span> x2)</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a>bg.dat<span class="ot">&lt;-</span><span class="fu">data.frame</span>(grid) <span class="sc">%&gt;%</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>          <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_logistic2, grid, <span class="at">type=</span><span class="st">"class"</span>),</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">pred_prob =</span> <span class="fu">predict</span>(fit_logistic2, grid, <span class="at">type=</span><span class="st">"prob"</span>))</span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb80-9"><a href="#cb80-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> bg.dat, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>performance, <span class="at">col=</span>.pred_class), </span>
<span id="cb80-10"><a href="#cb80-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb80-11"><a href="#cb80-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> test, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span> performance, <span class="at">col=</span>y), <span class="at">shape=</span><span class="dv">16</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb80-12"><a href="#cb80-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">col=</span><span class="st">"test dataset"</span>, <span class="at">fill=</span><span class="st">"Decision Boundary"</span>)<span class="sc">+</span></span>
<span id="cb80-13"><a href="#cb80-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text=</span><span class="fu">element_text</span>(<span class="at">family=</span><span class="st">"ChulaCharasNew"</span>))<span class="sc">+</span></span>
<span id="cb80-14"><a href="#cb80-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="528"></p>
<p></p><figcaption class="figure-caption">Decision Boundary ของ logistic regression ที่มีอิทธิพลปฏิสัมพันธ์</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>ผลการทำนายของโมเดลที่มีเทอมปฏิสัมพันธ์ระหว่างอายุกับประสิทธิภาพการทำงานพบว่าดีขึ้นเล็กน้อย แต่ยังไม่ประสบความสำเร็จ คราวนี้เราลองพิจารณาทางเลือกในการแปลงค่าของตัวแปรในลักษณะอื่นบ้าง จากผลการสำรวจที่พบว่าการเลื่อนตำแหน่งขึ้นกับปัจจัยอายุและประสิทธิภาพการทำงานผู้วิเคราะห์สร้างตัวแปรใหม่ในชุดข้อมูลเป็นอัตราส่วนอายุต่อประสิทธิภาพการทำงาน (<code>ratio_age_performance</code>) จากนั้นดำเนินการ fit โมเดลเหมือนกับสองโมเดลแรกที่ผ่านมา</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat<span class="sc">%&gt;%</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>        <span class="fu">mutate</span>(<span class="at">ratio_age_performance =</span> age<span class="sc">/</span>performance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>&lt;Training/Testing/Total&gt;
&lt;1399/601/2000&gt;</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: glm.fit: fitted probabilities numerically 0 or 1 occurred</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>              Truth
Prediction     promoted not promoted
  promoted          129            6
  not promoted        7          459</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.978
2 sens     binary         0.949
3 spec     binary         0.987</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="336"></p>
<p></p><figcaption class="figure-caption">ROC Curve ของ logistic regression ที่มีการทำ feature engineering</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># decision boundary</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">18</span>,<span class="dv">60</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">age =</span> x1,<span class="at">performance =</span> x2)<span class="sc">%&gt;%</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">mutate</span>(<span class="at">ratio_age_performance =</span> age<span class="sc">/</span>performance)</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>bg.dat<span class="ot">&lt;-</span><span class="fu">data.frame</span>(grid) <span class="sc">%&gt;%</span></span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_logistic3, grid, <span class="at">type=</span><span class="st">"class"</span>),</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">pred_prob =</span> <span class="fu">predict</span>(fit_logistic3, grid, <span class="at">type=</span><span class="st">"prob"</span>))</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> bg.dat, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>performance, <span class="at">col=</span>.pred_class), </span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> test, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span> performance, <span class="at">col=</span>y), <span class="at">shape=</span><span class="dv">16</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">col=</span><span class="st">"test dataset"</span>, <span class="at">fill=</span><span class="st">"Decision Boundary"</span>)<span class="sc">+</span></span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">text=</span><span class="fu">element_text</span>(<span class="at">family=</span><span class="st">"ChulaCharasNew"</span>))<span class="sc">+</span></span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid figure-img" width="528"></p>
<p></p><figcaption class="figure-caption">Decision Boundary ของ logistic regression ที่มีการทำ Feature Engineering</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>คราวนี้ลองเปลี่ยนโมเดลทำนายข้างต้นเป็น decision tree แบบ CART ที่มีจุดเด่นคือเป็นโมเดลจำแนกแบบ nonlinear classification กล่าวคือโมเดล decision tree ควรมีประสิทธิภาพในการจำแนกพนักงานที่จะได้เลื่อนและไม่ได้เลื่อนตำแหน่งได้สูงกว่า logistic regression ที่ยังไม่ได้ทำ feature engineering</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>fit_tree <span class="ot">&lt;-</span> <span class="fu">decision_tree</span>() <span class="sc">%&gt;%</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">set_engine</span>(<span class="st">"rpart"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">set_mode</span>(<span class="st">"classification"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">fit</span>(y <span class="sc">~</span> . , <span class="at">data=</span>train)</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate predicted values</span></span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_tree, </span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">new_data =</span> test,</span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"class"</span>)</span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>pred_prob <span class="ot">&lt;-</span> <span class="fu">predict</span>(fit_tree, </span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">new_data =</span> test,</span>
<span id="cb87-12"><a href="#cb87-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">type =</span> <span class="st">"prob"</span>)</span>
<span id="cb87-13"><a href="#cb87-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-14"><a href="#cb87-14" aria-hidden="true" tabindex="-1"></a>test_results <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(y)<span class="sc">%&gt;%</span></span>
<span id="cb87-15"><a href="#cb87-15" aria-hidden="true" tabindex="-1"></a>                <span class="fu">bind_cols</span>(pred, pred_prob)</span>
<span id="cb87-16"><a href="#cb87-16" aria-hidden="true" tabindex="-1"></a><span class="co"># evaluate model</span></span>
<span id="cb87-17"><a href="#cb87-17" aria-hidden="true" tabindex="-1"></a><span class="fu">conf_mat</span>(<span class="at">data =</span> test_results,</span>
<span id="cb87-18"><a href="#cb87-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth =</span> y,</span>
<span id="cb87-19"><a href="#cb87-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Truth
Prediction     promoted not promoted
  promoted          124            6
  not promoted       12          459</code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>eval_metric <span class="ot">&lt;-</span> <span class="fu">metric_set</span>(accuracy, sens, spec)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">eval_metric</span>(<span class="at">data =</span> test_results,</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">truth =</span> y,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">estimate =</span> .pred_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  .metric  .estimator .estimate
  &lt;chr&gt;    &lt;chr&gt;          &lt;dbl&gt;
1 accuracy binary         0.970
2 sens     binary         0.912
3 spec     binary         0.987</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># decision boundary</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">18</span>,<span class="dv">60</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>,<span class="at">length=</span><span class="dv">100</span>)</span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">age =</span> x1,<span class="at">performance =</span> x2)<span class="sc">%&gt;%</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">mutate</span>(<span class="at">ratio_age_performance =</span> age<span class="sc">/</span>performance)</span>
<span id="cb91-6"><a href="#cb91-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb91-7"><a href="#cb91-7" aria-hidden="true" tabindex="-1"></a>bg.dat<span class="ot">&lt;-</span><span class="fu">data.frame</span>(grid) <span class="sc">%&gt;%</span></span>
<span id="cb91-8"><a href="#cb91-8" aria-hidden="true" tabindex="-1"></a>          <span class="fu">bind_cols</span>(<span class="fu">predict</span>(fit_tree, grid, <span class="at">type=</span><span class="st">"class"</span>),</span>
<span id="cb91-9"><a href="#cb91-9" aria-hidden="true" tabindex="-1"></a>                    <span class="at">pred_prob =</span> <span class="fu">predict</span>(fit_tree, grid, <span class="at">type=</span><span class="st">"prob"</span>))</span>
<span id="cb91-10"><a href="#cb91-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>()<span class="sc">+</span></span>
<span id="cb91-11"><a href="#cb91-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> bg.dat, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span>performance, <span class="at">col=</span>.pred_class), </span>
<span id="cb91-12"><a href="#cb91-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape=</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>, <span class="at">alpha=</span><span class="fl">0.5</span>)<span class="sc">+</span></span>
<span id="cb91-13"><a href="#cb91-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> test, <span class="fu">aes</span>(<span class="at">x=</span>age, <span class="at">y=</span> performance, <span class="at">col=</span>y), <span class="at">shape=</span><span class="dv">16</span>, <span class="at">size=</span><span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb91-14"><a href="#cb91-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">col=</span><span class="st">"test dataset"</span>, <span class="at">fill=</span><span class="st">"Decision Boundary"</span>)<span class="sc">+</span></span>
<span id="cb91-15"><a href="#cb91-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02MLProcess_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid figure-img" width="528"></p>
<p></p><figcaption class="figure-caption">Decision Boundary ของ Decision Tree (CART algorithm)</figcaption><p></p>
</figure>
</div>
</div>
</div>
<p>ผู้อ่านจะเห็นว่าการทำ feature engineering โดยสร้างเทอมอัตราส่วนระหว่างอายุกับประสิทธิภาพการทำงานของพนักงานในการทำนายการเลื่อนตำแหน่งของพนักงานใน logistic regression ช่วยให้พื้นที่การตัดสินใจของโมเดลทำนายแบบ logistic regression พัฒนาขึ้นมาก จากเดิมที่เป็น linear classification เป็น nonlinear classification และมีประสิทธิภาพการทำนายบนชุดข้อมูลทดสอบที่สูงมากใกล้เคียงกับการใช้ decision tree ที่เป็น nonlinear classification (อย่างไรก็ตาม decision tree มี hyperparameter ที่สามารถปรับแต่งได้อีก ซึ่งอาจเพิ่มประสิทธิภาพในการทำนายได้มากขึ้นกว่านี้) ตัวอย่างนี้เป็นตัวอย่างหนึ่งที่แสดงให้เห็นว่าการทำ feature engineering ที่เหมาะสมนั้นช่วยเพิ่มประสิทธิภาพการทำนายให้กับโมเดลได้อย่างไร</p>
</section>
<section id="ประเภทของ-data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="ประเภทของ-data-preprocessing">4.2 ประเภทของ Data Preprocessing</h2>
<p>ดังที่ได้กล่าวในข้างต้นว่า data preprocessing เป็นกระบวนการจัดการข้อมูลที่มีลักษณะทวนซ้ำ และไม่ได้มีขั้นตอนการดำเนินการที่แน่นอน ขั้นตอนการดำเนินการจัดการข้อมูลในแต่ละงานขึ้นอยู่กับสภาพของข้อมูล และวัตถุประสงค์ของการวิเคราะห์ในแต่ละงาน โดยทั่วไปการจัดการข้อมูลอาจจำแนกเป็น 3 ประเภทได้แก่</p>
<ul>
<li><p><strong>การทำความสะอาดข้อมูล (data cleaning)</strong></p></li>
<li><p><strong>การแปลงข้อมูล (data transformation)</strong></p></li>
<li><p><strong>การคัดเลือกตัวแปร (feature selection)</strong></p></li>
</ul>
<p>รายละเอียดมีดังนี้</p>
<section id="การทำความสะอาดขอมล-data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="การทำความสะอาดขอมล-data-cleaning">การทำความสะอาดข้อมูล (data cleaning)</h3>
<p>การทำความสะอาดข้อมูลเป็นกระบวนการเพื่อสำรวจ วินิจฉัย และแก้ไขความผิดปกติที่เกิดขึ้นในข้อมูล ความผิดปกติดังกล่าวสามารถเกิดขึ้นได้จากหลายสาเหตุ เช่น การจัดเก็บหรือบันทึกข้อมูลที่ผิดพลาด หรือการวัดข้อมูลมีความคลาดเคลื่อนจากการวัด ความผิดปกติดังกล่าวมีโอกาสเกิดขึ้นได้เป็นประจำ จึงเป็นหน้าที่ของนักวิทยาการข้อมูลที่จะต้องสำรวจ และวินิจฉัยความผิดปกติดังกล่าวในชุดข้อมูล จากนั้นจึงดำเนินการแก้ไขอย่างเหมาะสม วัตถุประสงค์ของการทำความสะอาดข้อมูลคือการได้มาซึ่งชุดข้อมูลใหม่ที่มีความพร้อมในการนำไปวิเคราะห์ได้โดยไม่มีความผิดพลาด การทำความสะอาดข้อมูลจัดอยู่ในกลุ่มการเตรียมข้อมูลให้สอดคล้องกับความต้องการหรือข้อตกลงเบื้องต้นของอัลกอริทึมการเรียนรู้ ซึ่งเกี่ยวข้องกับการดำเนินการหรือเทคนิควิธีการหลายอย่าง ได้แก่</p>
<ul>
<li><p><strong>การจัดระเบียบและจัดกระทำข้อมูล (tidying and manipulating data)</strong> ซึ่งเกี่ยวข้องกับการจัดรูปแบบของตารางข้อมูลให้อยู่ในรูปแบบที่เหมาะสมสำหรับการวิเคราะห์ เช่นการเปลี่ยนรูปแบบตารางระหว่างตารางข้อมูลรูปแบบยาว (long format) กับรูปแบบกว้าง (wide format) การเปลี่ยนสถานะของตัวแปรในชุดข้อมูลให้เหมาะสม การแยกและยุบรวมคอลัมนท์ การจัดการกับข้อมูลซ้ำซ้อน การรวมชุดข้อมูล การคัดกรองข้อมูล เป็นต้น package ของ R ที่เกี่ยวข้องกับการดำเนินการส่วนนี้ ได้แก่ tidyr และ dplyr (รายละเอียดสามารถศึกษาได้จาก สิวะโชติ ศรีสุทธิยากร (2564)) &lt;--- ไม่พูดถึงแล้วในรายวิชานี้</p></li>
<li><p><strong>การสำรวจและจัดการกับค่าผิดปกติ</strong> เกี่ยวข้องกับการสำรวจข้อมูล วินิจฉัยความผิดปกติของข้อมูล และการแก้ไขปัญหาความผิดปกติของข้อมูล ข้อมูลที่ผิดปกติอาจจำแนกได้เป็นสามประเภทตามสาเหตุของการเกิด เช่น outlier, anomaly และ noisy data</p></li>
<li><p><strong>การวิเคราะห์และทดแทนค่าสูญหาย</strong> เป็นปกติที่ชุดข้อมูลจะมีข้อมูลที่สูญหายไม่ครบถ้วน หากค่าสูญหายดังกล่าวเกิดขึ้นเป็นจำนวนมากเกินไป และมีรูปแบบการเกิดที่เป็นระบบ อาจส่งผลให้การเรียนรู้ของเครื่องมีความลำเอียงหรือมีความน่าเชื่อถือที่ลดลงได้ การวิเคราะห์รูปแบบของค่าสูญหาย และการเลือกวิธีการทดแทนค่าสูญหายที่เหมาะสมจะช่วยลดทอนผลกระทบที่เกิดจากค่าสูญหายดังกล่าว</p></li>
</ul>
</section>
<section id="การแปลงขอมล-data-transformation" class="level3">
<h3 class="anchored" data-anchor-id="การแปลงขอมล-data-transformation">การแปลงข้อมูล (data transformation)</h3>
<p>การแปลงข้อมูลเป็นกระบวนการเปลี่ยนลักษณะหรือรูปแบบของข้อมูลจากรูปแบบหนึ่งไปเป็นอีกรูปแบบหนึ่ง เพื่อให้เหมาะกับความต้องการหรือข้อตกลงเบื้องต้นของการวิเคราะห์ที่เลือกใช้ ได้แก่ การแปลงข้อมูลจัดประเภทให้เป็นตัวแปรตัวเลข เช่น dummy encoding หรือ one-hot encoding การแปลงข้อมูลที่ไม่สมมาตรให้สมมาตร หรือการแปลงข้อมูลจากหน่วยใด ๆ ให้อยู่ในหน่วยมาตรฐานเพื่อให้สามารถเปรียบเทียบกันได้ หรือลดผลกระทบจากหน่วยข้อมูลที่มีต่อการเรียนรู้ของเครื่องในบางอัลกอริทึม นอกจากนี้การแปลงข้อมูลยังเป็นเทคนิคที่อาจช่วยให้การวิเคราะห์มีประสิทธิภาพสูงขึ้นดังตัวอย่างที่แสดงไว้ในส่วนนำของบทเรียนนี้</p>
</section>
<section id="การคดเลอกตวแปร-feature-selection" class="level3">
<h3 class="anchored" data-anchor-id="การคดเลอกตวแปร-feature-selection">การคัดเลือกตัวแปร (feature selection)</h3>
<p>เป็นกระบวนการคัดเลือกตัวแปรอิสระภายในชุดข้อมูลที่มีประสิทธิภาพสำหรับการวิเคราะห์หรือพัฒนาโมเดลทำนาย กระบวนการนี้มีความสำคัญมากโดยเฉพาะในสถานการณ์ที่ผู้วิเคราะห์มีชุดข้อมูลขนาดใหญ่และมีตัวแปรจำนวนมาก การคัดเลือกตัวแปรจะช่วยลดขนาดของชุดข้อมูลและช่วยให้ผู้วิเคราะห์ทำงานได้ง่ายขึ้น โดยทั่วไปอาจจำแนกวิธีการคัดเลือกตัวแปรได้เป็น 3 ประเภทได้แก่ filter methods, wrapper methods และ embedded methods</p>
<p><strong>Filter methods</strong> เป็นวิธีการพื้นฐานสำหรับการคัดเลือกตัวแปรอิสระ วิธีการในกลุ่มนี้จะเป็นการใช้ค่าสถิติพื้นฐาน ได้แก่ สัมประสิทธิ์สหสัมพันธ์ และใช้ความรู้จากการทบทวนวรรณกรรม ประสบการณ์ของผู้วิเคราะห์ ความคิดเห็นของผู้เกี่ยวข้องหรือผู้ทรงคุณวุฒิ เข้ามาร่วมกันเพื่อคัดเลือกชุดของตัวแปรอิสระที่เหมาะสม</p>
<p><strong>Wrapper methods</strong> เป็นวิธีการที่คัดเลือกตัวแปรอิสระในโมเดลด้วยอัลกอริทึมสำหรับคัดเลือกตัวแปรได้แก่ forward selection, backward selection, stepwise selection หรือ recursive feature elimination เป็นต้น</p>
<p><strong>Embedded methods</strong> เป็นวิธีการคัดเลือกตัวแปรอิสระที่รวมไปกับกระบวนการเรียนรู้ของอัลกอริทึมบางตัว เช่น lasso regression และ decision tree</p>
</section>
</section>
<section id="พนฐาน-recipe-สำหรบทำ-data-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="พนฐาน-recipe-สำหรบทำ-data-preprocessing">4.3 พื้นฐาน <code>recipe</code> สำหรับทำ Data Preprocessing</h2>
<p><img src="images/image-1527588902.png" class="img-fluid" style="width:30.0%"></p>
<p>การทำ data preprocessing เป็นกระบวนการที่มีการใช้ทั้งการจัดกระทำข้อมูล สถิติและอัลกอริทึมการเรียนรู้ จริง ๆ แล้วการดำเนินการดังกล่าวสามารถทำได้โดยใช้คำสั่งพื้นฐานปกติใน R อย่างไรก็ตามในกระบวนการพัฒนาโมเดลที่มีการดำเนินการแบบทวนซ้ำแต่ละขั้นตอนไปมาซึ่งการเขียนคำสั่งแบบปกติอาจไม่สะดวกนัก โดยเฉพาะในกรณีที่ผู้วิเคราะห์มีการใช้เทคนิคการจัดการข้อมูลหลาย ๆ เทคนิคต่อเนื่องกัน เช่น การแปลงค่า — &gt;การทดแทนค่าสูญหาย —&gt; การสร้างองค์ประกอบด้วย PCA บทเรียนนี้จะกล่าวถึงการใช้ package recipe เพื่อใช้เป็นวิธีการทางเลือกสำหรับผู้วิเคราะห์ในการทำ data preprocessing ภายใต้ package นี้ผู้วิเคราะห์สามารถดำเนินการทำ data preprocessing ที่มีหลายขั้นตอนหลายเทคนิคได้อย่างต่อเนื่องโดยใช้ piping operator คล้ายกับการทำงานใน package dplyr นอกจากนี้ยังนำกระบวนการที่กำหนดไปทำซ้ำกับชุดข้อมูลอื่นได้โดยง่าย เนื้อหาในหัวข้อนี้จะกล่าวถึงพื้นฐานการใช้ package recipe ดังกล่าวรายละเอียดมีดังนี้</p>
<section id="การดาวนโหลดและตดตง-package" class="level3">
<h3 class="anchored" data-anchor-id="การดาวนโหลดและตดตง-package">การดาวน์โหลดและติดตั้ง package</h3>
<p>กรณีที่ติดตั้ง package tidymodels จะดาวน์โหลดและติดตั้ง package recipe โดยอัตโนมัติ ส่วนในกรณีที่ต้องการติดตั้งแยกสามารถพิมพ์คำสั่งดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># CRAN version</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"recipe"</span>)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(recipe)</span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># development version from GitHub</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>devtools<span class="sc">::</span><span class="fu">install_github</span>(<span class="st">"tidymodels/recipes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="ขนตอนการทำ-data-preprocessing-ดวย-recipe" class="level3">
<h3 class="anchored" data-anchor-id="ขนตอนการทำ-data-preprocessing-ดวย-recipe">ขั้นตอนการทำ data preprocessing ด้วย recipe</h3>
<p>การทำ data preprocessing ด้วย package recipe ประกอบด้วยขั้นตอนการดำเนินงานหลัก 4 ขั้นได้แก่</p>
<ol type="1">
<li><p>ขั้นตอนการกำหนดสถานะของตัวแปร ว่าภายในชุดข้อมูลที่ดำเนินการอยู่ ตัวแปรใดเป็นตัวแปรตามตัวแปรใดเป็นตัวแปรอิสระ รวมถึงพิจารณาประเภทของข้อมูลในแต่ละตัวแปรด้วย ซึ่งปกติสามารถจำแนกได้ 2 ประเภทได้แก่ ข้อมูลตัวเลข และข้อมูลแบบจัดประเภท การดำเนินการในขั้นนี้จะใช้ฟังก์ชัน <code>recipe()</code></p></li>
<li><p>ขั้นตอนการกำหนดวิธีการจัดการข้อมูลที่ต้องการ โดยผู้วิเคราะห์สามารถกำหนดวิธีการจัดการข้อมูลที่ต้องการผ่านฟังก์ชัน <code>step_*()</code> ที่ครอบคลุมทั้งการแปลงค่าข้อมูล เช่น การแปลงให้เป็นคะแนนมาตรฐาน การแปลงด้วยฟังก์ชัน log การสร้างตัวแปรใหม่จากข้อมูลของตัวแปรเดิม หรือ การทดแทนค่าสูญหาย (missing data imputation) เป็นต้น ผู้อ่านสามารถศึกษารายละเอียดของฟังก์ชัน <code>step_*()</code> ทั้งหมดภายใต้ package recipe ได้จาก <a href="https://recipes.tidymodels.org/reference/index.html" class="uri">https://recipes.tidymodels.org/reference/index.html</a></p></li>
<li><p>การจัดการข้อมูลหลายตัวมีการใช้วิธีการทางสถิติหรืออัลกอริทึมการเรียนรู้ที่จะต้องใช้ผลการวิเคราะห์จากชุดข้อมูลฝึกหัดมาเป็นค่าพารามิเตอร์หรือค่าสถิติสำหรับจัดการข้อมูลที่กำหนด (แต่การจัดการข้อมูลบางตัวก็ไม่ต้องใช้) ดังนั้นเมื่อผู้วิเคราะห์กำหนดสถานะของตัวแปรและการจัดการข้อมูลเรียบร้อยแล้ว ขั้นตอนที่ 3 คือการนำตัวแปรจาก <code>recipe()</code> ข้างต้นมาผ่านการประมวลผลหรือวิเคราะห์โดยใช้ชุดข้อมูลฝึกหัดเป็นข้อมูลนำเข้า เช่น หากผู้วิเคราะห์กำหนดให้มีการแปลงคะแนนตัวแปรให้เป็นสเกลมาตรฐาน ขั้นตอนนี้จะเป็นการคำนวนค่าเฉลี่ย และส่วนเบี่ยงเบนมาตรฐานของตัวแปรในชุดข้อมูลฝึกหัดที่กำหนดเพื่อใช้ในการ centering และ scaling ตัวแปรในชุดข้อมูลที่ต้องการจะทำ data preprocessing ในอนาคต การดำเนินการใช้ขั้นตอนนี้จะใช้ฟังก์ชัน <code>prep()</code></p></li>
<li><p>ขั้นตอนสุดท้ายคือการจัดการข้อมูลตามที่วางแผนไว้บนชุดข้อมูลที่กำหนด ซึ่งเป็นไปได้ทั้ง training dataset, test dataset หรือชุดข้อมูลอื่น ๆ ที่จะนำเข้าสู่โมเดลทำนายในอนาคต (เพราะ ML model ที่พัฒนาต้องจะต้องการข้อมูลที่มีการจัดการเหมือนกับชุดข้อมูลฝึกหัด) การดำเนินการในขั้นตอนนี้จะใช้ฟังก์ชัน <code>bake()</code></p></li>
</ol>
<p>ตัวอย่างต่อไปนี้แสดงทำ data preprocessing ด้วย package recipe ตามขั้นตอนข้างต้น จากชุดข้อมูล <a href="https://github.com/ssiwacho/2758688_ML/blob/main/week%201/TeacherSalaryData.csv"><code>TeacherSalaryData.csv</code></a> สมมุติว่าผู้วิจัยต้องการแปลงค่าของตัวแปร <code>salary</code> ด้วยฟังก์ชัน log สามารถดำเนินการได้ดังนี้</p>
<p><strong>ขั้นที่ 0 : นำเข้าและแบ่งชุดข้อมูล</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"https://raw.githubusercontent.com/ssiwacho/2758688_ML/main/week%201/TeacherSalaryData.csv"</span>)</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat[,<span class="sc">-</span><span class="dv">1</span>] <span class="co">#remove X</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>dat <span class="ot">&lt;-</span> dat<span class="sc">%&gt;%</span><span class="fu">mutate_if</span>(is.character, factor)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="co"># data splitting</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span> <span class="fu">initial_split</span>(<span class="at">data =</span> dat, <span class="at">prop =</span> <span class="fl">0.8</span>)</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>salary_train <span class="ot">&lt;-</span> split <span class="sc">%&gt;%</span> <span class="fu">training</span>()</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>salary_test <span class="ot">&lt;-</span> split <span class="sc">%&gt;%</span> <span class="fu">testing</span>()</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        rank     discipline yrs.since.phd    yrs.service        sex     
 AssocProf: 55   A:141      Min.   : 1.00   Min.   : 0.00   Female: 35  
 AsstProf : 51   B:176      1st Qu.:12.00   1st Qu.: 7.00   Male  :282  
 Prof     :211              Median :22.00   Median :17.00               
                            Mean   :22.57   Mean   :17.88               
                            3rd Qu.:32.00   3rd Qu.:26.00               
                            Max.   :56.00   Max.   :60.00               
     salary      
 Min.   : 57800  
 1st Qu.: 91000  
 Median :108200  
 Mean   :114839  
 3rd Qu.:135027  
 Max.   :231545  </code></pre>
</div>
</div>
<p><strong>ขั้น 1 : กำหนดสถานะของตัวแปร และพิจารณาความถูกต้องของประเภทข้อมูลในแต่ละตัวแปร</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a>salary_rec <span class="ot">&lt;-</span> <span class="fu">recipe</span>(salary <span class="sc">~</span>., <span class="at">data =</span> salary_train)</span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>salary_rec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recipe

Inputs:

      role #variables
   outcome          1
 predictor          5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a>salary_rec <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  variable      type    role      source  
  &lt;chr&gt;         &lt;chr&gt;   &lt;chr&gt;     &lt;chr&gt;   
1 rank          nominal predictor original
2 discipline    nominal predictor original
3 yrs.since.phd numeric predictor original
4 yrs.service   numeric predictor original
5 sex           nominal predictor original
6 salary        numeric outcome   original</code></pre>
</div>
</div>
<p>ผลการวิเคราะห์ข้างต้นจะเห็นว่าภายในชุดข้อมูลประกอบด้วย 6 ตัวแปร มีตัวแปรตามคือ salary ซึ่งเป็นตัวแปรเชิงปริมาณ ตัวแปรที่เหลือเป็นตัวแปรอิสระที่ประกอบด้วยตัวแปรเชิงปริมาณจำนวน 2 ตัว และตัวแปรจัดประเภทจำนวน 3 ตัว</p>
<p><strong>ขั้น 2 : กำหนดการจัดการข้อมูลให้กับตัวแปร <code>recipe</code> จากขั้นที่ 1</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a>salary_rec <span class="ot">&lt;-</span> salary_rec <span class="sc">%&gt;%</span></span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">step_log</span>(salary, <span class="at">base =</span> <span class="dv">10</span>)</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a>salary_rec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recipe

Inputs:

      role #variables
   outcome          1
 predictor          5

Operations:

Log transformation on salary</code></pre>
</div>
</div>
<p>ผลลัพธ์ในข้างต้นแสดงให้เห็นว่ามีการกำหนดให้แปลงค่าของตัวแปร <code>salary</code> ด้วยฟังก์ชัน log</p>
<p><strong>ขั้น 3 : การประมวลผล preprocessing model</strong></p>
<p>ขั้นตอนนี้เป็นการนำกรอบการจัดการข้อมูลที่กำหนดให้ขั้นที่ 1 และ 2 มาประมวลผลบนชุดข้อมูลฝึกหัด ด้วยฟังก์ชัน <code>prep()</code> โดยฟังก์ชันดังกล่าวจะคำนวณค่าสถิติที่จำเป็นหรือให้อัลกอริทึมการเรียนรู้ทำการประมวลผลลัพธ์ที่จำเป็นสำหรับการจัดการข้อมูลตามที่กำหนดไว้ ฟังก์ชัน <code>prep()</code> มีอาร์กิวเมนท์ที่สำคัญคือ <code>training</code> ที่ใช้ระบุชุดข้อมูลฝึกหัดสำหรับการจัดการข้อมูล</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>salary_rec_prep <span class="ot">&lt;-</span> salary_rec <span class="sc">%&gt;%</span> <span class="fu">prep</span>(<span class="at">training =</span> salary_train)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a>salary_rec_prep</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Recipe

Inputs:

      role #variables
   outcome          1
 predictor          5

Training data contained 317 data points and no missing data.

Operations:

Log transformation on salary [trained]</code></pre>
</div>
</div>
<p>จะเห็นว่าเมื่อผ่านตัวแปรของ <code>recipe</code> เข้าสู่ฟังก์ชัน <code>prep</code> แล้วจะมีการขึ้นสถานะว่า <code>[trained]</code> ซึ่งหมายถึง package recipe ได้ประมวลผลที่จำเป็นสำหรับการจัดการข้อมูลตามที่กำหนดแล้ว และเก็บผลดังกล่าวเอาไว้ในตัวแปร <code>salary_rec_pre</code></p>
<p><strong>ขั้น 4 : การจัดการข้อมูล</strong></p>
<p>อย่างที่กล่าวไว้แล้วว่าขั้นที่ 1 - 3 ถือเป็นขั้นตอนการวางแผนและเตรียมการจัดการข้อมูล ส่วนขั้นที่ 4 เป็นการจัดการข้อมูลบนชุดข้อมูลที่กำหนด ด้วยฟังก์ชัน <code>bake()</code> โดยจะใช้กรอบการจัดการข้อมูลที่กำหนดในขั้นตอนที่ 1 และ 2 และจะใช้ค่าสถิติที่จำเป็นสำหรับการจัดการข้อมูลที่ได้จากขั้นตอนที่ 3 ฟังก์ชัน <code>bake()</code> มีอาร์กิวเมนท์สำคัญหนึ่งตัวคือ <code>new_data</code> ที่ใช้ระบุชุดข้อมูลที่จะต้องการดำเนินการ ในกรณีที่ต้องการจัดการข้อมูลฝึกหัดที่ใช้เป็นชุดข้อมูลฝึกหัดในขั้นตอนที่ 3 ให้กำหนด <code>new_data = NULL</code> ดังตัวอย่างต่อไปนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a>salary_train_baked <span class="ot">&lt;-</span> salary_rec_prep <span class="sc">%&gt;%</span> <span class="fu">bake</span>(<span class="at">new_data =</span> <span class="cn">NULL</span>)</span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(salary_train_baked)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        rank     discipline yrs.since.phd    yrs.service        sex     
 AssocProf: 55   A:141      Min.   : 1.00   Min.   : 0.00   Female: 35  
 AsstProf : 51   B:176      1st Qu.:12.00   1st Qu.: 7.00   Male  :282  
 Prof     :211              Median :22.00   Median :17.00               
                            Mean   :22.57   Mean   :17.88               
                            3rd Qu.:32.00   3rd Qu.:26.00               
                            Max.   :56.00   Max.   :60.00               
     salary     
 Min.   :4.762  
 1st Qu.:4.959  
 Median :5.034  
 Mean   :5.044  
 3rd Qu.:5.130  
 Max.   :5.365  </code></pre>
</div>
</div>
<p>ในกรณีที่ต้องการนำการจัดการข้อมูลที่ train ไว้ในขั้นที่ 3 ไปใช้กับชุดข้อมูลอื่นเช่น <code>salary_test</code> สามารถเขียนคำสั่งได้ดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a>salary_test_baked <span class="ot">&lt;-</span> salary_rec_prep <span class="sc">%&gt;%</span> <span class="fu">bake</span>(<span class="at">new_data =</span> salary_test)</span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a>salary_test_baked</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 80 × 6
   rank     discipline yrs.since.phd yrs.service sex   salary
   &lt;fct&gt;    &lt;fct&gt;              &lt;int&gt;       &lt;int&gt; &lt;fct&gt;  &lt;dbl&gt;
 1 AsstProf B                      4           3 Male    4.90
 2 Prof     A                     36          31 Male    5.01
 3 AsstProf B                      5           3 Male    4.92
 4 AsstProf B                     11           0 Male    4.89
 5 Prof     B                     13           9 Male    5.07
 6 AsstProf B                      4           2 Male    4.90
 7 Prof     B                     40          27 Male    5.01
 8 Prof     B                     12          11 Male    5.04
 9 Prof     B                     16           9 Male    5.03
10 AsstProf B                      8           3 Male    4.88
# … with 70 more rows</code></pre>
</div>
</div>
<p>จะเห็นว่าชุดข้อมูลทั้งสองมีการจัดการข้อมูลของตัวแปร salary ตามที่กำหนดไว้เรียบร้อยแล้ว เนื้อหาในส่วนต่อไปจะกล่าวถึงเทคนิคการทำ data preprocessing สำหรับสถานการณ์ต่าง ๆ โดยจะใช้ package recipe ในการดำเนินการ</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../documents/01basicConcepts.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Wk01 Intro to ML</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../documents/03TreeModels.html" class="pagination-link">
        <span class="nav-page-text">Wk03 Decision Trees</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2023, DataKruRoo</div>   
    <div class="nav-footer-right">This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>