---
title: "ch01"
format: html
---

การวิเคราะห์เครือข่ายสังคม (Social Network Analysis: SNA) เป็นวิธีการเชิงคอมพิวเตอร์ที่มักถูกนำมาใช้วิเคราะห์ปฏิสัมพันธ์ ความสัมพันธ์ และการเชื่อมต่อระหว่างหน่วยข้อมูลที่หลากหลาย ซึ่งเป็นไปได้ทั้ง คน สัตว์ เมือง องค์กร หรือสิ่งที่เป็นนามธรรมต่าง ๆ เช่น แนวคิด หรือ เหตุการณ์

SNA เป็นสาขาหนึ่งภายใต้การวิเคราะห์เครือข่าย ซึ่งเน้นการวิเคราะห์เพื่อระบุรูปแบบ อธิบาย โครงสร้างความสัมพันธ์ที่เป็นเครือข่ายระหว่างคนหรือหน่วยข้อมูลลักษณะอื่น ๆ ภายใต้บริบทต่าง ๆ ของสังคม อย่างไรก็ตามแนวคิดหรือเครื่องมือที่ใช้ในการวิเคราะห์เครือข่ายสังคมนี้ก็อาจนำไปวิเคราะห์เครือข่ายลักษณะอื่น ๆ ได้โดยไม่จำเป็นต้องเป็นเครือข่ายสังคมเสมอไป ในรายวิชานี้ เราจะใช้คำว่า การวิเคราะห์เครือข่ายสังคม และ การวิเคราะห์เครือข่าย สลับกันไปตามบริบท โดยถือว่าเป็นคำที่สามารถใช้แทนกันได้

โดยปกติแล้วในการวิเคราะห์ข้อมูลทั่วไป มักมีข้อตกลงเบื้องต้นเกี่ยวกับความเป็นอิสระของค่าสังเกต กล่าวคือค่าสังเกตแต่ละค่าจะได้จากหน่วยข้อมูลที่มีความเป็นอิสระซึ่งกันและกัน

อย่างไรก็ตามในการวิเคราะห์เครือข่ายข้อมูลค่าสังเกตนี้สามารถมีความเกี่ยวข้องกันหรือมีความสัมพันธ์กันได้ นอกจากนี้ยังสามารถมีปฏิสัมพันธ์หรือมีอิทธิพลซึ่งกันและกันได้ด้วย จากลักษณะดังกล่าวการวิเคราะห์เครือข่ายจึงให้สารสนเทศที่มีความสอดคล้องกับปรากฏการณ์ภายใต้บริบทที่หน่วยข้อมูลต่าง ๆ มีความเชื่อมโยงถึงกันหรือเกี่ยวข้องกัน

ตัวอย่างหนึ่งที่อาจทำให้เห็นภาพได้คือ การวิเคราะห์การมีส่วนร่วมในการเรียนของนักเรียนในโรงเรียน การวิเคราะห์แบบปกติ ผู้วิเคราะห์อาจดำเนินการเก็บรวบรวมข้อมูลเพื่อวัดระดับการมีส่วนร่วมของนักเรียนแต่ละคนโดยใช้แบบสอบถาม จากนั้นดำเนินการคำนวณคะแนนการมีส่วนร่วมของนักเรียนแต่ละคน และอาจนำคะแนนดังกล่าวไปวิเคราะห์ความสัมพันธ์กับผลสัมฤทธิ์ทางการเรียนของนักเรียน อย่างไรก็ตามการวิเคราะห์ลักษณะดังกล่าวอาจละเลยรายละเอียดที่สำคัญในบริบทของชั้นเรียนดังกล่าว ได้แก่

-   การมองข้ามปฏิสัมพันธ์ระหว่างบุคคล : การเรียนรู้และการมีส่วนร่วมของนักเรียนอาจได้รับอิทธิพลจากเพื่อนหรือครู แต่การวิเคราะห์แบบดั้งเดิมไม่ได้สะท้อนผลกระทบนี้อย่างครบถ้วน เช่น นักเรียนที่ผู้ในกลุ่มที่มีความกระตือรือร้นในการเรียนสูง มักมีแนวโน้มที่จะมีส่วนร่วมมากขึ้น การมองเห็นความสัมพันธ์ที่ซับซ้อนดังกล่าวทำให้ผู้วิเคราะห์สามารถเข้าใจได้ว่าการมีส่วนร่วมของนักเรียนแต่ละคนเกิดขึ้นอย่างไรในระดับกลุ่มหรือห้องเรียน ไม่ใช่แค่ระดับบุคคล นอกจากนี้การวิเคราะห์ได้ว่านักเรียนคนใดมีแนวโน้มเป็นผู้มีอิทธิพลสูงในชั้นเรียน ช่วยให้การออกแบบกิจกรรมกลุ่มที่ถจัดผู้เรียนลักษณะนี้เข้ากลุ่มอย่างเหมาะสม อาจเพิ่มโอกาสการมีส่วนร่วมของนักเรียนคนอื่น ๆ มากขึ้น

-   การละเลยโครงสร้างทางสังคมในห้องเรียน : ห้องเรียนแต่ละห้องมีสิ่งแวดล้อมและโครงสร้างทางสังคมที่ซับซ้อน เช่น นักเรียนบางคนอาจเป็นศูนย์กลางของกลุ่ม บางคนอาจอยู่ภายใต้เครือข่ายหลัก หรือเครือข่ายรอง ที่เป็นกลุ่มย่อย ๆ ในชั้นเรียน แต่บางคนอาจถูกแยกออกจากกลุ่มต่าง ๆ ในชั้นเรียน การที่สามารถระบุนักเรียนที่มีความเสี่ยงถูกแยกออกจากกลุ่มนี้ได้ ช่วยให้ครูผู้สอนสามารถออกแบบกิจกรรมหรือสิ่งสนับสนุนเพื่อช่วยให้นักเรียนดังกล่าวมีโอกาสที่จะมีส่วนร่วมในชั้นเรียนมากขึ้น

ปฏิสัมพันธ์ระหว่างนักเรียนแต่ละคนกับเพื่อน ครู และสภาพแวดล้อมที่สนับสนุนการเรียนรู้ของนักเรียนในชั้นเรียน รวมทั้งปัจจัยทางเศรษฐกิจและสังคมต่าง ๆ ที่อาจเป็นปัจจัยสนับสนุนหรืออุปสรรคต่อการมีส่วนร่วมของนักเรียน การวิเคราะห์เครือข่ายที่จะกล่าวถึงในรายวิชานี้มีแนวคิดและเทคนิคอีกชุดหนึ่งที่มีประสิทธิภาพสำหรับการสร้างโมเดลเพื่อบรรยายและวิเคราะห์ประเด็นดังกล่าวได้อย่างครอบคลุม

## ความหมายของเครือข่าย

**เครือข่าย (networks)** คือกลุ่มของสิ่งต่าง ๆ เรียกว่า **เอนทิตี (entities)** ที่มีความเชื่อมโยงหรือสัมพันธ์กัน ในบริบทของการวิเคราะห์เครือข่ายจะแทนเอนทิตีดังกล่าวด้วย **จุดยอด (vertices)** หรือ **โหนด (nodes)** โดยที่โหนดนี้อาจเป็นบุคคล (เช่น นักเรียน ครู ผู้ปกครอง) กลุ่มคน (เช่น ทีมงาน ฝ่าย) องค์กร (เช่น โรงเรียน หน่วยงาน ประเทศ) ไปจนถึงแนวคิด คำสำคัญ พฤติกรรม หรืออารมณ์/ความรู้สึก เอนทิตีแต่ละตัวสามารถมีคุณลักษณะ (attributes) ที่แตกต่างกัน เช่น ตัวแปรแบบจัดประเภท (categorical) เช่น เพศ หรือระดับชั้นของนักเรียน หรือ ตัวแปรเชิงต่อเนื่อง (continuous) เช่น อายุ

ภายในเครือข่ายจะแทนความสัมพันธ์ระหว่างโหนดด้วย **เส้นเชื่อม (edges)** ซึ่งสามารถมีคุณลักษณะที่แตกต่างกันได้ เช่นเดียวกับโหนด ตัวอย่างเช่น โหนด A คือนักเรียนชายคนที่หนึ่ง และโหนด B คือนักเรียนหญิงคนที่สอง ความสัมพันธ์ระหว่างนักเรียนทั้งสองคนนี้อาจเป็นเพื่อนร่วมห้อง ในขณะที่ความสัมพันธ์ระหว่างโหนด A และโหนด C (นักเรียนชายคนที่สาม) อาจเป็นสมาชิกในชมรมเดียวกัน จุดเด่นของการวิเคราะห์เครือข่ายคือ การวิเคราะห์ได้ทั้งความสัมพันธ์ทางตรงระหว่างโหนดที่เชื่อมต่อกันโดยตรง และความสัมพันธ์ทางอ้อม (indirect relationship) ตัวอย่างเช่น ความสัมพันธ์ระหว่างโหนด B และ C ที่เชื่อมโยงผ่านโหนด A

การวิเคราะห์เครือข่ายอาจจำแนกออกเป็น 3 ระดับ ได้แก่ ระดับคู่สัมพันธ์ (dyad level) ระดับโหนด (node level) และระดับเครือข่าย (network level)

-   **ระดับคู่สัมพันธ์ (dyad level)** เป็นการวิเคราะห์ไปที่หน่วยพื้นฐานของข้อมูลเครือข่าย กล่าวคือ**เป็นการวิเคราะห์ความสัมพันธ์ระหว่างแต่ละคู่ของโหนด** เพื่อทำความเข้าใจว่าความสัมพันธ์ของโหนดสองโหนดมีลักษณะอย่างไร

-   **ระดับโหนด (node level)** เป็นการวิเคราะห์เกี่ยวกับบุคคลหรือโหนดภายในเครือข่าย เพื่อทำความเข้าใจบทบาทและอิทธิพลของแต่ละโหนด เช่น ใครเป็นศูนย์กลางของเครือข่าย หรือ ใครมีความสัมพันธ์กับบุคคลอื่น ๆ ในเครือข่ายมากที่สุด

-   **ระดับเครือข่าย (network level)** เป็นการวิเคราะห์ภาพรวมของทั้งเครือข่าย เพื่อทำความเข้าใจคุณลักษณะของเครือข่ายโดยรวม เช่น ความหนาแน่น การแยกกลุ่ม และโครงสร้างของเครือข่าย

การวิเคราะห์แต่ละระดับไม่ได้แยกออกจากกันอย่างสิ้นเชิง แต่สามารถเชื่อมโยงและเสริมกันได้ กล่าวคือ การวิเคราะห์ในระดับคู่สัมพันธ์สามารถนำมาสรุปรวมกันเพื่อวิเคราะห์ในระดับโหนด และการวิเคราะห์ในระดับโหนดสามารถนำไปสังเคราะห์เพื่อทำความเข้าใจรูปแบบหรือสภาพของเครือข่าย เช่น

ระดับคู่สัมพันธ์ : นักเรียนที่ทำงานกลุ่มร่วมกันบ่อย มีผลสัมฤทธิ์สูงกว่าคู่ที่ไม่ได้ทำงานร่วมกันหรือไม่

ระดับโหนด : นักเรียนคนใดเป็นศูนย์กลางของเครือข่ายในห้องเรียน และมีบทบาทสำคัญในการช่วยเหลือเพื่อน

ระดับเครือข่าย : ห้องเรียนมีปฏิสัมพันธ์ระหว่างนักเรียนในระดับใด การมีปฏิสัมพันธ์อย่างทั่วถึงมีความสามัคคีและผลสัมฤทธิ์ทางการเรียนที่ดีกว่าหรือไม่

## ประเภทของความสัมพันธ์

ความสัมพันธ์ระหว่างโหนดมีได้หลายรูปแบบ โดยอาจจำแนกได้เป็นสองประเภทหลัก ได้แก่

1.  สถานะความสัมพันธ์ (relational states)
2.  เหตุการณ์เชิงความสัมพันธ์ (relational events)

### ความสัมพันธ์แบบสถานะความสัมพันธ์

ความสัมพันธ์ระหว่างโหนดลักษณะนี้เป็นความสัมพันธ์ที่คงอยู่อย่างต่อเนื่องในเครือข่าย และไม่ขึ้นอยู่กับเวลา โดยอาจจำแนกออกเป็น 3 ประเภทย่อยได้แก่ ความคล้ายคลึงกัน (similarity) ความสัมพันธ์เชิงบทบาท (relational roles) และความสัมพันธ์เชิงการรับรู้ (relational cognition) รายละเอียดมีดังนี้

**ความคล้ายคลึงกัน** เป็นความสัมพันธ์ระหว่างโหนดหรือโหนดในเชิงของคุณลักษณะที่เหมือนกันระหว่างโหนดในเครือข่าย โดยไม่จำเป็นที่โหนดดังกล่าวจะต้องมีปฏิสัมพันธ์กันโดยตรง ความคล้ายคลึงนี้อาจเป็นปัจจัยที่สร้างโอกาสให้เกิดการเชื่อมโยงหรือปฏิสัมพันธ์ต่อกันได้ในอนาคต ตัวอย่างของความคล้ายคลึงในเครือข่าย เช่น

-   คุณลักษณะทางกายภาพหรือภูมิหลัง เช่น เพศ อายุ เชื้อชาติ ศาสนา หรือ อาชีพ

-   ความคิดเห็นและค่านิยม เช่น การมีความคิดเห็นทางการเมืองเหมือนกัน หรือมีค่านิยมทางสังคมที่คล้ายกัน

-   ประสบการณ์ร่วม เช่น การสำเร็จการศึกษาจากโรงเรียนหรือมหาวิทยาลัยเดียวกัน เคยทำงานในบริษัทเดียวกัน ตำแหน่งงานคล้ายกัน หรือเข้าร่วมกิจกรรมทางสังคมเดียวกัน

-   ตำแหน่งที่ตั้ง เช่น เป็นคนพื้นที่เดียวกัน หรือทำงานที่เดียวกัน

ความสำคัญของความคล้ายคลึงในเครือข่าย

1.  เป็นพื้นฐานของการสร้างความสัมพันธ์ในอนาคต ทั้งนี้เพราะคนที่มีความคล้ายคลึงกันมักมีแนวโน้มที่จะมีปฏิสัมพันธ์กันมากกว่าคนที่มีความแตกต่างกัน
2.  ส่งเสริมการสื่อสารและความร่วมมือ กล่าวคือ ความคล้ายคลึงกันช่วยลดช่องว่างทางภูมิหลังของบุคคล เพิ่มความไว้วางใจ และทำให้การสื่อสาร ขอความร่วมมือ หรือการทำงานร่วมกันทำได้อย่างมีประสิทธิภาพมากขึ้น
3.  เสริมสร้างความเป็นกลุ่ม กล่าวคือ กลุ่มที่มีสมาชิกที่มีคุณลักษณะคล้ายกัน เครือข่ายมักจะมีความเข้มแข็งและเสถียรมากขึ้น บุคคลที่คล้ายกันมักให้ความช่วยเหลือและแบ่งปันข้อมูลซึ่งกันและกัน ส่งเสริมการไหลเวียนของข้อมูลและทำให้เครือข่ายสามารถพัฒนาได้อย่างต่อเนื่อง

**ความสัมพันธ์เชิงบทบาท** เป็นความสัมพันธ์ภายในเครือข่ายที่สะท้อนบทบาททางสังคมที่บุคคลมีต่อกันภายในเครือข่าย ความสัมพันธ์ประเภทนี้มีลักษณะต่อเนื่องและคงอยู่อย่างมั่นคง เช่น ความสัมพันธ์ระหว่างพ่อแม่-ลูก ครู-นักเรียน หัวหน้า-ลูกน้อง หรือเพื่อนร่วมงาน ลักษณะสำคัญของความสัมพันธ์เชิงบทบาทมีดังนี้

1.  มีโครงสร้างและบทบาทหน้าที่ชัดเจน เช่น นักเรียนมีหน้าที่เรียนรู้ ส่วนครูมีหน้าที่สอนและให้คำแนะนำ
2.  เกิดขึ้นอย่างเป็นระบบ กล่าวคือ บทบาทดังกล่าวมักมีการสืบทอดหรือถูกสร้างขึ้นจากบริบททางสังคม/วัฒนธรรม ตัวอย่าง พ่อแม่-ลูก หรือ ครู-นักเรียน เป็นตัวอย่างที่เห็นอย่างชัดเจน
3.  สะท้อนถึงความสัมพันธ์ที่ไม่สมมาตรหรือมีทิศทาง หลายกรณีความสัมพันธ์เชิงบทบาทมีลักษณะที่ไม่เท่าเทียมกัน เช่น แม่-ลูก หรือ หัวหน้า-ลูกน้อง โดยบุคคลที่มีบทบาทแตกต่างกันจะมีอำนาจหรือหน้าที่ที่แตกต่างไปจากอีกฝ่าย

**ความสัมพันธ์เชิงการรับรู้** เป็นความสัมพันธ์ในเชิงความคิดและความรู้สึกที่ผู้คนมีต่อกัน ซึ่งรวมถึงการรู้จักกัน ใครรู้จักใคร การรับรู้เชิงความสัมพันธ์เหล่านี้โดยพื้นฐานแล้วไม่สามารถสังเกตได้โดยสมาชิกคนอื่น ๆ ในเครือข่าย ยกเว้นจะมีการอนุมานจากปฏิสัมพันธ์ ตัวอย่างหนึ่งที่ชัดเจนของความสัมพันธ์เครือข่ายลักษณะนี้คือ ความไว้วางใจ (trust relation) ซึ่งเป็นปัจจัยที่ทำให้เกิดการร่วมมือหรือดำเนินการที่มีผลประโยชน์ต่อกัน

### เหตุการณ์เชิงความสัมพันธ์

หมายถึงเหตุการณ์ที่สะท้อนหรือสร้างความสัมพันธ์ระหว่างโหนด เป็นปฏิสัมพันธ์หรือกิจกรรมที่เกิดขึ้นระหว่างโหนด ในช่วงเวลาใดเวลาหนึ่ง ซึ่งสะท้อนถึงความสัมพันธ์ที่เกิดขึ้นชั่วคราว ไม่ต่อเนื่อง ทั้งนี้เป็นเพราะเหตุการณ์ดังกล่าวไม่ใช่สถานะที่คงอยู่อย่างยาวนาน แต่เป็นการกระทำหรือกิจกรรมที่มีผลต่อเครือข่ายและอาจนำไปสู่การสร้างความสัมพันธ์ในระยะยาว ลักษณะสำคัญของเหตุการณ์เชิงความสัมพันธ์ ได้แก่

1.  เป็นเหตุการณ์ที่เกิดขึ้นชั่วคราว เกิดขึ้นและสิ้นสุดในช่วงเวลาหนึ่ง ๆ และสามารถสังเกตได้ เช่น การส่ง email ระหว่างพนักงาน การติดต่อเพื่อซื่อขายสินค้า การทำงานกลุ่ม
2.  สะท้อนถึงการมีปฏิสัมพันธ์ในเครือข่าย
3.  เป็นพื้นฐานของการสร้างความสัมพันธ์ถาวร
4.  สะท้อนถึงความสัมพันธ์ที่ซ่อนอยู่ เช่น การส่ง email หรือ พิมพ์ข้อความผ่าน chat ส่วนตัว สามารถแสดงให้เห็นถึงการเชื่อมต่อหรือแลกเปลี่ยนข้อมูลที่มองไม่เห็น
5.  ช่วยในการวิเคราะห์เครือข่ายแบบ dynamic กล่าวคือ เหตุการณ์ที่เกิดขึ้นสามารถใช้อธิบายหรือช่วยในการวิเคราะห์การเปลี่ยนแปลงของเครือข่ายในช่วงเวลาต่าง ๆ

เหตุการณ์เชิงความสัมพันธ์อาจจำแนกเป็น 2 ประเภท ได้แก่

1.  **ปฏิสัมพันธ์ (interactions)** เป็นกิจกรรมหรือพฤติกรรมที่เกิดขึ้นระหว่างโหนดโดยตรงและสามารถสังเกตได้ เช่น การประชุม การทำงานร่วมกันในโครงการ การพูดคุยหรือแลกเปลี่ยนความคิดเห็น การซื้อขายสินค้า
2.  **การไหล (flows)** หมายถึงการส่งผ่านข้อมูล ทรัพยากร หรือแนวคิด จากโหนดหนึ่งไปยังอีกโหนดหนึ่ง ซึ่งสามารถเกิดขึ้นได้โดยไม่จำเป็นต้องมีปฏิสัมพันธ์โดยตรงระหว่างบุคคล เช่น การส่ง email การถ่ายทอดข่าวสาร การส่งต่อไฟล์ การโอนเงิน

การเก็บรวบรวมข้อมูลเหตุการณ์เชิงความสัมพันธ์ เช่น การถามตอบกระทู้เกี่ยวกับการบ้านของนักเรียน ผู้วิเคราะห์จำเป็นต้องจัดกระทำข้อมูลเหตุการณ์นี้โดยอาจใช้การนับจำนวนครั้งที่เกิดการถามตอบกระทู้ระหว่างนักเรียนดังกล่าวภายใต้ช่วงเวลาที่ทำการศึกษา

## วัตถุประสงค์ของการวิเคราะห์เครือข่าย

วัตถุประสงค์ของการวิเคราะห์เครือข่ายอาจจำแนกได้เป็น 2 ประเภท ได้แก่ การวิเคราะห์เชิงบรรยาย (descriptive) และการวิเคราะห์เชิงอธิบาย (explanatory) รายละเอียดมีดังนี้

### การวิเคราะห์เชิงบรรยาย (descriptive)

การวิเคราะห์ประเภทนี้เน้นการคำนวณตัวชี้วัดของเครือข่ายหลายตัว เพื่อบรรยายหรือทำความเข้าใจลักษณะโครงสร้างของเครือข่าย หรือสะท้อน หรือลักษณะของโหนดหรือบุคคลแต่ละคนในเครือข่าย ผลการวิเคราะห์ที่ได้จากตัวชี้วัดต่าง ๆ จะถูกแปลความหมายและนำไปประยุกต์ใช้โดยตรง เช่น

-   การอบรมพัฒนาครูที่มีค่าใช้จ่ายในการอบรมสูง อาจใช้การวิเคราะห์ความเป็นศูนย์กลาง (centrality) เพื่อค้นหาครูแม่ข่ายและดำเนินการอบรมกับครูกลุ่มนี้ก่อน โดยคาดหวังว่าครูที่ได้รับการอบรมจะนำแนวคิดและแนวปฏิบัติไปเผยแพร่ต่อในเครือข่าย

-   การพัฒนาการเรียนรู้ของนักเรียนในบางมิติ อาจใช้การวิเคราะห์เครือข่ายเพื่อระบุนักเรียนที่ไม่สามารถทำงานร่วมกับเพื่อนได้ หรือถูกแยกออกจากกลุ่มเพื่อน เพื่อออกแบบการสนับสนุนและปรับปรุงพฤติกรรมการเรียนรู้ของนักเรียน

การวิเคราะห์เชิงบรรยาย ส่วนใหญ่เป็นการวิเคราะห์แบบตัวแปรเดียว (univariate analysis) โดยเน้นการคำนวณตัวชี้วัดของเครือข่าย เช่น ความเป็นศูนย์กลางของโหนด (centrality) ความเหนียวแน่นของกลุ่ม (group's cohesion) สารสนเทศที่ได้จะใช้สนับสนุนการออกแบบ/ตัดสินใจหรือดำเนินการแทรกแซงที่เหมาะสม ทั้งนี้การดำเนินการดังกล่าวควรจะต้องใช้องค์ความรู้/ทฤษฎีจากงานวิจัยที่เกี่่ยวข้อง หรืออย่างน้อยก็ควรมีหลักเหตุผลที่แสดงให้เห็นว่าค่าที่คำนวณได้จากตัวชี้วัดต่าง ๆ น่าจะมีความสัมพันธ์เชิงบวกหรือเชิงลบกับตัวแปรตาม (ผลลัพธ์ที่ต้องการ) อย่างไร ยกตัวอย่างเช่น

-   ในกรณีของการระบุครูแม่ข่าย เนื่องจากงานวิจัยหรือผลการดำเนินงานจากโครงการที่ผ่านมาพบว่าการให้ความรู้แก่ครูกลุ่มนี้จะช่วยให้เกิดการแนะนำและเผยแพร่ความรู้ไปยังครูในเครือข่ายคนอื่น ๆ ได้อย่างมีประสิทธิภาพและลดต้นทุนการฝึกอบรมได้มากกว่า จะเห็นว่าการดำเนินการนี้สามารถทำได้เพราะมีทฤษฎีที่กล่าวถึงความสัมพันธ์หรือความสัมพันธ์เชิงสาเหตุระหว่างการเป็นครูแม่ข่ายกับประสิทธิภาพของการเผยแพร่ความรู้แล้ว สิ่งที่ผู้วิจัยต้องดำเนินการจึงเป็นเพียงแค่วัดค่ของตัวแปรอิสระ เช่น ความเป็นศูนย์กลางของครู เพื่อสะท้อนศักยภาพความเป็นครูแม่ข่าย

-   ในการจัดการเรียนรู้บางกรณี ครูผู้สอนอาจต้องการลดระดับความเป็นศูนย์กลางในเครือข่ายของนักเรียนในแต่ละกลุ่ม เนื่องจากงานวิจัยก่อนหน้าบ่งชี้ว่ากลุ่มหรือทีมที่มีโครงสร้างแบบกระจายอำนาจ (decentralized) มีแนวโน้มจะสร้างงานสร้างสรรค์ได้มากกว่า

### การวิเคราะห์เชิงอธิบาย

ในทางกลับกันการวิเคราะห์เชิงอธิบายมักเป็นการวิเคราะห์แบบหลายตัวแปร (multivariate analysis) และเกี่ยวข้องกับการวิเคราะห์ความสัมพันธ์ โดยพยายามอธิบายความแปรปรวนร่วมของตัวแปรหลายตัว หรืออธิบายความแปรปรวนของตัวแปรตามโดยใช้ตัวแปรอิสระอื่น ๆ ที่เกี่ยวข้อง การวิเคราะห์ลักษณะนี้มักพบได้บ่อยในงานเชิงวิชาการ เช่น

-   ผู้วิเคราะห์อาจคำนวณตัวชี้วัดเกี่ยวกับความเป็นศูนย์กลางของนักเรียนแต่ละคนในเครือข่าย แล้วใช้ค่าดังกล่าวทำนายความเสี่ยงทางด้านอารมณ์/สังคมของนักเรียน ตัวอย่างการวิจัยลักษณะนี้มักเน้นการสร้างทฤษฎีเครือข่าย ซึ่งมักตั้งชื่องานวิจัยในลักษณะ "เครือข่ายของ XXX" โดยที่ XXX คือตัวแปรตาม ในที่นี้คือ ทฤษฎีเครือข่ายความเสี่ยงด้านอารมณ์/สังคมของนักเรียน

-   อีกลักษณะหนึ่งคือการใช้ตัวแปรเครือข่ายเป็นตัวแปรตาม กล่าวคือผู้วิเคราะห์อาจใช้ความคล้ายคลึงกันของนักเรียนในเชิงทัศนคติและพฤติกรรมในการเรียน เพื่อทำนายว่านักเรียนคนใดน่าจะเป็นเพื่อนกับใคร การศึกษาวิจัยในลักษณะนี้มักเน้นสร้างทฤษฎีเครือข่าย XXX โดยที่ XXX เป็นตัวแปรอิสระ ซึ่งในที่นี้อาจตั้งชื่อเป็นเครือข่ายของความสนใจร่วมกัน

ทั้งนี้ไม่ว่าในการวิเคราะห์เราจะใช้ตัวแปรเครือข่ายเป็นตัวแปรอิสระหรือตัวแปรตาม ตัวแปรดังกล่าวสามารถอยู่ในระดับใดหนึ่งในสามระดับของการวิเคราะห์ก็ได้

## ตัวแปรเครือข่ายที่เป็นตัวแปรอิสระ

การใช้ตัวแปรเครือข่ายเป็นตัวแปรอิสระ หมายถึง การนำตัวชี้วัดของเครือข่ายที่อาจเกี่ยวข้องกับโครงสร้างความสัมพันธ์ หรือบทบาทของโหนด หรือคุณลักษณะของเครือข่าย (แล้วแต่ว่าเป็นการวิเคราะห์ในระดับใด) มาใช้เป็นตัวแปรอิสระเพื่ออธิบายหรือทำนายตัวแปรตาม (ผลลัพธ์ที่สนใจ)

-   มิตรภาพระหว่างนักเรียนสองคนอธิบายการช่วยกันทำการบ้าน

-   นักเรียนที่เป็นศูนย์กลางของเครือข่าย ทำนายว่า จะเป็นหัวหน้ากลุ่มที่ดีหรือไม่

-   เครือข่ายที่มีการสื่อสารอย่างหนาแน่น จะสามารถแก้ปัญหาได้อย่างมีประสิทธิภาพหรือไม่

จากตัวอย่างข้างต้นจะเห็นว่า เมื่อการวิจัยใช้ตัวแปรเครือข่ายเป็นตัวแปรอิสระ วัตถุประสงค์หลักของงานคือการสร้างทฤษฎีที่ใช้อธิบายเกี่ยวกับผลของคุณลักษณะของเครือข่ายที่มีต่อตัวแปรตามที่สนใจ ดังนั้นสมมุติฐานของการวิจัยประเภทนี้จะเกี่ยวข้องกับการทำนายหรืออธิบายผลของตัวแปรอิสระ (ตัวแปรเครือข่าย) ที่มีต่อตัวแปรตาม จะเห็นว่าผลการวิเคราะห์ที่ได้จะให้คำตอบที่นำไปสู่การออกแบบสิ่งสนับสนุนหรือกลยุทธ์ที่เหมาะสมสำหรับปรับเปลี่ยนคุณลักษณะของเครือข่ายเพื่อให้เกิดผลลัพธ์ที่มุ่งหวัง

ทฤษฎีเครือข่ายที่สร้างขึ้นในลักษณะนี้ส่วนใหญ่มักเป็นทฤษฎีที่มีมุมมองพื้นฐานว่า ความสัมพันธ์ภายในเครือข่ายเป็นเส้นทางที่สิ่งต่าง ๆ เช่น แนวคิด ข้อมูล/ข่าวสาร ความรู้ ทรัพยากร หรือโรค ถูกส่งหรือไหลผ่านไปยังบุคคลหรือสิ่งต่าง ๆ ในเครือข่าย ภายใต้แนวคิดพื้นฐานนี้มีหลายกลไกที่ถูกพัฒนาขึ้นเพื่ออธิบายการไหลดังกล่าวกับผลลัพธ์ที่คาดหวัง โดยอาจจำแนกแนวคิดดังกล่าวออกเป็นประเภทตามลักษณะของตัวแปรตามที่สนใจศึกษาดังนี้

### Social Capital

เป็นกลุ่มงานวิจัยที่ศึกษาผลของตัวแปรเครือข่ายที่มีต่อตัวแปรตามประเภท ความสำเร็จ ผลงาน หรือประโยชน์ทั้งในระดับโหนดรายบุคคลหรือเครือข่ายโดยรวม ตัวอย่างหนึ่งคือ ทฤษฎีทรัพยากรทางสังคม (Lin, 2001) ที่เสนอว่า ความสำเร็จของบุคคลแต่ละบุคคลนั้น ส่วนหนึ่งเป็นผลมาจากทรัพยากรที่เครือข่ายทางสังคมของบุคคลนั้นทำให้เข้าถึงได้ ดังนั้นบุคคลที่มีความเชื่อมโยงกับผู้ที่ควบคุมทรัพยากรสำคัญหลาย ๆ ประเภท เช่น เงิน อำนาจ และความรู้ มีแนวโน้มที่จะมีโอกาสประสบความสำเร็จมากกว่าคนที่มีทรัพยากรของตนเองเพียงอย่างเดียว จะเห็นว่าทฤษฎีนี้มีจุดสำคัญอยู่ที่การไหลเข้าของทรัพยากรที่หลากหลายที่เครือข่ายความสัมพันธ์ของบุคคลนั้น ๆ ทำให้หรือสามารถเข้าถึงได้

### Arbitrage Theory

ที่ระบุว่าโหนด $j$ สามารถได้รับผลประโยชน์ หากสามารถทำให้เกิดความสัมพันธ์ระหว่าง $i$ กับ $k$ ขึ้นได้ โดยที่ $i$ และ $k$ เป็นโหนดที่มีเป้าหมายความสำเร็จเดียวกัน แต่มีผลการดำเนินงานที่แตกต่างกัน เช่น หาก $i$ บรรลุความสำเร็จหรือแก้ปัญหาใดปัญหาหนึ่งได้แล้ว ในขณะที่ $k$ ยังทำไม่ได้ $j$ สามารถนำวิธีดำเนินงานของ $i$ ไปบอกกับ $k$ โดยแลกเปลี่ยนค่าตอบแทนหรือผลประโยชน์จาก $k$ จะเห็นว่าผลประโยชน์ของ $j$ เกิดขึ้นจากการไหลเข้าออกของทรัพยากร (สังเกตว่า $j$ อยู่ในตำแหน่งตรงกลางระหว่าง $i$ กับ $k$ )

### Auctioning

ในกรณีที่ $j$ มีสิ่งที่ทั้ง $i$ และ $k$ ต้องการ $j$ สามารถทำให้ทั้งสองฝ่ายแข่งขันกันเพื่อเพิ่มราคา หรือดึงผลประโยชน์จากแต่ละฝ่ายได้ กรณีนี้เกิดจากความเป็นไปได้ในการส่งต่อทรัพยากรจาก $j$ ไปยังเครือข่ายที่เชื่อมต่อกัน ดังนั้นโครงสร้างของเครือข่ายและตำแหน่งที่โหนดแต่ละตัวอยู่ในเครือข่ายจึงเป็นปัจจัยสำคัญในการทำนายผลลัพธ์ สังเกตว่า $j$ อยู่ในตำแหน่งตรงกลางระหว่าง $i$ กับ $k$ อีกแล้ว)

### Style

รูปแบบเป็นผลลัพธ์หรือตัวแปรตามที่มีลักษณะแบบจัดประเภทที่เกี่ยวข้องกับทางเลือก (choices) เช่น มุมมองทางการเมือง การตัดสินใจใช้นวัตกรรม การเลือกซื้อสินค้า การเลือกแผนการเรียน ผลลัพธ์ดังกล่าวนี้มักถูกอธิบายในมุมมองระดับคู่สัมพันธ์ (dyadic terms) ดังนั้นสิ่งที่ผู้วิเคราะห์พยายามจะอธิบายคือ ทำไมบุคคลสองคนจึงมีมุมมองทางการเมืองต่างกัน ทำไมคนนึงถึงเลือกใช้ chatgpt แต่อีกคนเลือกใช้ gemini หรือ ทำไมนักเรียนสองคนถึงเลือกเรียนแผนการเรียนเดียวกัน คำอธิบายหรือคำตอบที่ได้จากการวิเคราะห์ลักษณะนี้เป็นคำอธิบายในลักษณะของอิทธิพลของการแพร่กระจาย หรือการติดต่อทางสังคมผ่านการมีปฏิสัมพันธ์ระหว่างบุคคลจนเกิดเป็นมุมมองหรือการรับรู้ข้อมูลที่คล้ายคลึงกัน

## ตัวแปรเครือข่ายที่เป็นตัวแปรตาม

การวิจัยที่ตัวแปรตามเป็นตัวแปรเครือข่ายมักเน้นการสร้างคำอธิบายว่ามีปัจจัยอะไรบ้างที่นำไปสู่การเกิดเครือข่ายที่มีคุณลักษณะตามที่คาดหวัง การอธิบายคุณลักษณะของเครือข่ายดังกล่าวอาจเป็นไปได้ทั้งในระดับคู่สัมพันธ์ โหนด หรือเครือข่ายโดยรวม อย่างไรก็ตามงานวิจัยลักษณะนี้อาจจะไม่ใช้คำว่าเครือข่ายอยู่ในงานวิจัยก็ได้ ตัวอย่างงานวิจัยในลักษณะนี้ เช่น

แนวคิด Homophily ที่อธิบายถึงแนวโน้มของบุคคลที่จะมีความสัมพันธ์เชิงบวกกับบุคคลที่มีลักษณะคล้ายคลึงกับตนเองในแง่ของคุณลักษณะที่สำคัญทางสังคม เช่น เพศ เชื้อชาติ ศาสนา ชาติพันธุ์ และชนชั้น การวิเคราะห์ข้อมูลในการวิจัยลักษณะนี้อาจใช้การวิเคราะห์การถดถอย logistic ที่มีหน่วยการวิเคราะห์คือคู่สัมพันธ์ (dyads) และตัวแปรตามเป็นแบบ binary ที่มีค่าเป็น 1 เมื่อโหนดทั้งสองมีความสัมพันธ์เชิงบวก และ 0 เมื่อมีความสัมพันธ์เชิงลบ ส่วนตัวแปรอิสระอาจเป็น เพศ เชื้อชาติ หรืออื่น ๆ ตามแนวคิด Homophily ความสัมพันธ์ระหว่างปัจจัยทางสังคมส่วนใหญ่จะมีความสัมพันธ์เชิงบวกกับตัวแปรตามดังกล่าว

มีข้อสังเกตว่าการมีความสัมพันธ์เชิงบวกกับบุคคลที่คล้ายกับตนเองอาจไม่ใช่เป็นเพราะความชอบส่วนตัวแต่เพียงอย่างเดียว แต่อาจสะท้อนการความพร้อมของคู่สัมพันธ์ที่เหมาะสม เช่น หากคนส่วนใหญ่ในองค์กรเป็นผู้หญิงเราคาดว่าผู้หญิงเหล่านั้นจะมีเพื่อนร่วมงานที่เป็นผู้หญิงด้วยเนื่องจากความพร้อมของคู่สัมพันธ์ในสัดส่วนที่สูง ในขณะเดียวกันผู้ชายในองค์กรส่วนใหญ่จะมีเพื่อนผู้หญิงจำนวนมากพอสมควร เนื่องจากความพร้อมของคู่สัมพันธ์เช่นกัน จากสภาพบริบทองค์กรดังกล่าวเราจึงไม่ควรสรุปว่าผู้หญิงมีแนวโน้ม homophily ส่วนผู้ชายมีแนวโน้ม heterophily

ตัวอย่างข้างต้นแสดงให้เห็นว่ามีปัจจัยพื้นฐานในการสร้างความสัมพันธ์ภายในเครือข่ายอยู่สองประเภท ได้แก่ **โอกาส (opportunity)** และ **ความชอบหรือความสนใจหรือคุณลักษณะที่เหมือนกันส่วนบุคคล (perference)** ทั้งสองปัจจัยมักมีความเกี่ยวข้องกันอย่างใกล้ชิด

-   ตัวอย่างหนึ่งกลไกความสัมพันธ์ที่ขับเคลื่อนด้วยโอกาส คือผลการวิจัยที่พบว่า ความสัมพันธ์หนึ่งนำไปสู่หรือก่อให้เกิดความสัมพันธ์อีกรูปแบบหนึ่ง ยกตัวอย่างเช่น นักเรียนสองคนถูกจับให้นั่งข้างกันอาจนำไปสู่การเป็นเพื่อนสนิทกัน นำไปสู่การมีปฏิสัมพันธ์หรือการช่วยให้การไหลเวียนของทรัพยากรต่าง ๆ ดีขึ้น

-   ตัวอย่างของกลไกที่ขับเคลื่อนด้วยความชอบส่วนบุคคลคือ ทฤษฎีสมดุล (balance theory) ที่กล่าวว่า บุคคลจะพยายามสร้างความสอดคล้องกับผู้ที่ตนชอบ ดังนั้นหาก A ชอบ B และ B ชอบ C อาจทำให้เกิดความขัดแย้งระหว่าง A กับ B หรือ A ไม่ชอบ C ตามทฤษฎีสมดุลจะทำให้คาดได้ว่า A จะต้องชอบ C เพิ่มขึ้น หรือในทางกลับกัน A อาจจะชอบ B ลดลง
