project:
  type: book

book:
  title: "R_book_update"
  author: "สิวะโชติ ศรีสุทธิยากร"
  date: "8/12/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - basicR.qmd
    - summary.qmd
    - references.qmd
  sidebar:
    style: docked
    background: light
  cover-image: cover2.png
  cover-image-alt: |
    Alternative text describing the book cover

comments:
  hypothesis: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true  # เปิดใช้งานสารบัญ
    toc-title: "สารบัญ"
    number-sections: false
    number-depth: 4
  pdf:
    latex-engine: xelatex
    documentclass: book
    mainfont: "TH Sarabun New"
    papersize: a4
    header-includes:
      - \XeTeXlinebreaklocale "th"
      - \XeTeXlinebreakskip = 0pt plus 0pt 
      - \usepackage{fontspec}
      - \defaultfontfeatures{Mapping=tex-text} 
      - \newfontfamily{\thaifont}[Mapping=textext]{TH Sarabun New}
      - \newenvironment{thailang}{\thaifont}{}
      - \usepackage[Latin,Thai]{ucharclasses}
      - \setTransitionTo{Thai}{\begin{thailang}}
      - \setTransitionFrom{Thai}{\end{thailang}}
      - \renewcommand{\baselinestretch}{1.0}
      - \usepackage{polyglossia}
      - \setdefaultlanguage{english}      
      - \setotherlanguages{thai}
      - \AtBeginDocument\captionsthai

editor: visual

