{
  "hash": "8fff04345570e9d0ad236661a7008caa",
  "result": {
    "markdown": "---\ntitle: \"Hypothetical Model\"\n---\n\n\nขอให้นิสิตใช้ไฟล์ข้อมูล hsb.sav และ hsb2.sav สำหรับวิเคราะห์เพื่อตอบคำถามวิจัยต่อไปนี้\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nhsb2<-read_spss(\"/Users/siwachoat/Library/CloudStorage/OneDrive-ChulalongkornUniversity/Documents/MSEM/MSEM/datasets/hsb2.sav\")\nglimpse(hsb2, width=80)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 160\nColumns: 7\n$ schoolid <dbl> 1224, 1288, 1296, 1308, 1317, 1358, 1374, 1433, 1436, 1461, 1…\n$ size     <dbl> 842, 1855, 1719, 716, 455, 1430, 2400, 899, 185, 1672, 530, 5…\n$ sector   <dbl> 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1…\n$ pracad   <dbl> 0.35, 0.27, 0.32, 0.96, 0.95, 0.25, 0.50, 0.96, 1.00, 0.78, 0…\n$ disclim  <dbl> 1.597, 0.174, -0.137, -0.622, -1.694, 1.535, 2.016, -0.321, -…\n$ himnty   <dbl> 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1…\n$ meanses  <dbl> -0.428, 0.128, -0.420, 0.534, 0.351, -0.014, -0.007, 0.718, 0…\n```\n:::\n:::\n\n\n## คำอธิบายข้อมูล\n\n-   size คือ จำนวนนักเรียนภายในโรงเรียน\n\n-   sector คือ ประเภทของโรงเรียน (เหมือน hsb.sav)\n\n-   pracad คือ สัดส่วนของนักเรียนในโรงเรียนที่เรียนสายสามัญ\n\n-   disclim คือ คะแนนบรรยากาศความมีวิจัยในโรงเรียน\n\n-   himnty คือ ตัวแปรดัมมี่ (1 = มีชนกลุ่มน้อยในโรงเรียนมากกว่าร้อยละ 40, 0 = น้อยกว่าร้อยละ 40)\n\n-   meanses คือ ค่าเฉลี่ยของคะแนนเศรษฐานะระดับโรงเรียน\n\n## คำถามวิจัย\n\n1.  ผลสัมฤทธิ์ทางการเรียนโดยเฉลี่ยระดับโรงเรียนมีความแตกต่างกันระหว่างสังกัด (sector) อย่างไร\n2.  อิทธิพลของเศรษฐานะของครอบครัวนักเรียนที่มีต่อผลสัมฤทธิ์ทางการเรียนวิชาคณิตศาสตร์ของนักเรียน มีความแตกต่างกันอย่างไร ตามประเภทของโรงเรียน (sector) และสัดส่วนชนกลุ่มน้อยในโรงเรียน (himnty)\n\n## modelling\n\nstudent-level model\n\n$mathach_{ij} = \\beta_{0j} + \\beta_{1j}SES_{ij} + e_{ij}$\n\nschool-level model\n\n$\\beta_{0j} = \\gamma_{00} + \\gamma_{01}Sector_j + u_{0j}$\n\n$\\beta_{1j} = \\gamma_{10} + \\gamma_{11}Sector_j + \\gamma_{12}Himnty_j + u_{1j}$\n\nCombined-model\n\n$mathach_{ij} = \\gamma_{00} + \\gamma_{01}Sector_j + u_{0j} + ( \\gamma_{10} + \\gamma_{11}Sector_j + \\gamma_{12}Himnty_j + u_{1j})SES_{ij} + e_{ij}$\n\n$mathach_{ij} = \\gamma_{00} + \\gamma_{01}Sector_j + u_{0j} + \\gamma_{10}SES_{ij} + \\gamma_{11}Sector_jSES_{ij} + \\gamma_{12}Himnty_jSES_{ij} + u_{1j}SES_{ij} + e_{ij}$\n\n$mathach_{ij} = \\gamma_{00} + \\gamma_{01}Sector_j + \\gamma_{10}SES_{ij} + \\gamma_{11}Sector_jSES_{ij} + \\gamma_{12}Himnty_jSES_{ij} + u_{0j}+u_{1j}SES_{ij} + e_{ij}$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(haven)\n# student level data\ndat<-read_spss(\"datasets/HSB.SAV\")\nglimpse(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 7,185\nColumns: 4\n$ schid   <chr> \"1224\", \"1224\", \"1224\", \"1224\", \"1224\", \"1224\", \"1224\", \"1224\"…\n$ sector  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ ses     <dbl> -1.528, -0.588, -0.528, -0.668, -0.158, 0.022, -0.618, -0.998,…\n$ mathach <dbl> 5.876, 19.708, 20.349, 8.781, 17.898, 4.583, -2.832, 0.523, 1.…\n```\n:::\n\n```{.r .cell-code}\nsummary(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    schid               sector            ses               mathach      \n Length:7185        Min.   :0.0000   Min.   :-3.758000   Min.   :-2.832  \n Class :character   1st Qu.:0.0000   1st Qu.:-0.538000   1st Qu.: 7.275  \n Mode  :character   Median :0.0000   Median : 0.002000   Median :13.131  \n                    Mean   :0.4931   Mean   : 0.000143   Mean   :12.748  \n                    3rd Qu.:1.0000   3rd Qu.: 0.602000   3rd Qu.:18.317  \n                    Max.   :1.0000   Max.   : 2.692000   Max.   :24.993  \n```\n:::\n\n```{.r .cell-code}\n# school level data\ndat2<-read_spss(\"/Users/siwachoat/Library/CloudStorage/OneDrive-ChulalongkornUniversity/Documents/MSEM/MSEM/datasets/hsb2.sav\")\nhead(dat2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n  schoolid  size sector pracad disclim himnty meanses\n     <dbl> <dbl>  <dbl>  <dbl>   <dbl>  <dbl>   <dbl>\n1     1224   842      0   0.35   1.60       0  -0.428\n2     1288  1855      0   0.27   0.174      0   0.128\n3     1296  1719      0   0.32  -0.137      1  -0.42 \n4     1308   716      1   0.96  -0.622      0   0.534\n5     1317   455      1   0.95  -1.69       1   0.351\n6     1358  1430      0   0.25   1.54       0  -0.014\n```\n:::\n\n```{.r .cell-code}\n## merging data\nmerge.dat <- merge(dat, dat2, by.x = \"schid\", by.y =\"schoolid\")\nhead(merge.dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  schid sector.x    ses mathach size sector.y pracad disclim himnty meanses\n1  1224        0 -1.528   5.876  842        0   0.35   1.597      0  -0.428\n2  1224        0 -0.588  19.708  842        0   0.35   1.597      0  -0.428\n3  1224        0 -0.528  20.349  842        0   0.35   1.597      0  -0.428\n4  1224        0 -0.668   8.781  842        0   0.35   1.597      0  -0.428\n5  1224        0 -0.158  17.898  842        0   0.35   1.597      0  -0.428\n6  1224        0  0.022   4.583  842        0   0.35   1.597      0  -0.428\n```\n:::\n\n```{.r .cell-code}\nmerge.dat <- merge.dat %>%\n  select(-sector.x)\n\nnames(merge.dat)[5]<-\"sector\"\n\n# modeling\nlibrary(lme4)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: Matrix\n```\n:::\n\n```{.r .cell-code}\nfit<-lmer(mathach ~ 1+sector+ses+sector*ses+himnty*ses + (1 + ses | schid), \n          data= merge.dat)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in checkConv(attr(opt, \"derivs\"), opt$par, ctrl = control$checkConv, :\nModel failed to converge with max|grad| = 0.00428662 (tol = 0.002, component 1)\n```\n:::\n\n```{.r .cell-code}\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML ['lmerMod']\nFormula: mathach ~ 1 + sector + ses + sector * ses + himnty * ses + (1 +  \n    ses | schid)\n   Data: merge.dat\n\nREML criterion at convergence: 46541.2\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-3.10322 -0.72947  0.01724  0.75783  2.99649 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr\n schid    (Intercept)  3.07538 1.7537       \n          ses          0.04075 0.2019   1.00\n Residual             36.78875 6.0654       \nNumber of obs: 7185, groups:  schid, 160\n\nFixed effects:\n            Estimate Std. Error t value\n(Intercept)  12.2300     0.2307  53.007\nsector        2.2349     0.3179   7.030\nses           3.0640     0.1571  19.507\nhimnty       -1.9782     0.3570  -5.541\nsector:ses   -1.2706     0.2128  -5.971\nses:himnty   -0.5387     0.2289  -2.353\n\nCorrelation of Fixed Effects:\n           (Intr) sector ses    himnty sctr:s\nsector     -0.595                            \nses         0.161 -0.136                     \nhimnty     -0.376 -0.064 -0.012              \nsector:ses -0.135  0.127 -0.580 -0.024       \nses:himnty -0.018 -0.020 -0.428  0.249 -0.041\noptimizer (nloptwrap) convergence code: 0 (OK)\nModel failed to converge with max|grad| = 0.00428662 (tol = 0.002, component 1)\n```\n:::\n:::\n\n\n![](images/image-984491753.png){width=\"255\"}\n\n$\\gamma_{00} = 12.23$ คือ ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลาง ในโรงเรียนรัฐ\n\nค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลางในโรงเรียน car เท่ากับ 12.23 + 2.2349 $=\\gamma_{00} + \\gamma_{01}(1)$\n\n$\\beta_{1j}$ คืออัตราการเปลี่ยนของ mathach เมื่อเทียบกับ ses ของโรงเรียนที่ j\n\n$\\gamma_{10} = 3.06$ คือ ค่าเฉลี่ยของอัตราการเปลี่ยนของ mathach เมื่อเทียบกับ ses ของนักเรียนในโรงเรียนรัฐที่มีนักเรียนต่างชาติเป็นส่วนน้อย\n\nค่าเฉลี่ยของอัตราการเปลี่ยนของ mathach เมื่อเทียบกับ ses ของนักเรียนในโรงเรียน car เท่ากับ 3.06 - 1.27 = 1.79 เมื่อควบคุมให้ปัจจัยจำนวนนักเรียนต่างชาติในโรงเรียนคงที่\n\n$\\beta_{0j}$ คือค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลางในโรงเรียน j\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lmerTest)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'lmerTest'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:lme4':\n\n    lmer\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:stats':\n\n    step\n```\n:::\n\n```{.r .cell-code}\ncoef(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$schid\n     (Intercept)   sector      ses    himnty sector:ses ses:himnty\n1224   11.241236 2.234865 2.950165 -1.978184  -1.270557  -0.538727\n1288   12.845183 2.234865 3.134783 -1.978184  -1.270557  -0.538727\n1296   10.906321 2.234865 2.911614 -1.978184  -1.270557  -0.538727\n1308   12.724127 2.234865 3.120848 -1.978184  -1.270557  -0.538727\n1317   12.431322 2.234865 3.087147 -1.978184  -1.270557  -0.538727\n1358   11.612052 2.234865 2.992851 -1.978184  -1.270557  -0.538727\n1374   10.540892 2.234865 2.869557 -1.978184  -1.270557  -0.538727\n1433   15.068397 2.234865 3.390681 -1.978184  -1.270557  -0.538727\n1436   14.216680 2.234865 3.292645 -1.978184  -1.270557  -0.538727\n1461   14.128594 2.234865 3.282513 -1.978184  -1.270557  -0.538727\n1462   11.159206 2.234865 2.940720 -1.978184  -1.270557  -0.538727\n1477   11.775880 2.234865 3.011702 -1.978184  -1.270557  -0.538727\n1499   11.100892 2.234865 2.934018 -1.978184  -1.270557  -0.538727\n1637   11.232796 2.234865 2.949197 -1.978184  -1.270557  -0.538727\n1906   12.711631 2.234865 3.119412 -1.978184  -1.270557  -0.538727\n1909   13.210379 2.234865 3.176817 -1.978184  -1.270557  -0.538727\n1942   14.761318 2.234865 3.355332 -1.978184  -1.270557  -0.538727\n1946   12.758830 2.234865 3.124844 -1.978184  -1.270557  -0.538727\n2030   11.267216 2.234865 2.953151 -1.978184  -1.270557  -0.538727\n2208   12.401674 2.234865 3.083736 -1.978184  -1.270557  -0.538727\n2277   10.102000 2.234865 2.819029 -1.978184  -1.270557  -0.538727\n2305   11.636863 2.234865 2.995695 -1.978184  -1.270557  -0.538727\n2336   14.451603 2.234865 3.319682 -1.978184  -1.270557  -0.538727\n2458   13.277136 2.234865 3.184507 -1.978184  -1.270557  -0.538727\n2467   11.341851 2.234865 2.961748 -1.978184  -1.270557  -0.538727\n2526   13.785120 2.234865 3.242966 -1.978184  -1.270557  -0.538727\n2626   13.297116 2.234865 3.186802 -1.978184  -1.270557  -0.538727\n2629   12.728091 2.234865 3.121299 -1.978184  -1.270557  -0.538727\n2639   11.115892 2.234865 2.935733 -1.978184  -1.270557  -0.538727\n2651   11.282684 2.234865 2.954940 -1.978184  -1.270557  -0.538727\n2655   15.630348 2.234865 3.455362 -1.978184  -1.270557  -0.538727\n2658   10.840484 2.234865 2.904040 -1.978184  -1.270557  -0.538727\n2755   12.965991 2.234865 3.148685 -1.978184  -1.270557  -0.538727\n2768   11.463639 2.234865 2.975766 -1.978184  -1.270557  -0.538727\n2771   12.810725 2.234865 3.130818 -1.978184  -1.270557  -0.538727\n2818   13.229949 2.234865 3.179069 -1.978184  -1.270557  -0.538727\n2917   11.904652 2.234865 3.026519 -1.978184  -1.270557  -0.538727\n2990   16.148529 2.234865 3.515006 -1.978184  -1.270557  -0.538727\n2995   10.696677 2.234865 2.887480 -1.978184  -1.270557  -0.538727\n3013   12.668131 2.234865 3.114405 -1.978184  -1.270557  -0.538727\n3020   11.832330 2.234865 3.018201 -1.978184  -1.270557  -0.538727\n3039   14.821412 2.234865 3.362253 -1.978184  -1.270557  -0.538727\n3088   12.255043 2.234865 3.066854 -1.978184  -1.270557  -0.538727\n3152   12.922423 2.234865 3.143671 -1.978184  -1.270557  -0.538727\n3332   12.331004 2.234865 3.075598 -1.978184  -1.270557  -0.538727\n3351   12.516525 2.234865 3.096953 -1.978184  -1.270557  -0.538727\n3377   12.412745 2.234865 3.084998 -1.978184  -1.270557  -0.538727\n3427   16.081490 2.234865 3.507280 -1.978184  -1.270557  -0.538727\n3498   12.753804 2.234865 3.124261 -1.978184  -1.270557  -0.538727\n3499   12.388022 2.234865 3.082162 -1.978184  -1.270557  -0.538727\n3533    9.101190 2.234865 2.703841 -1.978184  -1.270557  -0.538727\n3610   12.833726 2.234865 3.133468 -1.978184  -1.270557  -0.538727\n3657   11.665625 2.234865 2.999018 -1.978184  -1.270557  -0.538727\n3688   11.817302 2.234865 3.016471 -1.978184  -1.270557  -0.538727\n3705   10.330004 2.234865 2.845281 -1.978184  -1.270557  -0.538727\n3716   13.365258 2.234865 3.194655 -1.978184  -1.270557  -0.538727\n3838   14.939202 2.234865 3.375805 -1.978184  -1.270557  -0.538727\n3881   11.699266 2.234865 3.002885 -1.978184  -1.270557  -0.538727\n3967   12.646379 2.234865 3.111900 -1.978184  -1.270557  -0.538727\n3992   13.553270 2.234865 3.216283 -1.978184  -1.270557  -0.538727\n3999   13.038337 2.234865 3.157020 -1.978184  -1.270557  -0.538727\n4042   11.518782 2.234865 2.982111 -1.978184  -1.270557  -0.538727\n4173   10.880516 2.234865 2.908650 -1.978184  -1.270557  -0.538727\n4223   12.511361 2.234865 3.096361 -1.978184  -1.270557  -0.538727\n4253    9.940387 2.234865 2.800432 -1.978184  -1.270557  -0.538727\n4292   13.029757 2.234865 3.156021 -1.978184  -1.270557  -0.538727\n4325   13.154704 2.234865 3.170407 -1.978184  -1.270557  -0.538727\n4350   11.666444 2.234865 2.999110 -1.978184  -1.270557  -0.538727\n4383   11.643714 2.234865 2.996495 -1.978184  -1.270557  -0.538727\n4410   12.946636 2.234865 3.146459 -1.978184  -1.270557  -0.538727\n4420   13.934848 2.234865 3.260203 -1.978184  -1.270557  -0.538727\n4458   10.634489 2.234865 2.880328 -1.978184  -1.270557  -0.538727\n4511   11.454390 2.234865 2.974696 -1.978184  -1.270557  -0.538727\n4523    9.045434 2.234865 2.697431 -1.978184  -1.270557  -0.538727\n4530    9.894653 2.234865 2.795177 -1.978184  -1.270557  -0.538727\n4642   13.900599 2.234865 3.256263 -1.978184  -1.270557  -0.538727\n4868   10.187720 2.234865 2.828903 -1.978184  -1.270557  -0.538727\n4931   11.128000 2.234865 2.937129 -1.978184  -1.270557  -0.538727\n5192    9.466926 2.234865 2.745941 -1.978184  -1.270557  -0.538727\n5404   11.807702 2.234865 3.015365 -1.978184  -1.270557  -0.538727\n5619   12.500174 2.234865 3.095082 -1.978184  -1.270557  -0.538727\n5640   13.482620 2.234865 3.208154 -1.978184  -1.270557  -0.538727\n5650   13.578211 2.234865 3.219153 -1.978184  -1.270557  -0.538727\n5667   11.130301 2.234865 2.937402 -1.978184  -1.270557  -0.538727\n5720   12.061825 2.234865 3.044619 -1.978184  -1.270557  -0.538727\n5761   10.021360 2.234865 2.809763 -1.978184  -1.270557  -0.538727\n5762    9.785882 2.234865 2.782653 -1.978184  -1.270557  -0.538727\n5783   12.504746 2.234865 3.095598 -1.978184  -1.270557  -0.538727\n5815   10.239523 2.234865 2.834870 -1.978184  -1.270557  -0.538727\n5819   11.681413 2.234865 3.000828 -1.978184  -1.270557  -0.538727\n5838   12.892546 2.234865 3.140232 -1.978184  -1.270557  -0.538727\n5937   13.927826 2.234865 3.259395 -1.978184  -1.270557  -0.538727\n6074   12.061170 2.234865 3.044541 -1.978184  -1.270557  -0.538727\n6089   14.412208 2.234865 3.315146 -1.978184  -1.270557  -0.538727\n6144   10.339590 2.234865 2.846386 -1.978184  -1.270557  -0.538727\n6170   15.341175 2.234865 3.422077 -1.978184  -1.270557  -0.538727\n6291   13.176073 2.234865 3.172870 -1.978184  -1.270557  -0.538727\n6366   12.732186 2.234865 3.121776 -1.978184  -1.270557  -0.538727\n6397   14.846659 2.234865 3.365154 -1.978184  -1.270557  -0.538727\n6415   12.419251 2.234865 3.085759 -1.978184  -1.270557  -0.538727\n6443   10.830719 2.234865 2.902906 -1.978184  -1.270557  -0.538727\n6464   11.121082 2.234865 2.936335 -1.978184  -1.270557  -0.538727\n6469   14.285111 2.234865 3.300522 -1.978184  -1.270557  -0.538727\n6484   13.064661 2.234865 3.160039 -1.978184  -1.270557  -0.538727\n6578   10.937312 2.234865 2.915187 -1.978184  -1.270557  -0.538727\n6600   12.007583 2.234865 3.038380 -1.978184  -1.270557  -0.538727\n6808   11.647540 2.234865 2.996931 -1.978184  -1.270557  -0.538727\n6816   13.325227 2.234865 3.190037 -1.978184  -1.270557  -0.538727\n6897   13.655799 2.234865 3.228088 -1.978184  -1.270557  -0.538727\n6990    9.566972 2.234865 2.757451 -1.978184  -1.270557  -0.538727\n7011   11.897801 2.234865 3.025743 -1.978184  -1.270557  -0.538727\n7101   11.859391 2.234865 3.021312 -1.978184  -1.270557  -0.538727\n7172    8.984370 2.234865 2.690399 -1.978184  -1.270557  -0.538727\n7232   12.769498 2.234865 3.126075 -1.978184  -1.270557  -0.538727\n7276   12.438962 2.234865 3.088029 -1.978184  -1.270557  -0.538727\n7332   11.973258 2.234865 3.034424 -1.978184  -1.270557  -0.538727\n7341   10.565674 2.234865 2.872402 -1.978184  -1.270557  -0.538727\n7342   11.574087 2.234865 2.988478 -1.978184  -1.270557  -0.538727\n7345   13.153956 2.234865 3.170331 -1.978184  -1.270557  -0.538727\n7364   12.090375 2.234865 3.047901 -1.978184  -1.270557  -0.538727\n7635   12.386644 2.234865 3.082006 -1.978184  -1.270557  -0.538727\n7688   15.099570 2.234865 3.394262 -1.978184  -1.270557  -0.538727\n7697   14.164556 2.234865 3.286645 -1.978184  -1.270557  -0.538727\n7734   13.416151 2.234865 3.200509 -1.978184  -1.270557  -0.538727\n7890   10.183108 2.234865 2.828367 -1.978184  -1.270557  -0.538727\n7919   13.143945 2.234865 3.169172 -1.978184  -1.270557  -0.538727\n8009   11.222824 2.234865 2.948045 -1.978184  -1.270557  -0.538727\n8150   12.044569 2.234865 3.042626 -1.978184  -1.270557  -0.538727\n8165   13.352519 2.234865 3.193178 -1.978184  -1.270557  -0.538727\n8175   13.578912 2.234865 3.219233 -1.978184  -1.270557  -0.538727\n8188   12.337848 2.234865 3.076390 -1.978184  -1.270557  -0.538727\n8193   13.889837 2.234865 3.255024 -1.978184  -1.270557  -0.538727\n8202   11.680047 2.234865 3.000675 -1.978184  -1.270557  -0.538727\n8357   13.909138 2.234865 3.257243 -1.978184  -1.270557  -0.538727\n8367    7.972658 2.234865 2.573945 -1.978184  -1.270557  -0.538727\n8477   12.950399 2.234865 3.146895 -1.978184  -1.270557  -0.538727\n8531   12.275810 2.234865 3.069247 -1.978184  -1.270557  -0.538727\n8627   10.833120 2.234865 2.903187 -1.978184  -1.270557  -0.538727\n8628   14.160225 2.234865 3.286143 -1.978184  -1.270557  -0.538727\n8707   12.389007 2.234865 3.082277 -1.978184  -1.270557  -0.538727\n8775   10.737122 2.234865 2.892137 -1.978184  -1.270557  -0.538727\n8800    9.104465 2.234865 2.704229 -1.978184  -1.270557  -0.538727\n8854    7.903701 2.234865 2.566014 -1.978184  -1.270557  -0.538727\n8857   13.962803 2.234865 3.263422 -1.978184  -1.270557  -0.538727\n8874   12.938358 2.234865 3.145509 -1.978184  -1.270557  -0.538727\n8946   11.494372 2.234865 2.979297 -1.978184  -1.270557  -0.538727\n8983   11.886324 2.234865 3.024412 -1.978184  -1.270557  -0.538727\n9021   11.551381 2.234865 2.985865 -1.978184  -1.270557  -0.538727\n9104   13.027622 2.234865 3.155782 -1.978184  -1.270557  -0.538727\n9158   10.226599 2.234865 2.833385 -1.978184  -1.270557  -0.538727\n9198   14.880062 2.234865 3.369003 -1.978184  -1.270557  -0.538727\n9225   13.444720 2.234865 3.203790 -1.978184  -1.270557  -0.538727\n9292   13.144134 2.234865 3.169190 -1.978184  -1.270557  -0.538727\n9340   12.355989 2.234865 3.078476 -1.978184  -1.270557  -0.538727\n9347   11.210474 2.234865 2.946628 -1.978184  -1.270557  -0.538727\n9359   12.291179 2.234865 3.071010 -1.978184  -1.270557  -0.538727\n9397   10.411716 2.234865 2.854685 -1.978184  -1.270557  -0.538727\n9508   11.808596 2.234865 3.015473 -1.978184  -1.270557  -0.538727\n9550   11.354209 2.234865 2.963171 -1.978184  -1.270557  -0.538727\n9586   11.661078 2.234865 2.998490 -1.978184  -1.270557  -0.538727\n\nattr(,\"class\")\n[1] \"coef.mer\"\n```\n:::\n\n```{.r .cell-code}\nranova(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nANOVA-like table for random-effects: Single term deletions\n\nModel:\nmathach ~ sector + ses + himnty + (1 + ses | schid) + sector:ses + ses:himnty\n                         npar logLik   AIC    LRT Df Pr(>Chisq)\n<none>                     10 -23271 46561                     \nses in (1 + ses | schid)    8 -23272 46560 2.6556  2     0.2651\n```\n:::\n:::\n\n\n### centering\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit<-lmer(mathach ~ 1+ses + (1 + ses | schid), \n          data= merge.dat)\nsummary(fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLinear mixed model fit by REML. t-tests use Satterthwaite's method [\nlmerModLmerTest]\nFormula: mathach ~ 1 + ses + (1 + ses | schid)\n   Data: merge.dat\n\nREML criterion at convergence: 46640.4\n\nScaled residuals: \n     Min       1Q   Median       3Q      Max \n-3.12272 -0.73046  0.02144  0.75610  2.94356 \n\nRandom effects:\n Groups   Name        Variance Std.Dev. Corr \n schid    (Intercept)  4.8287  2.1974        \n          ses          0.4129  0.6426   -0.11\n Residual             36.8301  6.0688        \nNumber of obs: 7185, groups:  schid, 160\n\nFixed effects:\n            Estimate Std. Error       df t value Pr(>|t|)    \n(Intercept)  12.6650     0.1898 145.5479   66.71   <2e-16 ***\nses           2.3938     0.1181 157.5299   20.27   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nCorrelation of Fixed Effects:\n    (Intr)\nses -0.045\n```\n:::\n:::\n\n\n#### type 1\n\nstudent-level model\n\n$mathach_{ij} = \\beta_{0j} + \\beta_{1j}SES_{ij} + e_{ij}$\n\nschool-level model\n\n$\\beta_{0j} = \\gamma_{00} + u_{0j}$\n\n$\\beta_{1j} = \\gamma_{10} + u_{1j}$\n\n$\\gamma_{00} = 12.66$ ค่าเฉลี่นย mathach ของนักเรียนที่มีฐานะปานกลาง ในโรงเรียน j\n\n$\\beta_{0j}$ ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะอยู่ในระดับปานกลางของประเทศ ในโรงเรียนที่ j\n\n#### type2 : centering SES ด้วย group means\n\nstudent-level model\n\n$mathach_{ij} = \\beta_{0j} + \\beta_{1j}(SES_{ij}-\\overline{SES}_{.j}) + e_{ij}$\n\nschool-level model\n\n$\\beta_{0j} = \\gamma_{00} + u_{0j}$\n\n$\\beta_{1j} = \\gamma_{10} + u_{1j}$\n\nintercepe ==\\> $\\beta_{0j}$ \\<\\-- ค่าของ y เมื่อ x เป็น 0 ---\\> ค่าเฉลี่ยของ mathach เมื่อ centering term เป็น 0\n\n$\\beta_{0j}$ ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลางของโรงเรียนที่ j\n\n#### type3 : centering SES ด้วย grand means\n\nstudent-level model\n\n$mathach_{ij} = \\beta_{0j} + \\beta_{1j}(SES_{ij}-\\overline{SES}_{..}) + e_{ij}$\n\nschool-level model\n\n$\\beta_{0j} = \\gamma_{00} + u_{0j}$\n\n$\\beta_{1j} = \\gamma_{10} + u_{1j}$\n",
    "supporting": [
      "08HypotheticalModel_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}