project:
  type: default

title: |
 | แบบสอบปลายภาค รายวิชา 2758615 สมรรถนะสําคัญของการเขียนโปรแกรมวิเคราะห์ข้อมูลทางการศึกษา
 | ภาคต้น ปีการศึกษา 2568

format:
  pdf:
    pdf-engine: xelatex
    toc: true
    number-sections: false
    include-in-header:
      - "thai-preamble.tex"    # preamble ภาษาไทย
      - text: |
          % ใช้รูปใน title
          \usepackage{graphicx}
          \usepackage{titling}
          \pretitle{\begin{center}\includegraphics[width=10cm]{logo-banner.png}\\[\bigskipamount]\LARGE}
          \posttitle{\end{center}}
    keep-tex: false