<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2756714 MSEM RES - Hypothetical Model</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<meta property="og:title" content="2756714 MSEM RES - Hypothetical Model">
<meta property="og:description" content="ขอให้นิสิตใช้ไฟล์ข้อมูล hsb.sav และ hsb2.sav สำหรับวิเคราะห์เพื่อตอบคำถามวิจัยต่อไปนี้">
<meta property="og:site-name" content="2756714 MSEM RES">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Hypothetical Model</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
    <a href="https://www.facebook.com/KruRooEduCU" title="KruRoo @ EDUCU" class="sidebar-tool px-1"><i class="bi bi-facebook"></i></a>
    <a href="https://posit.co/download/rstudio-desktop/" title="RStudio" class="sidebar-tool px-1"><i class="bi bi-code-square"></i></a>
</div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">Course information</a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">MSEM RES 2023</a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../instructors.html" class="sidebar-item-text sidebar-link">Instructor</a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#คำอธบายขอมล" id="toc-คำอธบายขอมล" class="nav-link active" data-scroll-target="#คำอธบายขอมล">คำอธิบายข้อมูล</a></li>
  <li><a href="#คำถามวจย" id="toc-คำถามวจย" class="nav-link" data-scroll-target="#คำถามวจย">คำถามวิจัย</a></li>
  <li><a href="#modelling" id="toc-modelling" class="nav-link" data-scroll-target="#modelling">modelling</a>
  <ul class="collapse">
  <li><a href="#centering" id="toc-centering" class="nav-link" data-scroll-target="#centering">centering</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Hypothetical Model</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>ขอให้นิสิตใช้ไฟล์ข้อมูล hsb.sav และ hsb2.sav สำหรับวิเคราะห์เพื่อตอบคำถามวิจัยต่อไปนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>hsb2<span class="ot">&lt;-</span><span class="fu">read_spss</span>(<span class="st">"/Users/siwachoat/Library/CloudStorage/OneDrive-ChulalongkornUniversity/Documents/MSEM/MSEM/datasets/hsb2.sav"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(hsb2, <span class="at">width=</span><span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 160
Columns: 7
$ schoolid &lt;dbl&gt; 1224, 1288, 1296, 1308, 1317, 1358, 1374, 1433, 1436, 1461, 1…
$ size     &lt;dbl&gt; 842, 1855, 1719, 716, 455, 1430, 2400, 899, 185, 1672, 530, 5…
$ sector   &lt;dbl&gt; 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1…
$ pracad   &lt;dbl&gt; 0.35, 0.27, 0.32, 0.96, 0.95, 0.25, 0.50, 0.96, 1.00, 0.78, 0…
$ disclim  &lt;dbl&gt; 1.597, 0.174, -0.137, -0.622, -1.694, 1.535, 2.016, -0.321, -…
$ himnty   &lt;dbl&gt; 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1…
$ meanses  &lt;dbl&gt; -0.428, 0.128, -0.420, 0.534, 0.351, -0.014, -0.007, 0.718, 0…</code></pre>
</div>
</div>
<section id="คำอธบายขอมล" class="level2">
<h2 class="anchored" data-anchor-id="คำอธบายขอมล">คำอธิบายข้อมูล</h2>
<ul>
<li><p>size คือ จำนวนนักเรียนภายในโรงเรียน</p></li>
<li><p>sector คือ ประเภทของโรงเรียน (เหมือน hsb.sav)</p></li>
<li><p>pracad คือ สัดส่วนของนักเรียนในโรงเรียนที่เรียนสายสามัญ</p></li>
<li><p>disclim คือ คะแนนบรรยากาศความมีวิจัยในโรงเรียน</p></li>
<li><p>himnty คือ ตัวแปรดัมมี่ (1 = มีชนกลุ่มน้อยในโรงเรียนมากกว่าร้อยละ 40, 0 = น้อยกว่าร้อยละ 40)</p></li>
<li><p>meanses คือ ค่าเฉลี่ยของคะแนนเศรษฐานะระดับโรงเรียน</p></li>
</ul>
</section>
<section id="คำถามวจย" class="level2">
<h2 class="anchored" data-anchor-id="คำถามวจย">คำถามวิจัย</h2>
<ol type="1">
<li>ผลสัมฤทธิ์ทางการเรียนโดยเฉลี่ยระดับโรงเรียนมีความแตกต่างกันระหว่างสังกัด (sector) อย่างไร</li>
<li>อิทธิพลของเศรษฐานะของครอบครัวนักเรียนที่มีต่อผลสัมฤทธิ์ทางการเรียนวิชาคณิตศาสตร์ของนักเรียน มีความแตกต่างกันอย่างไร ตามประเภทของโรงเรียน (sector) และสัดส่วนชนกลุ่มน้อยในโรงเรียน (himnty)</li>
</ol>
</section>
<section id="modelling" class="level2">
<h2 class="anchored" data-anchor-id="modelling">modelling</h2>
<p>student-level model</p>
<p><span class="math inline">\(mathach_{ij} = \beta_{0j} + \beta_{1j}SES_{ij} + e_{ij}\)</span></p>
<p>school-level model</p>
<p><span class="math inline">\(\beta_{0j} = \gamma_{00} + \gamma_{01}Sector_j + u_{0j}\)</span></p>
<p><span class="math inline">\(\beta_{1j} = \gamma_{10} + \gamma_{11}Sector_j + \gamma_{12}Himnty_j + u_{1j}\)</span></p>
<p>Combined-model</p>
<p><span class="math inline">\(mathach_{ij} = \gamma_{00} + \gamma_{01}Sector_j + u_{0j} + ( \gamma_{10} + \gamma_{11}Sector_j + \gamma_{12}Himnty_j + u_{1j})SES_{ij} + e_{ij}\)</span></p>
<p><span class="math inline">\(mathach_{ij} = \gamma_{00} + \gamma_{01}Sector_j + u_{0j} + \gamma_{10}SES_{ij} + \gamma_{11}Sector_jSES_{ij} + \gamma_{12}Himnty_jSES_{ij} + u_{1j}SES_{ij} + e_{ij}\)</span></p>
<p><span class="math inline">\(mathach_{ij} = \gamma_{00} + \gamma_{01}Sector_j + \gamma_{10}SES_{ij} + \gamma_{11}Sector_jSES_{ij} + \gamma_{12}Himnty_jSES_{ij} + u_{0j}+u_{1j}SES_{ij} + e_{ij}\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># student level data</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_spss</span>(<span class="st">"datasets/HSB.SAV"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 7,185
Columns: 4
$ schid   &lt;chr&gt; "1224", "1224", "1224", "1224", "1224", "1224", "1224", "1224"…
$ sector  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…
$ ses     &lt;dbl&gt; -1.528, -0.588, -0.528, -0.668, -0.158, 0.022, -0.618, -0.998,…
$ mathach &lt;dbl&gt; 5.876, 19.708, 20.349, 8.781, 17.898, 4.583, -2.832, 0.523, 1.…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    schid               sector            ses               mathach      
 Length:7185        Min.   :0.0000   Min.   :-3.758000   Min.   :-2.832  
 Class :character   1st Qu.:0.0000   1st Qu.:-0.538000   1st Qu.: 7.275  
 Mode  :character   Median :0.0000   Median : 0.002000   Median :13.131  
                    Mean   :0.4931   Mean   : 0.000143   Mean   :12.748  
                    3rd Qu.:1.0000   3rd Qu.: 0.602000   3rd Qu.:18.317  
                    Max.   :1.0000   Max.   : 2.692000   Max.   :24.993  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># school level data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dat2<span class="ot">&lt;-</span><span class="fu">read_spss</span>(<span class="st">"/Users/siwachoat/Library/CloudStorage/OneDrive-ChulalongkornUniversity/Documents/MSEM/MSEM/datasets/hsb2.sav"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  schoolid  size sector pracad disclim himnty meanses
     &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
1     1224   842      0   0.35   1.60       0  -0.428
2     1288  1855      0   0.27   0.174      0   0.128
3     1296  1719      0   0.32  -0.137      1  -0.42 
4     1308   716      1   0.96  -0.622      0   0.534
5     1317   455      1   0.95  -1.69       1   0.351
6     1358  1430      0   0.25   1.54       0  -0.014</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">## merging data</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>merge.dat <span class="ot">&lt;-</span> <span class="fu">merge</span>(dat, dat2, <span class="at">by.x =</span> <span class="st">"schid"</span>, <span class="at">by.y =</span><span class="st">"schoolid"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(merge.dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  schid sector.x    ses mathach size sector.y pracad disclim himnty meanses
1  1224        0 -1.528   5.876  842        0   0.35   1.597      0  -0.428
2  1224        0 -0.588  19.708  842        0   0.35   1.597      0  -0.428
3  1224        0 -0.528  20.349  842        0   0.35   1.597      0  -0.428
4  1224        0 -0.668   8.781  842        0   0.35   1.597      0  -0.428
5  1224        0 -0.158  17.898  842        0   0.35   1.597      0  -0.428
6  1224        0  0.022   4.583  842        0   0.35   1.597      0  -0.428</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>merge.dat <span class="ot">&lt;-</span> merge.dat <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>sector.x)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(merge.dat)[<span class="dv">5</span>]<span class="ot">&lt;-</span><span class="st">"sector"</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># modeling</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lmer</span>(mathach <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>sector<span class="sc">+</span>ses<span class="sc">+</span>sector<span class="sc">*</span>ses<span class="sc">+</span>himnty<span class="sc">*</span>ses <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> ses <span class="sc">|</span> schid), </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data=</span> merge.dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv, :
Model failed to converge with max|grad| = 0.00428662 (tol = 0.002, component 1)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: mathach ~ 1 + sector + ses + sector * ses + himnty * ses + (1 +  
    ses | schid)
   Data: merge.dat

REML criterion at convergence: 46541.2

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-3.10322 -0.72947  0.01724  0.75783  2.99649 

Random effects:
 Groups   Name        Variance Std.Dev. Corr
 schid    (Intercept)  3.07538 1.7537       
          ses          0.04075 0.2019   1.00
 Residual             36.78875 6.0654       
Number of obs: 7185, groups:  schid, 160

Fixed effects:
            Estimate Std. Error t value
(Intercept)  12.2300     0.2307  53.007
sector        2.2349     0.3179   7.030
ses           3.0640     0.1571  19.507
himnty       -1.9782     0.3570  -5.541
sector:ses   -1.2706     0.2128  -5.971
ses:himnty   -0.5387     0.2289  -2.353

Correlation of Fixed Effects:
           (Intr) sector ses    himnty sctr:s
sector     -0.595                            
ses         0.161 -0.136                     
himnty     -0.376 -0.064 -0.012              
sector:ses -0.135  0.127 -0.580 -0.024       
ses:himnty -0.018 -0.020 -0.428  0.249 -0.041
optimizer (nloptwrap) convergence code: 0 (OK)
Model failed to converge with max|grad| = 0.00428662 (tol = 0.002, component 1)</code></pre>
</div>
</div>
<p><img src="images/image-984491753.png" class="img-fluid" width="255"></p>
<p><span class="math inline">\(\gamma_{00} = 12.23\)</span> คือ ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลาง ในโรงเรียนรัฐ</p>
<p>ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลางในโรงเรียน car เท่ากับ 12.23 + 2.2349 <span class="math inline">\(=\gamma_{00} + \gamma_{01}(1)\)</span></p>
<p><span class="math inline">\(\beta_{1j}\)</span> คืออัตราการเปลี่ยนของ mathach เมื่อเทียบกับ ses ของโรงเรียนที่ j</p>
<p><span class="math inline">\(\gamma_{10} = 3.06\)</span> คือ ค่าเฉลี่ยของอัตราการเปลี่ยนของ mathach เมื่อเทียบกับ ses ของนักเรียนในโรงเรียนรัฐที่มีนักเรียนต่างชาติเป็นส่วนน้อย</p>
<p>ค่าเฉลี่ยของอัตราการเปลี่ยนของ mathach เมื่อเทียบกับ ses ของนักเรียนในโรงเรียน car เท่ากับ 3.06 - 1.27 = 1.79 เมื่อควบคุมให้ปัจจัยจำนวนนักเรียนต่างชาติในโรงเรียนคงที่</p>
<p><span class="math inline">\(\beta_{0j}\)</span> คือค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลางในโรงเรียน j</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'lmerTest'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:lme4':

    lmer</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:stats':

    step</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$schid
     (Intercept)   sector      ses    himnty sector:ses ses:himnty
1224   11.241236 2.234865 2.950165 -1.978184  -1.270557  -0.538727
1288   12.845183 2.234865 3.134783 -1.978184  -1.270557  -0.538727
1296   10.906321 2.234865 2.911614 -1.978184  -1.270557  -0.538727
1308   12.724127 2.234865 3.120848 -1.978184  -1.270557  -0.538727
1317   12.431322 2.234865 3.087147 -1.978184  -1.270557  -0.538727
1358   11.612052 2.234865 2.992851 -1.978184  -1.270557  -0.538727
1374   10.540892 2.234865 2.869557 -1.978184  -1.270557  -0.538727
1433   15.068397 2.234865 3.390681 -1.978184  -1.270557  -0.538727
1436   14.216680 2.234865 3.292645 -1.978184  -1.270557  -0.538727
1461   14.128594 2.234865 3.282513 -1.978184  -1.270557  -0.538727
1462   11.159206 2.234865 2.940720 -1.978184  -1.270557  -0.538727
1477   11.775880 2.234865 3.011702 -1.978184  -1.270557  -0.538727
1499   11.100892 2.234865 2.934018 -1.978184  -1.270557  -0.538727
1637   11.232796 2.234865 2.949197 -1.978184  -1.270557  -0.538727
1906   12.711631 2.234865 3.119412 -1.978184  -1.270557  -0.538727
1909   13.210379 2.234865 3.176817 -1.978184  -1.270557  -0.538727
1942   14.761318 2.234865 3.355332 -1.978184  -1.270557  -0.538727
1946   12.758830 2.234865 3.124844 -1.978184  -1.270557  -0.538727
2030   11.267216 2.234865 2.953151 -1.978184  -1.270557  -0.538727
2208   12.401674 2.234865 3.083736 -1.978184  -1.270557  -0.538727
2277   10.102000 2.234865 2.819029 -1.978184  -1.270557  -0.538727
2305   11.636863 2.234865 2.995695 -1.978184  -1.270557  -0.538727
2336   14.451603 2.234865 3.319682 -1.978184  -1.270557  -0.538727
2458   13.277136 2.234865 3.184507 -1.978184  -1.270557  -0.538727
2467   11.341851 2.234865 2.961748 -1.978184  -1.270557  -0.538727
2526   13.785120 2.234865 3.242966 -1.978184  -1.270557  -0.538727
2626   13.297116 2.234865 3.186802 -1.978184  -1.270557  -0.538727
2629   12.728091 2.234865 3.121299 -1.978184  -1.270557  -0.538727
2639   11.115892 2.234865 2.935733 -1.978184  -1.270557  -0.538727
2651   11.282684 2.234865 2.954940 -1.978184  -1.270557  -0.538727
2655   15.630348 2.234865 3.455362 -1.978184  -1.270557  -0.538727
2658   10.840484 2.234865 2.904040 -1.978184  -1.270557  -0.538727
2755   12.965991 2.234865 3.148685 -1.978184  -1.270557  -0.538727
2768   11.463639 2.234865 2.975766 -1.978184  -1.270557  -0.538727
2771   12.810725 2.234865 3.130818 -1.978184  -1.270557  -0.538727
2818   13.229949 2.234865 3.179069 -1.978184  -1.270557  -0.538727
2917   11.904652 2.234865 3.026519 -1.978184  -1.270557  -0.538727
2990   16.148529 2.234865 3.515006 -1.978184  -1.270557  -0.538727
2995   10.696677 2.234865 2.887480 -1.978184  -1.270557  -0.538727
3013   12.668131 2.234865 3.114405 -1.978184  -1.270557  -0.538727
3020   11.832330 2.234865 3.018201 -1.978184  -1.270557  -0.538727
3039   14.821412 2.234865 3.362253 -1.978184  -1.270557  -0.538727
3088   12.255043 2.234865 3.066854 -1.978184  -1.270557  -0.538727
3152   12.922423 2.234865 3.143671 -1.978184  -1.270557  -0.538727
3332   12.331004 2.234865 3.075598 -1.978184  -1.270557  -0.538727
3351   12.516525 2.234865 3.096953 -1.978184  -1.270557  -0.538727
3377   12.412745 2.234865 3.084998 -1.978184  -1.270557  -0.538727
3427   16.081490 2.234865 3.507280 -1.978184  -1.270557  -0.538727
3498   12.753804 2.234865 3.124261 -1.978184  -1.270557  -0.538727
3499   12.388022 2.234865 3.082162 -1.978184  -1.270557  -0.538727
3533    9.101190 2.234865 2.703841 -1.978184  -1.270557  -0.538727
3610   12.833726 2.234865 3.133468 -1.978184  -1.270557  -0.538727
3657   11.665625 2.234865 2.999018 -1.978184  -1.270557  -0.538727
3688   11.817302 2.234865 3.016471 -1.978184  -1.270557  -0.538727
3705   10.330004 2.234865 2.845281 -1.978184  -1.270557  -0.538727
3716   13.365258 2.234865 3.194655 -1.978184  -1.270557  -0.538727
3838   14.939202 2.234865 3.375805 -1.978184  -1.270557  -0.538727
3881   11.699266 2.234865 3.002885 -1.978184  -1.270557  -0.538727
3967   12.646379 2.234865 3.111900 -1.978184  -1.270557  -0.538727
3992   13.553270 2.234865 3.216283 -1.978184  -1.270557  -0.538727
3999   13.038337 2.234865 3.157020 -1.978184  -1.270557  -0.538727
4042   11.518782 2.234865 2.982111 -1.978184  -1.270557  -0.538727
4173   10.880516 2.234865 2.908650 -1.978184  -1.270557  -0.538727
4223   12.511361 2.234865 3.096361 -1.978184  -1.270557  -0.538727
4253    9.940387 2.234865 2.800432 -1.978184  -1.270557  -0.538727
4292   13.029757 2.234865 3.156021 -1.978184  -1.270557  -0.538727
4325   13.154704 2.234865 3.170407 -1.978184  -1.270557  -0.538727
4350   11.666444 2.234865 2.999110 -1.978184  -1.270557  -0.538727
4383   11.643714 2.234865 2.996495 -1.978184  -1.270557  -0.538727
4410   12.946636 2.234865 3.146459 -1.978184  -1.270557  -0.538727
4420   13.934848 2.234865 3.260203 -1.978184  -1.270557  -0.538727
4458   10.634489 2.234865 2.880328 -1.978184  -1.270557  -0.538727
4511   11.454390 2.234865 2.974696 -1.978184  -1.270557  -0.538727
4523    9.045434 2.234865 2.697431 -1.978184  -1.270557  -0.538727
4530    9.894653 2.234865 2.795177 -1.978184  -1.270557  -0.538727
4642   13.900599 2.234865 3.256263 -1.978184  -1.270557  -0.538727
4868   10.187720 2.234865 2.828903 -1.978184  -1.270557  -0.538727
4931   11.128000 2.234865 2.937129 -1.978184  -1.270557  -0.538727
5192    9.466926 2.234865 2.745941 -1.978184  -1.270557  -0.538727
5404   11.807702 2.234865 3.015365 -1.978184  -1.270557  -0.538727
5619   12.500174 2.234865 3.095082 -1.978184  -1.270557  -0.538727
5640   13.482620 2.234865 3.208154 -1.978184  -1.270557  -0.538727
5650   13.578211 2.234865 3.219153 -1.978184  -1.270557  -0.538727
5667   11.130301 2.234865 2.937402 -1.978184  -1.270557  -0.538727
5720   12.061825 2.234865 3.044619 -1.978184  -1.270557  -0.538727
5761   10.021360 2.234865 2.809763 -1.978184  -1.270557  -0.538727
5762    9.785882 2.234865 2.782653 -1.978184  -1.270557  -0.538727
5783   12.504746 2.234865 3.095598 -1.978184  -1.270557  -0.538727
5815   10.239523 2.234865 2.834870 -1.978184  -1.270557  -0.538727
5819   11.681413 2.234865 3.000828 -1.978184  -1.270557  -0.538727
5838   12.892546 2.234865 3.140232 -1.978184  -1.270557  -0.538727
5937   13.927826 2.234865 3.259395 -1.978184  -1.270557  -0.538727
6074   12.061170 2.234865 3.044541 -1.978184  -1.270557  -0.538727
6089   14.412208 2.234865 3.315146 -1.978184  -1.270557  -0.538727
6144   10.339590 2.234865 2.846386 -1.978184  -1.270557  -0.538727
6170   15.341175 2.234865 3.422077 -1.978184  -1.270557  -0.538727
6291   13.176073 2.234865 3.172870 -1.978184  -1.270557  -0.538727
6366   12.732186 2.234865 3.121776 -1.978184  -1.270557  -0.538727
6397   14.846659 2.234865 3.365154 -1.978184  -1.270557  -0.538727
6415   12.419251 2.234865 3.085759 -1.978184  -1.270557  -0.538727
6443   10.830719 2.234865 2.902906 -1.978184  -1.270557  -0.538727
6464   11.121082 2.234865 2.936335 -1.978184  -1.270557  -0.538727
6469   14.285111 2.234865 3.300522 -1.978184  -1.270557  -0.538727
6484   13.064661 2.234865 3.160039 -1.978184  -1.270557  -0.538727
6578   10.937312 2.234865 2.915187 -1.978184  -1.270557  -0.538727
6600   12.007583 2.234865 3.038380 -1.978184  -1.270557  -0.538727
6808   11.647540 2.234865 2.996931 -1.978184  -1.270557  -0.538727
6816   13.325227 2.234865 3.190037 -1.978184  -1.270557  -0.538727
6897   13.655799 2.234865 3.228088 -1.978184  -1.270557  -0.538727
6990    9.566972 2.234865 2.757451 -1.978184  -1.270557  -0.538727
7011   11.897801 2.234865 3.025743 -1.978184  -1.270557  -0.538727
7101   11.859391 2.234865 3.021312 -1.978184  -1.270557  -0.538727
7172    8.984370 2.234865 2.690399 -1.978184  -1.270557  -0.538727
7232   12.769498 2.234865 3.126075 -1.978184  -1.270557  -0.538727
7276   12.438962 2.234865 3.088029 -1.978184  -1.270557  -0.538727
7332   11.973258 2.234865 3.034424 -1.978184  -1.270557  -0.538727
7341   10.565674 2.234865 2.872402 -1.978184  -1.270557  -0.538727
7342   11.574087 2.234865 2.988478 -1.978184  -1.270557  -0.538727
7345   13.153956 2.234865 3.170331 -1.978184  -1.270557  -0.538727
7364   12.090375 2.234865 3.047901 -1.978184  -1.270557  -0.538727
7635   12.386644 2.234865 3.082006 -1.978184  -1.270557  -0.538727
7688   15.099570 2.234865 3.394262 -1.978184  -1.270557  -0.538727
7697   14.164556 2.234865 3.286645 -1.978184  -1.270557  -0.538727
7734   13.416151 2.234865 3.200509 -1.978184  -1.270557  -0.538727
7890   10.183108 2.234865 2.828367 -1.978184  -1.270557  -0.538727
7919   13.143945 2.234865 3.169172 -1.978184  -1.270557  -0.538727
8009   11.222824 2.234865 2.948045 -1.978184  -1.270557  -0.538727
8150   12.044569 2.234865 3.042626 -1.978184  -1.270557  -0.538727
8165   13.352519 2.234865 3.193178 -1.978184  -1.270557  -0.538727
8175   13.578912 2.234865 3.219233 -1.978184  -1.270557  -0.538727
8188   12.337848 2.234865 3.076390 -1.978184  -1.270557  -0.538727
8193   13.889837 2.234865 3.255024 -1.978184  -1.270557  -0.538727
8202   11.680047 2.234865 3.000675 -1.978184  -1.270557  -0.538727
8357   13.909138 2.234865 3.257243 -1.978184  -1.270557  -0.538727
8367    7.972658 2.234865 2.573945 -1.978184  -1.270557  -0.538727
8477   12.950399 2.234865 3.146895 -1.978184  -1.270557  -0.538727
8531   12.275810 2.234865 3.069247 -1.978184  -1.270557  -0.538727
8627   10.833120 2.234865 2.903187 -1.978184  -1.270557  -0.538727
8628   14.160225 2.234865 3.286143 -1.978184  -1.270557  -0.538727
8707   12.389007 2.234865 3.082277 -1.978184  -1.270557  -0.538727
8775   10.737122 2.234865 2.892137 -1.978184  -1.270557  -0.538727
8800    9.104465 2.234865 2.704229 -1.978184  -1.270557  -0.538727
8854    7.903701 2.234865 2.566014 -1.978184  -1.270557  -0.538727
8857   13.962803 2.234865 3.263422 -1.978184  -1.270557  -0.538727
8874   12.938358 2.234865 3.145509 -1.978184  -1.270557  -0.538727
8946   11.494372 2.234865 2.979297 -1.978184  -1.270557  -0.538727
8983   11.886324 2.234865 3.024412 -1.978184  -1.270557  -0.538727
9021   11.551381 2.234865 2.985865 -1.978184  -1.270557  -0.538727
9104   13.027622 2.234865 3.155782 -1.978184  -1.270557  -0.538727
9158   10.226599 2.234865 2.833385 -1.978184  -1.270557  -0.538727
9198   14.880062 2.234865 3.369003 -1.978184  -1.270557  -0.538727
9225   13.444720 2.234865 3.203790 -1.978184  -1.270557  -0.538727
9292   13.144134 2.234865 3.169190 -1.978184  -1.270557  -0.538727
9340   12.355989 2.234865 3.078476 -1.978184  -1.270557  -0.538727
9347   11.210474 2.234865 2.946628 -1.978184  -1.270557  -0.538727
9359   12.291179 2.234865 3.071010 -1.978184  -1.270557  -0.538727
9397   10.411716 2.234865 2.854685 -1.978184  -1.270557  -0.538727
9508   11.808596 2.234865 3.015473 -1.978184  -1.270557  -0.538727
9550   11.354209 2.234865 2.963171 -1.978184  -1.270557  -0.538727
9586   11.661078 2.234865 2.998490 -1.978184  -1.270557  -0.538727

attr(,"class")
[1] "coef.mer"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ranova</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ANOVA-like table for random-effects: Single term deletions

Model:
mathach ~ sector + ses + himnty + (1 + ses | schid) + sector:ses + ses:himnty
                         npar logLik   AIC    LRT Df Pr(&gt;Chisq)
&lt;none&gt;                     10 -23271 46561                     
ses in (1 + ses | schid)    8 -23272 46560 2.6556  2     0.2651</code></pre>
</div>
</div>
<section id="centering" class="level3">
<h3 class="anchored" data-anchor-id="centering">centering</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>fit<span class="ot">&lt;-</span><span class="fu">lmer</span>(mathach <span class="sc">~</span> <span class="dv">1</span><span class="sc">+</span>ses <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> ses <span class="sc">|</span> schid), </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>          <span class="at">data=</span> merge.dat)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: mathach ~ 1 + ses + (1 + ses | schid)
   Data: merge.dat

REML criterion at convergence: 46640.4

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-3.12272 -0.73046  0.02144  0.75610  2.94356 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 schid    (Intercept)  4.8287  2.1974        
          ses          0.4129  0.6426   -0.11
 Residual             36.8301  6.0688        
Number of obs: 7185, groups:  schid, 160

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept)  12.6650     0.1898 145.5479   66.71   &lt;2e-16 ***
ses           2.3938     0.1181 157.5299   20.27   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
    (Intr)
ses -0.045</code></pre>
</div>
</div>
<section id="type-1" class="level4">
<h4 class="anchored" data-anchor-id="type-1">type 1</h4>
<p>student-level model</p>
<p><span class="math inline">\(mathach_{ij} = \beta_{0j} + \beta_{1j}SES_{ij} + e_{ij}\)</span></p>
<p>school-level model</p>
<p><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span></p>
<p><span class="math inline">\(\beta_{1j} = \gamma_{10} + u_{1j}\)</span></p>
<p><span class="math inline">\(\gamma_{00} = 12.66\)</span> ค่าเฉลี่นย mathach ของนักเรียนที่มีฐานะปานกลาง ในโรงเรียน j</p>
<p><span class="math inline">\(\beta_{0j}\)</span> ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะอยู่ในระดับปานกลางของประเทศ ในโรงเรียนที่ j</p>
</section>
<section id="type2-centering-ses-ดวย-group-means" class="level4">
<h4 class="anchored" data-anchor-id="type2-centering-ses-ดวย-group-means">type2 : centering SES ด้วย group means</h4>
<p>student-level model</p>
<p><span class="math inline">\(mathach_{ij} = \beta_{0j} + \beta_{1j}(SES_{ij}-\overline{SES}_{.j}) + e_{ij}\)</span></p>
<p>school-level model</p>
<p><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span></p>
<p><span class="math inline">\(\beta_{1j} = \gamma_{10} + u_{1j}\)</span></p>
<p>intercepe ==&gt; <span class="math inline">\(\beta_{0j}\)</span> &lt;-- ค่าของ y เมื่อ x เป็น 0 —&gt; ค่าเฉลี่ยของ mathach เมื่อ centering term เป็น 0</p>
<p><span class="math inline">\(\beta_{0j}\)</span> ค่าเฉลี่ย mathach ของนักเรียนที่มีฐานะปานกลางของโรงเรียนที่ j</p>
</section>
<section id="type3-centering-ses-ดวย-grand-means" class="level4">
<h4 class="anchored" data-anchor-id="type3-centering-ses-ดวย-grand-means">type3 : centering SES ด้วย grand means</h4>
<p>student-level model</p>
<p><span class="math inline">\(mathach_{ij} = \beta_{0j} + \beta_{1j}(SES_{ij}-\overline{SES}_{..}) + e_{ij}\)</span></p>
<p>school-level model</p>
<p><span class="math inline">\(\beta_{0j} = \gamma_{00} + u_{0j}\)</span></p>
<p><span class="math inline">\(\beta_{1j} = \gamma_{10} + u_{1j}\)</span></p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">© Copyright 2023, DataKruRoo</div>   
    <div class="nav-footer-right">This page is built with ❤️ and <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>