<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="regression_files/libs/clipboard/clipboard.min.js"></script>
<script src="regression_files/libs/quarto-html/quarto.js"></script>
<script src="regression_files/libs/quarto-html/popper.min.js"></script>
<script src="regression_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="regression_files/libs/quarto-html/anchor.min.js"></script>
<link href="regression_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="regression_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="regression_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="regression_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="regression_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="regression_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="regression_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="regression_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link active" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
  <li><a href="#exploring-data" id="toc-exploring-data" class="nav-link" data-scroll-target="#exploring-data">1. exploring data</a></li>
  <li><a href="#fit-simple-regression" id="toc-fit-simple-regression" class="nav-link" data-scroll-target="#fit-simple-regression">2. fit simple regression</a></li>
  <li><a href="#การแปลความหมายพารามเตอรในโมเดล" id="toc-การแปลความหมายพารามเตอรในโมเดล" class="nav-link" data-scroll-target="#การแปลความหมายพารามเตอรในโมเดล">3. การแปลความหมายพารามิเตอร์ในโมเดล</a></li>
  </ul></li>
  <li><a href="#multiple-regression" id="toc-multiple-regression" class="nav-link" data-scroll-target="#multiple-regression">Multiple Regression</a></li>
  <li><a href="#regression-with-interaction" id="toc-regression-with-interaction" class="nav-link" data-scroll-target="#regression-with-interaction">Regression with Interaction</a>
  <ul class="collapse">
  <li><a href="#two-way-interaction-effect" id="toc-two-way-interaction-effect" class="nav-link" data-scroll-target="#two-way-interaction-effect">Two-way interaction effect</a></li>
  </ul></li>
  <li><a href="#polynomial-regression" id="toc-polynomial-regression" class="nav-link" data-scroll-target="#polynomial-regression">Polynomial Regression</a>
  <ul class="collapse">
  <li><a href="#ปญหา-multicollinearity-ใน-polynomial-regression" id="toc-ปญหา-multicollinearity-ใน-polynomial-regression" class="nav-link" data-scroll-target="#ปญหา-multicollinearity-ใน-polynomial-regression">ปัญหา Multicollinearity ใน Polynomial Regression</a></li>
  </ul></li>
  <li><a href="#regression-diagnostics" id="toc-regression-diagnostics" class="nav-link" data-scroll-target="#regression-diagnostics">Regression Diagnostics</a></li>
  <li><a href="#regression-remedials" id="toc-regression-remedials" class="nav-link" data-scroll-target="#regression-remedials">Regression Remedials</a></li>
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection">Model Selection</a>
  <ul class="collapse">
  <li><a href="#กจกรรมท-1-ทำลองวเคราะหการถดถอย" id="toc-กจกรรมท-1-ทำลองวเคราะหการถดถอย" class="nav-link" data-scroll-target="#กจกรรมท-1-ทำลองวเคราะหการถดถอย">กิจกรรมที่ 1 ทำลองวิเคราะห์การถดถอย</a></li>
  <li><a href="#filter-methods" id="toc-filter-methods" class="nav-link" data-scroll-target="#filter-methods">Filter Methods</a></li>
  <li><a href="#wrapper-methods" id="toc-wrapper-methods" class="nav-link" data-scroll-target="#wrapper-methods">Wrapper Methods</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Regression เป็นวิธีการทางสถิติที่ใช้วิเคราะห์ความสัมพันธ์ระหว่างตัวแปรตาม (Dependent Variable) และตัวแปรอิสระ (Independent Variables) หนึ่งตัวหรือมากกว่า ซึ่งจะช่วยให้เราเข้าใจว่าตัวแปรตามมีการเปลี่ยนแปลงอย่างไรเมื่อมีการเปลี่ยนแปลงในตัวแปรอิสระ</p>
<p>วัตถุประสงค์ของการวิเคราะห์ regression หลัก ๆ มี 2 ข้อ</p>
<p>คือการสร้างโมเดลทางสถิติที่สามารถใช้</p>
<ol type="1">
<li><p>อธิบายความสัมพันธ์ระหว่างตัวแปรตามกับตัวแปรอิสระ</p></li>
<li><p>ทำนายแนวโน้มของตัวแปรตามเมื่อกำหนดตัวแปรอิสระ</p></li>
</ol>
<p>การวิเคราะห์การถดถอยมีหลายประเภท</p>
<ul>
<li><p>Simple regression</p></li>
<li><p>Multiple regression</p></li>
<li><p>Polynomial regression</p></li>
<li><p>Logistic regression</p></li>
</ul>
<p>…</p>
<section id="simple-linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="simple-linear-regression">Simple Linear Regression</h2>
<p>เป็นโมเดลพื้นฐานใช้อธิบายความสัมพันธ์ระหว่างตัวแปรตามกับตัวแปรอิสระที่เป็นตัวแปรเดียว ทางสังคมศาสตร์อาจไม่ค่อยใช้โมเดลนี้ในทางปฏิบัติเท่าไหร่ แต่มักใช้เป็นโมเดลแรกในการอธิบาย concept เกี่ยวกับ regression</p>
<p>อย่างที่บอกว่า regression analysis จะทำการอธิบายและทำนายตัวแปรตามด้วยตัวแปรอิสระ ผ่านโมเดลทางสถิติ สำหรับ simple regression หรือเรียกเต็ม ๆ ว่า simple linear regression จะมีโมเดลเป็นสมการเส้นตรงที่มีส่วนประกอบจำแนกเป็นสองส่วนได้แก่</p>
<ul>
<li><p>ส่วนที่เป็นความสัมพันธ์เชิงฟังก์ชัน</p></li>
<li><p>ส่วน noise หรือ error</p></li>
</ul>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1X_i + \epsilon_i
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/Users/choat/Downloads/exam.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 387
Columns: 5
$ ach                  &lt;dbl&gt; 52.159780, 30.784999, 39.607737, 55.985351, 31.80…
$ learning_performance &lt;dbl&gt; 32.666667, 10.666667, 28.000000, 52.666667, 15.55…
$ ontime_class         &lt;chr&gt; "used to late", "used to late", "never late", "us…
$ engage               &lt;chr&gt; "no engage", "much engage", "much engage", "much …
$ practice             &lt;chr&gt; "do practice", "do not praction", "do not practio…</code></pre>
</div>
</div>
<p>สมมุติว่าวัตถุประสงค์การวิเคราะห์ เพื่อวิเคราะห์ความสัมพันธ์ระหว่าง ach กับ learning_performance โดยใช้ simple linear regression</p>
<section id="exploring-data" class="level3">
<h3 class="anchored" data-anchor-id="exploring-data">1. exploring data</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(ach, learning_performance) <span class="sc">%&gt;%</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           ach learning_performance
ach                  1.0000000            0.8457081
learning_performance 0.8457081            1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> learning_performance, <span class="at">y =</span> ach))<span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="fit-simple-regression" class="level3">
<h3 class="anchored" data-anchor-id="fit-simple-regression">2. fit simple regression</h3>
<p>การประมาณค่าพารามิเตอร์ใน linear regression ทุกโมเดลจะใช้ ordinary least squares (OLS)</p>
<p>วิธีการประมาณนี้จะพยายามหาค่าพารามิเตอร์ intercept และ slope ที่ทำให้ sum squared error น้อยที่สุด —&gt; แปลว่าต้องการโมเดล regression ที่ทำนายได้แม่นยำมากที่สุด หรือ bias น้อยที่สุด</p>
<p><span class="math display">\[
Q = \sum_{i=1}^n (Y_i - \hat{Y}_i)^2 = \sum_{i=1}^n (Y_i - \hat{\beta}_0 - \hat{\beta}_1X_i)^2
\]</span> ตอนประมาณค่าพารามิเตอร์จะใช้การหาอนุพันธ์ของ SSE เทียบกับพารามิเตอร์ intercept และ slope</p>
<p><span class="math display">\[
\frac{\partial Q}{\partial \beta_0}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>simple_reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(ach <span class="sc">~</span> learning_performance, <span class="at">data =</span> data)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ach ~ learning_performance, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.1638  -5.8006   0.6043   6.8305  23.2356 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          17.70386    0.95723    18.5   &lt;2e-16 ***
learning_performance  0.56536    0.01818    31.1   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.277 on 385 degrees of freedom
Multiple R-squared:  0.7152,    Adjusted R-squared:  0.7145 
F-statistic: 966.9 on 1 and 385 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>p1<span class="ot">&lt;-</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> learning_performance, <span class="at">y =</span> ach))<span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">17.7039</span> , <span class="at">slope =</span> <span class="fl">0.5654</span> , <span class="at">col =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">linewidth =</span> <span class="dv">2</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>p2<span class="ot">&lt;-</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> learning_performance, <span class="at">y =</span> ach))<span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">/</span>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ach         learning_performance ontime_class          engage         
 Min.   :-1.576   Min.   : 2.667       Length:387         Length:387        
 1st Qu.:31.132   1st Qu.:22.556       Class :character   Class :character  
 Median :43.873   Median :47.556       Mode  :character   Mode  :character  
 Mean   :43.607   Mean   :45.817                                            
 3rd Qu.:56.870   3rd Qu.:68.222                                            
 Max.   :83.415   Max.   :96.000                                            
   practice        
 Length:387        
 Class :character  
 Mode  :character  
                   
                   
                   </code></pre>
</div>
</div>
</section>
<section id="การแปลความหมายพารามเตอรในโมเดล" class="level3">
<h3 class="anchored" data-anchor-id="การแปลความหมายพารามเตอรในโมเดล">3. การแปลความหมายพารามิเตอร์ในโมเดล</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="dv">86</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.273618</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(simple_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ach ~ learning_performance, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.1638  -5.8006   0.6043   6.8305  23.2356 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          17.70386    0.95723    18.5   &lt;2e-16 ***
learning_performance  0.56536    0.01818    31.1   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.277 on 385 degrees of freedom
Multiple R-squared:  0.7152,    Adjusted R-squared:  0.7145 
F-statistic: 966.9 on 1 and 385 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(simple_reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: ach
                      Df Sum Sq Mean Sq F value    Pr(&gt;F)    
learning_performance   1  83212   83212  966.93 &lt; 2.2e-16 ***
Residuals            385  33132      86                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fl">966.9</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 31.09502</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="dv">83212</span><span class="sc">/</span> (<span class="dv">33132</span> <span class="sc">+</span><span class="dv">83212</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7152238</code></pre>
</div>
</div>
<ul>
<li>Residual standard error –&gt; square root ของ MSE ดัชนีตัวนี้ใช้บอกว่า ค่าทำนายของ regression model ของเรามีความคลาดเคลื่อนไปจากค่าจริงโดยเฉลี่ยกี่หน่วย (คะแนน)</li>
</ul>
<p>การแปลความหมายพารามิเตอร์หลัก ๆ ดูที่ intercept และ slope</p>
<ul>
<li>slope คือ อัตราการเปลี่ยนแปลงของ y เมื่อเทียบกับ –&gt; delta_y/delta_x</li>
</ul>
<p>ถ้า slope = 0.57 แปลว่า ถ้านักเรียนมี learning performance สูงขึ้น 1 หน่วย แล้ว ach ของนักเรียนมีแนวโน้มที่จะเพิ่มขึ้นโดยเฉลี่ย 0.57 คะแนน</p>
<ul>
<li>intercept คือ จุดตัดแกน y –&gt; ค่าของ y เมื่อ x = 0</li>
</ul>
<p>ถ้าเด็กไม่มี learning performance เลย (LP = 0) เด็กมีแนวโน้มที่จะมีคะแนน ach โดยเฉลี่ย 17.7 คะแนน</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fit_simreg <span class="ot">&lt;-</span> <span class="fu">lm</span>(ach <span class="sc">~</span> learning_performance, <span class="at">data =</span> data)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_simreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ach ~ learning_performance, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-29.1638  -5.8006   0.6043   6.8305  23.2356 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          17.70386    0.95723    18.5   &lt;2e-16 ***
learning_performance  0.56536    0.01818    31.1   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.277 on 385 degrees of freedom
Multiple R-squared:  0.7152,    Adjusted R-squared:  0.7145 
F-statistic: 966.9 on 1 and 385 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
<section id="multiple-regression" class="level2">
<h2 class="anchored" data-anchor-id="multiple-regression">Multiple Regression</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">count</span>(engage)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  engage              n
  &lt;chr&gt;           &lt;int&gt;
1 little engage      67
2 moderate engage    84
3 much engage       212
4 no engage          24</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  mutate(engage = factor(engage, levels=c("no engage","little engage",</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a> <span class="co">#                                         "moderate engage","much engage"))) %&gt;% </span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a> <span class="fu">mutate</span>(<span class="at">engage =</span> <span class="fu">fct_relevel</span>(engage, <span class="st">"no engage"</span>,<span class="st">"little engage"</span>,  <span class="st">"moderate engage"</span>,<span class="st">"much engage"</span>))  <span class="sc">%&gt;%</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="fu">with</span>(<span class="fu">lm</span>(ach <span class="sc">~</span> learning_performance <span class="sc">+</span> engage)) <span class="ot">-&gt;</span> fit_mulreg</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_mulreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ach ~ learning_performance + engage)

Residuals:
     Min       1Q   Median       3Q      Max 
-27.6449  -5.9326   0.4239   6.4016  24.7260 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           18.48425    1.99161   9.281   &lt;2e-16 ***
learning_performance   0.55225    0.01961  28.164   &lt;2e-16 ***
engagelittle engage   -2.21254    2.20469  -1.004    0.316    
engagemoderate engage -0.37247    2.15557  -0.173    0.863    
engagemuch engage      0.51921    2.04122   0.254    0.799    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.265 on 382 degrees of freedom
Multiple R-squared:  0.7181,    Adjusted R-squared:  0.7152 
F-statistic: 243.3 on 4 and 382 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><p>เมื่อควบคุมให้ตัวแปรอิสระอื่น ๆ คงที่ ถ้านักเรียนมี LP สูงขึ้น 1 คะแนน นักเรียนมีแนวโน้มที่จะมีค่าเฉลี่ย ach สูงขึ้น 0.55 คะแนน</p></li>
<li><p>เมื่อควบคุมให้ตัวแปรอิสระอื่น ๆ คงที่ นักเรียนที่มีส่วนร่วมในการเรียนน้อยมีแนวโน้มที่จะมี ach โดยเฉลี่ยต่ำกว่านักเรียนที่ไม่มีส่วนร่วมในการเรียน 2.21 คะแนน อย่างไรก็ตามความแตกต่างดังกล่าวไม่พบนัยสำคัญทางสถิติที่ระดับ .05</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fit_mulreg <span class="ot">&lt;-</span> <span class="fu">lm</span>(ach <span class="sc">~</span> learning_performance <span class="sc">+</span> engage, <span class="at">data =</span> data)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_mulreg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ach ~ learning_performance + engage, data = data)

Residuals:
     Min       1Q   Median       3Q      Max 
-27.6449  -5.9326   0.4239   6.4016  24.7260 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           16.27171    1.26921  12.820   &lt;2e-16 ***
learning_performance   0.55225    0.01961  28.164   &lt;2e-16 ***
engagemoderate engage  1.84006    1.54118   1.194   0.2332    
engagemuch engage      2.73175    1.38438   1.973   0.0492 *  
engageno engage        2.21254    2.20469   1.004   0.3162    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.265 on 382 degrees of freedom
Multiple R-squared:  0.7181,    Adjusted R-squared:  0.7152 
F-statistic: 243.3 on 4 and 382 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="regression-with-interaction" class="level2">
<h2 class="anchored" data-anchor-id="regression-with-interaction">Regression with Interaction</h2>
<p>อิทธิพลปฏิสัมพันธ์ (interaction effect) คืออิทธิพลรวมกันระหว่างตัวแปรอิสระอย่างน้อย 2 ตัวแปร ที่มีผลต่อตัวแปรตาม ที่เมื่อเกิดอิทธิพลของตัวแปรอิสระดังกล่าวจะมีแนวโน้มเปลี่ยนแปลงไปตามค่าของตัวแปรอิสระอื่น ๆ ที่อยู่ในกลุ่มปฏิสัมพันธ์เดียวกัน</p>
<p><img src="https://datakruroo.github.io/Programming/data_analysis/img/interaction.png" class="img-fluid"></p>
<section id="two-way-interaction-effect" class="level3">
<h3 class="anchored" data-anchor-id="two-way-interaction-effect">Two-way interaction effect</h3>
<ul>
<li><p><del>ตัวแปรอิสระทั้งสองเป็นตัวแปรจัดประเภท</del></p></li>
<li><p>ตัวแปรอิสระเป็นตัวแปรจัดประเภทและตัวแปรอิสระเชิงปริมาณ</p></li>
<li><p>ตัวแปรอิสระทั้งสองเป็นตัวแปรเชิงปริมาณ</p></li>
</ul>
<section id="ตวแปรอสระเปนตวแปรจดประเภทและตวแปรอสระเชงปรมาณ" class="level4">
<h4 class="anchored" data-anchor-id="ตวแปรอสระเปนตวแปรจดประเภทและตวแปรอสระเชงปรมาณ">ตัวแปรอิสระเป็นตัวแปรจัดประเภทและตัวแปรอิสระเชิงปริมาณ</h4>
<p>ใช้ชุดข้อมูล <a href="TeacherSalaryData.csv">teachersalary.csv</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"TeacherSalaryData.csv"</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 397
Columns: 7
$ ...1          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ rank          &lt;chr&gt; "Prof", "Prof", "AsstProf", "Prof", "Prof", "AssocProf",…
$ discipline    &lt;chr&gt; "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "…
$ yrs.since.phd &lt;dbl&gt; 19, 20, 4, 45, 40, 6, 30, 45, 21, 18, 12, 7, 1, 2, 20, 1…
$ yrs.service   &lt;dbl&gt; 18, 16, 3, 39, 41, 6, 23, 45, 20, 18, 8, 2, 1, 0, 18, 3,…
$ sex           &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male", "Male", …
$ salary        &lt;dbl&gt; 139750, 173200, 79750, 115000, 141500, 97000, 175000, 14…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>fit_interac1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(salary <span class="sc">~</span> yrs.service<span class="sc">*</span>discipline, <span class="at">data =</span> data)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_interac1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ yrs.service * discipline, data = data)

Residuals:
   Min     1Q Median     3Q    Max 
-86326 -19779  -4999  16091 102274 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              98038.0     3626.9   27.03  &lt; 2e-16 ***
yrs.service                526.8      150.1    3.51 0.000499 ***
disciplineB                857.4     4750.7    0.18 0.856873    
yrs.service:disciplineB    695.2      215.9    3.22 0.001388 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27540 on 393 degrees of freedom
Multiple R-squared:  0.1795,    Adjusted R-squared:  0.1733 
F-statistic: 28.67 on 3 and 393 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>fit_interac2 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rank =</span> <span class="fu">fct_relevel</span>(rank, <span class="st">"AsstProf"</span>, <span class="st">"AssocProf"</span>, <span class="st">"Prof"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">lm</span>(salary<span class="sc">~</span> yrs.service <span class="sc">+</span> discipline <span class="sc">+</span> yrs.service<span class="sc">:</span>discipline))</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_interac2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ yrs.service + discipline + yrs.service:discipline)

Residuals:
   Min     1Q Median     3Q    Max 
-86326 -19779  -4999  16091 102274 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              98038.0     3626.9   27.03  &lt; 2e-16 ***
yrs.service                526.8      150.1    3.51 0.000499 ***
disciplineB                857.4     4750.7    0.18 0.856873    
yrs.service:disciplineB    695.2      215.9    3.22 0.001388 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27540 on 393 degrees of freedom
Multiple R-squared:  0.1795,    Adjusted R-squared:  0.1733 
F-statistic: 28.67 on 3 and 393 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>การอ่านผล</p>
<ol type="1">
<li>เราสามารถประเมินอิทธิพลของ main effect ที่ไม่เกี่ยวข้องกับ interaction term ได้เลย</li>
</ol>
<ul>
<li><p>เมื่อควบคุมให้ตัวแปรอิสระอื่นคงที่ อาจารย์ที่เป็นรองศาสตราจารย์มีแนวโน้มจะมีเงินเดือนสูงกว่า ผศ. ประมาณ 14000 บท อย่างมีนัยสำคัญทางสถิติที่ระดับ .05 ()</p></li>
<li><p>เมื่อควบคุมให้ตัวแปรอิสระอื่นคงที่ ศาสตราจารย์ของมหาลัยมีแนวโน้มจะมีเงินเดือนสูงกว่า ผศ. ประมาณ 50000 บาท อย่างมีนัยสำคัญทางสถิติที่ระดับ .05</p></li>
</ul>
<ol start="2" type="1">
<li>พิจารณาส่วนปฏิสัมพันธ์</li>
</ol>
<ul>
<li><p>พิจารณา term ปฏิสัมพันธ์ก่อนว่ามีนัยสำคัญรึเปล่า (เชิงสถิติ/เชิงปฏฺิบัติ) ถ้าพบนัยสำคัญทางสถิติเราจะไม่อ่านผลที่ main effect</p></li>
<li><p>เราต้องไปประเมิน simple effect แทน</p>
<ul>
<li><p>ประเมินผลของ yrs.service ที่มีต่อ ach จำแนกตาม discipline A และ B &lt;– การวิเคราะห์ simple slope</p></li>
<li><p>ประเมินผลของ discipline ที่มีต่อ ach จำแนกตาม yrs.service</p></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>yrs.service))<span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="การวเคราะห-simple-slope-ของ-yrs.service-จำแนกตาม-discipline" class="level5">
<h5 class="anchored" data-anchor-id="การวเคราะห-simple-slope-ของ-yrs.service-จำแนกตาม-discipline">การวิเคราะห์ simple slope ของ yrs.service จำแนกตาม discipline</h5>
<p>วิเคราะห์อิทธิพลของ yrs.service ต่อ ach จำแนกตาม discipline</p>
<p>เราจะดู simple slope ของ cont. จำแนกตาม cat.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>simple_slopes <span class="ot">&lt;-</span> <span class="fu">emtrends</span>(fit_interac2, <span class="at">var =</span> <span class="st">"yrs.service"</span>, <span class="at">spec =</span> <span class="st">"discipline"</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="do">## slope ของ yrs.service จำแนกตาม discipline</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>simple_slopes </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> discipline yrs.service.trend  SE  df lower.CL upper.CL
 A                        527 150 393      232      822
 B                       1222 155 393      917     1527

Confidence level used: 0.95 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="do">## ความแตกต่างของ slope ของ yrs.service ระหว่าง 2 discipline</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrast</span>(simple_slopes, <span class="at">method =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast estimate  SE  df t.ratio p.value
 A - B        -695 216 393  -3.220  0.0014</code></pre>
</div>
</div>
<p>ลองใช้ <code>simple_slopes &lt;- emmeans(fit_interac1, pairwise ~ discipline | yrs.service)</code> ผลลัพธ์ที่ได้แตกต่างกันอย่างไร</p>
</section>
<section id="วเคราะห-simple-effect-ของ-discipline-บน-yrs.service" class="level5">
<h5 class="anchored" data-anchor-id="วเคราะห-simple-effect-ของ-discipline-บน-yrs.service">วิเคราะห์ simple effect ของ discipline บน yrs.service</h5>
<p>simple effect ของ discipline ที่วิเคราะห์ได้แต่ละค่าของ yrs.service</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ...1         rank            discipline        yrs.since.phd  
 Min.   :  1   Length:397         Length:397         Min.   : 1.00  
 1st Qu.:100   Class :character   Class :character   1st Qu.:12.00  
 Median :199   Mode  :character   Mode  :character   Median :21.00  
 Mean   :199                                         Mean   :22.31  
 3rd Qu.:298                                         3rd Qu.:32.00  
 Max.   :397                                         Max.   :56.00  
  yrs.service        sex                salary      
 Min.   : 0.00   Length:397         Min.   : 57800  
 1st Qu.: 7.00   Class :character   1st Qu.: 91000  
 Median :16.00   Mode  :character   Median :107300  
 Mean   :17.61                      Mean   :113706  
 3rd Qu.:27.00                      3rd Qu.:134185  
 Max.   :60.00                      Max.   :231545  </code></pre>
</div>
</div>
<p>ในทำนองเดียวกับ anova เราสามารถวิเคราะห์ simple effect ของ discipline แต่ในกรณีนี้จะเป็นการจำแนกตามระดับของ yrs.service ซึ่งมีจำนวนได้มากมาย</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      ...1         rank            discipline        yrs.since.phd  
 Min.   :  1   Length:397         Length:397         Min.   : 1.00  
 1st Qu.:100   Class :character   Class :character   1st Qu.:12.00  
 Median :199   Mode  :character   Mode  :character   Median :21.00  
 Mean   :199                                         Mean   :22.31  
 3rd Qu.:298                                         3rd Qu.:32.00  
 Max.   :397                                         Max.   :56.00  
  yrs.service        sex                salary      
 Min.   : 0.00   Length:397         Min.   : 57800  
 1st Qu.: 7.00   Class :character   1st Qu.: 91000  
 Median :16.00   Mode  :character   Median :107300  
 Mean   :17.61                      Mean   :113706  
 3rd Qu.:27.00                      3rd Qu.:134185  
 Max.   :60.00                      Max.   :231545  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">emmeans</span>(fit_interac2, pairwise <span class="sc">~</span> yrs.service <span class="sc">|</span> discipline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$emmeans
discipline = A:
 yrs.service emmean   SE  df lower.CL upper.CL
        17.6 107318 2077 393   103235   111401

discipline = B:
 yrs.service emmean   SE  df lower.CL upper.CL
        17.6 120420 1898 393   116688   124153

Confidence level used: 0.95 

$contrasts
discipline = A:
 contrast  estimate SE df z.ratio p.value
 (nothing)   nonEst NA NA      NA      NA

discipline = B:
 contrast  estimate SE df z.ratio p.value
 (nothing)   nonEst NA NA      NA      NA</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>emmeans <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(fit_interac2, pairwise <span class="sc">~</span> yrs.service <span class="sc">|</span> discipline, </span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">at =</span> <span class="fu">list</span>(<span class="at">yrs.service =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">8</span>,<span class="dv">27</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>emmeans<span class="sc">$</span>emmeans <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>emmean, <span class="at">y=</span><span class="fu">factor</span>(yrs.service), <span class="at">col =</span>discipline ))<span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lower.CL, <span class="at">xmax =</span> upper.CL), <span class="at">width =</span> <span class="fl">0.1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>เราอาจ plot แผนภาพแสดงความสัมพันธ์แบบ interaction ได้ง่าย ๆ ดังนี้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>fit_interac2 <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = salary ~ yrs.service + discipline + yrs.service:discipline)

Residuals:
   Min     1Q Median     3Q    Max 
-86326 -19779  -4999  16091 102274 

Coefficients:
                        Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              98038.0     3626.9   27.03  &lt; 2e-16 ***
yrs.service                526.8      150.1    3.51 0.000499 ***
disciplineB                857.4     4750.7    0.18 0.856873    
yrs.service:disciplineB    695.2      215.9    3.22 0.001388 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 27540 on 393 degrees of freedom
Multiple R-squared:  0.1795,    Adjusted R-squared:  0.1733 
F-statistic: 28.67 on 3 and 393 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="do">## partial dependence plot (pdp)</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="do">### 1. สร้าง grid ที่เป็น combination ระหว่างตัวแปรอิสระที่ interact กันก่อน</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="do">### สร้าง grid ของ yrs.service</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>yrs_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fu">min</span>(data<span class="sc">$</span>yrs.service), <span class="fu">max</span>(data<span class="sc">$</span>yrs.service), <span class="dv">2</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="do">### สร้าง grid ของ discipline</span></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>dis_grid <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"A"</span>,<span class="st">"B"</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a><span class="do">### combination ของ grid</span></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="fu">expand_grid</span>(<span class="at">yrs.service =</span> yrs_grid, <span class="at">discipline =</span> dis_grid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 62 × 2
   yrs.service discipline
         &lt;dbl&gt; &lt;chr&gt;     
 1           0 A         
 2           0 B         
 3           2 A         
 4           2 B         
 5           4 A         
 6           4 B         
 7           6 A         
 8           6 B         
 9           8 A         
10           8 B         
# ℹ 52 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="do">### ทำหน้าที่เป็นค่าของตัวแปรอิสระที่ต้องการนำไปหาค่าทำนาย</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>grid_pred <span class="ot">&lt;-</span> <span class="fu">expand_grid</span>(<span class="at">yrs.service =</span> yrs_grid,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">discipline =</span> <span class="fu">unique</span>(data<span class="sc">$</span>discipline))</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit_interac2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
120891.33 118447.34 102561.41 146553.21 148997.20 106227.40 127001.30 153885.18 
        9        10        11        12        13        14        15        16 
123335.32 120891.33 108671.39 101339.42 100117.42  98895.43 120891.33 102561.41 
       17        18        19        20        21        22        23        24 
123335.32 115950.24 110155.11 117003.90 111735.60 114369.75 113842.92 108047.80 
       25        26        27        28        29        30        31        32 
102252.68 102252.68 110155.11 102561.41  98895.43 108671.39 103783.41 101339.42 
       33        34        35        36        37        38        39        40 
109893.38 101339.42 101339.42  98895.43 124557.31 103783.41 136777.26 109893.38 
       41        42        43        44        45        46        47        48 
101339.42 127001.30 131889.28 145331.22 122113.32 117225.35 133111.27 122113.32 
       49        50        51        52        53        54        55        56 
129445.29 100117.42 133111.27 112337.37 102561.41 109893.38 112337.37 105005.40 
       57        58        59        60        61        62        63        64 
124557.31 108671.39 109893.38 102561.41 108671.39 101339.42 136777.26 112337.37 
       65        66        67        68        69        70        71        72 
102561.41 108671.39 113559.36 136777.26 119669.34 142887.23 101339.42 153885.18 
       73        74        75        76        77        78        79        80 
122113.32 140443.24 127001.30 102561.41 102561.41 122113.32 100117.42 101339.42 
       81        82        83        84        85        86        87        88 
133111.27 118447.34 123335.32 101339.42 120891.33 116003.35 144109.22 101339.42 
       89        90        91        92        93        94        95        96 
129445.29 107449.39 105005.40 107449.39 107449.39 145331.22 123335.32  98895.43 
       97        98        99       100       101       102       103       104 
113559.36 107449.39 116003.35 130667.28 129445.29 127001.30 105005.40 116003.35 
      105       106       107       108       109       110       111       112 
103306.33 112789.26 102252.68 102252.68 102252.68 114369.75 106467.31 106467.31 
      113       114       115       116       117       118       119       120 
 98564.87 117530.73  98038.04 102779.50 113316.09 117003.90  98564.87  99618.53 
      121       122       123       124       125       126       127       128 
105413.65 114896.58 109628.29 109628.29 109628.29 123852.68 111735.60  98038.04 
      129       130       131       132       133       134       135       136 
113842.92  99091.70 102779.50 128067.31 102252.68  98564.87 111208.77 107520.97 
      137       138       139       140       141       142       143       144 
105413.65 105413.65 101725.85 107520.97 102252.68 103306.33 103833.16 102561.41 
      145       146       147       148       149       150       151       152 
131889.28 133111.27 103783.41 131889.28 130667.28 102561.41 113559.36 103783.41 
      153       154       155       156       157       158       159       160 
109893.38 111115.37  98895.43 124557.31 120891.33  98895.43 106227.40 118447.34 
      161       162       163       164       165       166       167       168 
101339.42 122113.32 107449.39 102561.41  98895.43 108671.39 118447.34 122113.32 
      169       170       171       172       173       174       175       176 
106227.40 120891.33 105005.40 122113.32 128223.30 123335.32 106227.40 129445.29 
      177       178       179       180       181       182       183       184 
107449.39 109893.38 116003.35 102561.41 112337.37 105005.40 108671.39 125779.31 
      185       186       187       188       189       190       191       192 
127001.30 135555.26 111115.37 111115.37 133111.27 122113.32 109893.38 125779.31 
      193       194       195       196       197       198       199       200 
120891.33 122113.32 163661.13 107449.39 103783.41 103783.41 139221.25 125779.31 
      201       202       203       204       205       206       207       208 
103783.41 147775.21 119669.34 119669.34 105005.40 101339.42 139221.25 120891.33 
      209       210       211       212       213       214       215       216 
101339.42 123335.32 102561.41 146553.21 107449.39 122113.32 100117.42 112337.37 
      217       218       219       220       221       222       223       224 
112337.37 125779.31 107449.39 112337.37 124557.31 111115.37 106227.40 123335.32 
      225       226       227       228       229       230       231       232 
116477.07 108574.63  98564.87 101725.85 103833.16 118057.55 112262.43 110681.94 
      233       234       235       236       237       238       239       240 
108047.80 108047.80  99618.53 106994.14 111208.77 101199.02 119111.21 101199.02 
      241       242       243       244       245       246       247       248 
 99618.53 113842.92 117530.73 110155.11 110155.11 103833.16 110155.11 107520.97 
      249       250       251       252       253       254       255       256 
110155.11 101725.85 118584.38 102252.68 104359.99  99091.70 101725.85 102252.68 
      257       258       259       260       261       262       263       264 
109628.29 110155.11  99618.53 113842.92 115423.41 121745.36 111735.60 114369.75 
      265       266       267       268       269       270       271       272 
116477.07 113842.92 120691.70 103306.33 121218.53 101725.85 119111.21 107520.97 
      273       274       275       276       277       278       279       280 
 98564.87 100145.36  99618.53 101199.02 123325.85 112262.43 107520.97 122272.19 
      281       282       283       284       285       286       287       288 
118057.55 112262.43 124906.34 120691.70 101199.02 123852.68 112262.43  98038.04 
      289       290       291       292       293       294       295       296 
112262.43 100672.19 101725.85 112789.26 102779.50  98564.87 101725.85 117003.90 
      297       298       299       300       301       302       303       304 
107520.97 103833.16 120691.70 118584.38 117003.90 106467.31 104886.82 100145.36 
      305       306       307       308       309       310       311       312 
121218.53 114369.75 100145.36 112789.26  98038.04 105940.48 101725.85 102779.50 
      313       314       315       316       317       318       319       320 
108047.80 116477.07 101199.02 102561.41 109893.38 153885.18 118447.34 117225.35 
      321       322       323       324       325       326       327       328 
127001.30 109893.38 112337.37 117225.35 136777.26 103783.41 117225.35 144109.22 
      329       330       331       332       333       334       335       336 
111115.37 127001.30 172215.10 109893.38 111115.37 122113.32 106227.40 145331.22 
      337       338       339       340       341       342       343       344 
127001.30 113559.36 129445.29 117225.35 112337.37 119669.34 145331.22 136777.26 
      345       346       347       348       349       350       351       352 
141665.23 111115.37 131889.28 139221.25 102561.41 133111.27 158773.16 145331.22 
      353       354       355       356       357       358       359       360 
131889.28 123335.32 100117.42 124557.31 119111.21 116477.07 105413.65 100145.36 
      361       362       363       364       365       366       367       368 
103833.16 105940.48 113842.92 106994.14 120691.70 119111.21 103306.33  98564.87 
      369       370       371       372       373       374       375       376 
113842.92 114369.75 102252.68 108574.63 101725.85 111735.60 108047.80 111735.60 
      377       378       379       380       381       382       383       384 
 98564.87  99618.53 118057.55 102252.68  99618.53 110155.11 100672.19 121218.53 
      385       386       387       388       389       390       391       392 
109101.46 102779.50 112262.43 105940.48 117003.90 107520.97 108047.80 108047.80 
      393       394       395       396       397 
113842.92 108047.80 111208.77 105940.48 100145.36 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(fit_interac2, <span class="at">newdata =</span> grid_pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        1         2         3         4         5         6         7         8 
 98895.43  98038.04 101339.42  99091.70 103783.41 100145.36 106227.40 101199.02 
        9        10        11        12        13        14        15        16 
108671.39 102252.68 111115.37 103306.33 113559.36 104359.99 116003.35 105413.65 
       17        18        19        20        21        22        23        24 
118447.34 106467.31 120891.33 107520.97 123335.32 108574.63 125779.31 109628.29 
       25        26        27        28        29        30        31        32 
128223.30 110681.94 130667.28 111735.60 133111.27 112789.26 135555.26 113842.92 
       33        34        35        36        37        38        39        40 
137999.25 114896.58 140443.24 115950.24 142887.23 117003.90 145331.22 118057.55 
       41        42        43        44        45        46        47        48 
147775.21 119111.21 150219.20 120164.87 152663.18 121218.53 155107.17 122272.19 
       49        50        51        52        53        54        55        56 
157551.16 123325.85 159995.15 124379.51 162439.14 125433.16 164883.13 126486.82 
       57        58        59        60        61        62 
167327.12 127540.48 169771.11 128594.14 172215.10 129647.80 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>grid_pred <span class="sc">%&gt;%</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pred =</span> <span class="fu">predict</span>(fit_interac2, <span class="at">newdata =</span> grid_pred)) <span class="sc">%&gt;%</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> yrs.service, <span class="at">y =</span> pred, <span class="at">color =</span> discipline)) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>simple_slopes </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> discipline yrs.service.trend  SE  df lower.CL upper.CL
 A                        527 150 393      232      822
 B                       1222 155 393      917     1527

Confidence level used: 0.95 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>p1<span class="ot">&lt;-</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>yrs.service, <span class="at">y=</span>salary))<span class="sc">+</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>p2<span class="ot">&lt;-</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>yrs.service, <span class="at">y=</span>salary, <span class="at">col =</span> discipline))<span class="sc">+</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)</span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">/</span>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="ตวแปรอสระทงสองเปนตวแปรเชงปรมาณ" class="level4">
<h4 class="anchored" data-anchor-id="ตวแปรอสระทงสองเปนตวแปรเชงปรมาณ">ตัวแปรอิสระทั้งสองเป็นตัวแปรเชิงปริมาณ</h4>
<p><img src="img/interaction2.png" class="img-fluid" style="width:50.0%"></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"eff.csv"</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 100
Columns: 4
$ id    &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…
$ seef  &lt;dbl&gt; 5.7599470, 3.7773884, 5.4455399, 13.5313592, 9.4946747, 2.341611…
$ motiv &lt;dbl&gt; 5.472301, 3.966361, 4.874800, 5.928663, 5.868340, 4.150825, 4.61…
$ eff   &lt;dbl&gt; 39, 28, 41, 40, 38, 31, 20, 33, 42, 61, 33, 33, 24, 23, 41, 47, …</code></pre>
</div>
</div>
<p><span class="math display">\[
eff = \beta_0 + \beta_1motiv + \beta_2seef + \beta_3motiv \times seef + \epsilon
\]</span></p>
<p>$$ eff = _0 + _1motiv + (_2seef + _3motiv seef) + </p>
<p>$$</p>
<p>$$ eff = _0 + _1motiv + (_2 + _3motiv)seef + </p>
<p>$$</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id              seef             motiv            eff       
 Min.   :  1.00   Min.   : 0.3818   Min.   :2.371   Min.   :18.00  
 1st Qu.: 25.75   1st Qu.: 3.3801   1st Qu.:4.209   1st Qu.:28.00  
 Median : 50.50   Median : 6.2057   Median :5.062   Median :34.50  
 Mean   : 50.50   Mean   : 6.2896   Mean   :5.048   Mean   :35.77  
 3rd Qu.: 75.25   3rd Qu.: 8.1899   3rd Qu.:5.954   3rd Qu.:41.00  
 Max.   :100.00   Max.   :15.4602   Max.   :7.448   Max.   :77.00  </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>fit_interac3 <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">lm</span>(eff <span class="sc">~</span> motiv <span class="sc">+</span> seef <span class="sc">+</span> motiv<span class="sc">:</span>seef))</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_interac3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = eff ~ motiv + seef + motiv:seef)

Residuals:
     Min       1Q   Median       3Q      Max 
-11.4653  -3.3952  -0.9439   3.2766  12.9369 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  13.6969     4.9097   2.790  0.00636 ** 
motiv         1.6534     0.9545   1.732  0.08644 .  
seef          7.7468     0.7112  10.893  &lt; 2e-16 ***
motiv:seef   -1.0891     0.1356  -8.034 2.41e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.958 on 96 degrees of freedom
Multiple R-squared:  0.8065,    Adjusted R-squared:  0.8004 
F-statistic: 133.3 on 3 and 96 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>ดังนั้นเราสรุปได้ว่า</p>
<p>อิทธิพลของ seef ที่มีต่อ eff อธิบายได้ด้วยสมการ 7.75 - 1.09 x motiv</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>motiv<span class="ot">&lt;-</span><span class="dv">3</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>slope_seef <span class="ot">&lt;-</span> <span class="fl">7.75</span> <span class="sc">-</span> <span class="fl">1.09</span><span class="sc">*</span>motiv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>motiv<span class="ot">&lt;-</span><span class="fl">5.048</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>slope_seef <span class="ot">&lt;-</span> <span class="fl">7.75</span> <span class="sc">-</span> <span class="fl">1.09</span><span class="sc">*</span>motiv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> </span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>seef, <span class="at">y=</span>eff))<span class="sc">+</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> F)<span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">13.6969</span>,<span class="at">slope =</span> <span class="fl">4.48</span>, <span class="at">col =</span><span class="st">"black"</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">13.6969</span>,<span class="at">slope =</span> <span class="fl">2.24768</span>, <span class="at">col =</span><span class="st">"black"</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fl">13.6969</span>,<span class="at">slope =</span> <span class="fl">0.12</span>, <span class="at">col =</span><span class="st">"black"</span>, <span class="at">linetype =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>,<span class="dv">80</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>simple_slope_seef <span class="ot">&lt;-</span> <span class="fu">emtrends</span>(fit_interac3, <span class="at">var=</span><span class="st">"seef"</span>, <span class="at">spec =</span> <span class="st">"motiv"</span>,</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">at =</span> <span class="fu">list</span>(<span class="at">motiv=</span> <span class="fu">c</span>(<span class="fl">4.209</span>,<span class="fl">5.062</span>,<span class="fl">5.954</span>)))</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>simple_slope_seef <span class="sc">%&gt;%</span> <span class="fu">contrast</span>(<span class="at">method =</span> <span class="st">"pairwise"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast                estimate    SE df t.ratio p.value
 motiv4.209 - motiv5.062    0.929 0.116 96   8.034  &lt;.0001
 motiv4.209 - motiv5.954    1.901 0.237 96   8.034  &lt;.0001
 motiv5.062 - motiv5.954    0.972 0.121 96   8.034  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>simple_slope_seef <span class="sc">%&gt;%</span> <span class="fu">data.frame</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  motiv seef.trend        SE df  lower.CL upper.CL
1 4.209   3.162659 0.1894318 96 2.7866394 3.538678
2 5.062   2.233633 0.1414366 96 1.9528832 2.514382
3 5.954   1.262131 0.1788933 96 0.9070302 1.617231</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>seef, <span class="at">y=</span>eff))<span class="sc">+</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> ,<span class="at">slope =</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ggeffects")</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggeffects)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpredict</span>(fit_interac3, <span class="at">terms =</span> <span class="fu">c</span>(<span class="st">"seef"</span>, <span class="st">"motiv"</span>)) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>data <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id              seef             motiv            eff       
 Min.   :  1.00   Min.   : 0.3818   Min.   :2.371   Min.   :18.00  
 1st Qu.: 25.75   1st Qu.: 3.3801   1st Qu.:4.209   1st Qu.:28.00  
 Median : 50.50   Median : 6.2057   Median :5.062   Median :34.50  
 Mean   : 50.50   Mean   : 6.2896   Mean   :5.048   Mean   :35.77  
 3rd Qu.: 75.25   3rd Qu.: 8.1899   3rd Qu.:5.954   3rd Qu.:41.00  
 Max.   :100.00   Max.   :15.4602   Max.   :7.448   Max.   :77.00  </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="polynomial-regression" class="level2">
<h2 class="anchored" data-anchor-id="polynomial-regression">Polynomial Regression</h2>
<p>สมการถดถอยพหุนาม</p>
<p>ความสัมพันธ์ระหว่างตัวแปรบนโลก อาจจำแนกได้เป็น 2 ลักษณะ</p>
<ul>
<li><p>linear relationship</p></li>
<li><p>non-linear relationship</p></li>
</ul>
<p>โมเดลการวิเคราะห์ความสัมพันธ์ระหว่างตัวแปรอาจจำแนกได้เป็น 2 ลักษณะเช่นกัน</p>
<ul>
<li><p>linear (in parameters) model</p></li>
<li><p>non-linear model</p></li>
</ul>
<p><span class="math display">\[
y = mx + c
\]</span> <span class="math display">\[
y = ax^2+bx+c
\]</span></p>
<p><span class="math display">\[
y = \frac{exp(ax+b)}{1+exp(ax+b)}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggforce)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y=</span>lifeExp))<span class="sc">+</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb78-9"><a href="#cb78-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>การสร้าง term polynomial อาจทำได้สองวิธีการ วิธีการแรกคือการใช้ฟังก์ชัน identity function (<code>I()</code>) และวิธีการที่สองคือการใช้ <code>poly()</code> ความแตกต่างระหว่างการสร้างเทอมพหุนามของทั้งสองวิธีการคือ</p>
<ul>
<li><p><code>I()</code> เป็นวิธีการสร้างพหุนามโดยตรง โดยเราจะใส่ตัวแปรที่ต้องการยกกำลังในฟังก์ชันนี้ ตัวอย่างเช่น I(x^2) หมายถึงการสร้างเทอม x^2 ที่ใช้ในโมเดลการถดถอย ดังนั้นการแปลความหมาย slope ของตัวแปรที่เป็นพหุนามนี้สามารถทำได้อย่างตรงไปตรงมา เพราะตัวแปรต่าง ๆ อยู่ในสเกลต้นฉบับ</p></li>
<li><p>ปัญหาหนึ่งของการใช้ <code>I()</code> คือ multicollinearity!!!</p></li>
<li><p><code>poly()</code> จะสร้างเทอมพหุนามที่เรียกว่า orthogonal polynomial ซึ่งจะทำให้เราไม่ต้องกังวลเรื่อง multicollinearity แต่ต้องแลกมาด้วยการแปลความหมายความสัมพันธ์ที่ยาก เพราะตัวแปรที่ถูกแปลงเป็น orthogonal polynomial จะอยู่คนละสเกลกับตัวแปรเดิม การแปลงลักษณะนี้จึงเหมาะกับวัตถุประสงค์ในการทำนายมากกว่าอธิบายความสัมพันธ์ื</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>cubic_fit <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">lm</span>(lifeExp <span class="sc">~</span> gdpPercap <span class="sc">+</span> <span class="fu">I</span>(gdpPercap<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">I</span>(gdpPercap<span class="sc">^</span><span class="dv">3</span>))) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math display">\[
lifeExp = (5.296e+01) + (2.734e-03)gdpPercap - (9.270e-08)gdpPercap^2 + (1.009e-12)gdpPercap^3
\]</span><br>
</p>
<section id="ปญหา-multicollinearity-ใน-polynomial-regression" class="level3">
<h3 class="anchored" data-anchor-id="ปญหา-multicollinearity-ใน-polynomial-regression">ปัญหา Multicollinearity ใน Polynomial Regression</h3>
<p>variance inflation factor –&gt; เป็นดัชนีที่ใช้วัด multicollinearity ของตัวแปรอิสระในโมเดล regression ถ้าค่า VIF มีค่ามากกว่า 10 แสดงว่ามี multicollinearity ในโมเดล</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("car")</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(cubic_fit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     gdpPercap I(gdpPercap^2) I(gdpPercap^3) 
      50.24411      260.77975      101.25863 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x =</span> gdpPercap,</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">x2 =</span>gdpPercap<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x3 =</span> gdpPercap<span class="sc">^</span><span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(x,x2,x3) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x        x2        x3
x  1.0000000 0.9578118 0.8872893
x2 0.9578118 1.0000000 0.9792936
x3 0.8872893 0.9792936 1.0000000</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="do">## correlation matrix between centering variables</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x =</span> gdpPercap,</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x2 =</span>gdpPercap<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">x3 =</span> gdpPercap<span class="sc">^</span><span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x_center =</span> x<span class="sc">-</span><span class="fu">mean</span>(x),</span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">x_center2 =</span> x_center<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x_center3 =</span> x_center<span class="sc">^</span><span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb84-10"><a href="#cb84-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(x_center, x_center2,x_center3) <span class="sc">%&gt;%</span> <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x_center x_center2 x_center3
x_center  1.0000000 0.7993676 0.8129349
x_center2 0.7993676 1.0000000 0.9654560
x_center3 0.8129349 0.9654560 1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="do">## scatter plot</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x =</span> gdpPercap,</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">x2 =</span>gdpPercap<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">x3 =</span> gdpPercap<span class="sc">^</span><span class="dv">3</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">x_center =</span> x<span class="sc">-</span><span class="fu">mean</span>(x),</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">x_center2 =</span> x_center<span class="sc">^</span><span class="dv">2</span>,</span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">x_center3 =</span> x_center<span class="sc">^</span><span class="dv">3</span>) <span class="sc">%&gt;%</span></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(x_center, x_center2,x_center3) <span class="sc">%&gt;%</span> </span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x_center,x_center3 ))<span class="sc">+</span></span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>cubic_fit <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">with</span>(<span class="fu">lm</span>(lifeExp <span class="sc">~</span> <span class="fu">poly</span>(gdpPercap, <span class="dv">3</span>)))</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>cubic_fit <span class="sc">%&gt;%</span> <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = lifeExp ~ poly(gdpPercap, 3))

Residuals:
    Min      1Q  Median      3Q     Max 
-23.954  -3.373   1.044   4.933  15.151 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          67.0074     0.6425 104.295  &lt; 2e-16 ***
poly(gdpPercap, 3)1  97.2925     7.6560  12.708  &lt; 2e-16 ***
poly(gdpPercap, 3)2 -48.2958     7.6560  -6.308 3.58e-09 ***
poly(gdpPercap, 3)3  25.7821     7.6560   3.368 0.000983 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7.656 on 138 degrees of freedom
Multiple R-squared:  0.6064,    Adjusted R-squared:  0.5979 
F-statistic: 70.88 on 3 and 138 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
</section>
<section id="regression-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="regression-diagnostics">Regression Diagnostics</h2>
<p>regression เป็นโมเดลทางสถิติแบบ parametric ที่การใช้งานจะต้องอยู่ภายใต้ข้อตกลงเบื้องต้นของโมเดลที่ค่อนข้าง strict (แต่ก็ไม่ได้แปลว่าต้อง strict มาก ๆ )</p>
<ul>
<li><p>Independence</p></li>
<li><p>Linearity</p></li>
<li><p>Normality</p></li>
<li><p>Homoscedasticity</p></li>
<li><p>No Missing Values</p></li>
<li><p>No Influential Outlier</p>
<ul>
<li>Outlier คือ ค่าสังเกตที่ทำนายไม่ได้หรือมีประสิทธิภาพการทำนายด้วย regression ต่ำ (กล่าวคือมีค่าสัมบูรณ์ของ residual ที่มากเกินไป)</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y=</span>lifeExp))<span class="sc">+</span></span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()<span class="sc">+</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ellipse</span>(<span class="at">data =</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>                        <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">filter</span>(lifeExp <span class="sc">&lt;</span> <span class="dv">60</span> <span class="sc">&amp;</span> gdpPercap <span class="sc">&gt;</span> <span class="dv">8000</span>),</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>               <span class="fu">aes</span>(<span class="at">x0 =</span> <span class="fu">mean</span>(gdpPercap), <span class="at">y0 =</span> <span class="fu">mean</span>(lifeExp), </span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>                   <span class="at">a =</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(gdpPercap), <span class="at">b =</span> <span class="dv">2</span><span class="sc">*</span><span class="fu">sd</span>(lifeExp), <span class="at">angle =</span> <span class="dv">0</span>),</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>               <span class="at">color =</span> <span class="st">'maroon'</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">fill =</span> <span class="cn">NA</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Leverage value คือ combination ของค่าสังเกตของตัวแปรอิสระที่ผิดปกติ กล่าวคือเป็น outlier ใน feature space ค่า leverage ไม่จำเป็นต้องมีผลต่อค่าของเส้นถดถอยเสมอไป มันเพียงแค่บอกว่าจุดนั้นอยู่ห่างไกลและมีศักยภาพที่จะส่งผลกระทบต่อโมเดล</li>
</ul>
<p><span class="math display">\[
h_{ii} = x_i^T (X^T X)^{-1} x_i
\]</span> ค่า <span class="math inline">\(h_{ii}\)</span> มีค่าอยู่ในช่วง [0,1] ถ้ามีค่าใกล้ 1.0 แสดงว่าค่าสังเกตของตัวแปรอิสระนั้นมีแนวโน้มอยู่ใกล้จากแนวโน้มส่วนใหญ่</p>
<ul>
<li>Influential observation คือค่าสังเกตที่มีอิทธิพลต่อการประมาณค่าพารามิเตอร์ในโมเดลมากกว่าปกติ การประเมินค่าสังเกตประเภทนี้ทำได้ด้วยสถิติ Cook’s distance</li>
</ul>
<p><span class="math display">\[
D_i = \frac{(e_i^2)}{p \cdot MSE} \left( \frac{h_{ii}}{(1 - h_{ii})^2} \right)
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y=</span>lifeExp))<span class="sc">+</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb90-6"><a href="#cb90-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span>
<span id="cb90-7"><a href="#cb90-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-8"><a href="#cb90-8" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> gapminder <span class="sc">%&gt;%</span> </span>
<span id="cb90-9"><a href="#cb90-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(year<span class="sc">==</span><span class="st">"2007"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb90-10"><a href="#cb90-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(gdpPercap <span class="sc">&lt;</span> <span class="dv">10000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb90-11"><a href="#cb90-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> gdpPercap, <span class="at">y=</span>lifeExp))<span class="sc">+</span></span>
<span id="cb90-12"><a href="#cb90-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb90-13"><a href="#cb90-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span>
<span id="cb90-14"><a href="#cb90-14" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb90-15"><a href="#cb90-15" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">/</span>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="regression-remedials" class="level2">
<h2 class="anchored" data-anchor-id="regression-remedials">Regression Remedials</h2>
<ol type="1">
<li>Linearity</li>
</ol>
<ul>
<li><p>เพิ่ม polynomial หรือ interaction terms เพื่อเพิ่มความซับซ้อนของโมเดล</p></li>
<li><p>แปลงข้อมูลด้วยการใช้ log, square root, หรือการแปลงเชิงเส้นตรงแบบอื่น ๆ</p></li>
<li><p>ใช้ Multivariate Adaptive Regression Splines (MARs) Generalized Additive Models (GAMs) เพื่อจับความสัมพันธ์ที่ไม่เป็นเชิงเส้น</p></li>
</ul>
<ol start="2" type="1">
<li>Normality</li>
</ol>
<ul>
<li><p>แปลงข้อมูล (log-transformation, square root, Box-Cox) เพื่อให้ residuals เป็นปกติมากขึ้น</p></li>
<li><p>ใช้ robust regression เพื่อทนทานต่อผลกระทบของ outliers</p></li>
<li><p>เพิ่มตัวแปรอิสระหรือเทอมของตัวแปรอิสระที่อาจหายไปเพื่อปรับปรุงการกระจายของ residuals</p></li>
</ul>
<ol start="3" type="1">
<li>Homoscedasticity</li>
</ol>
<ul>
<li><p>แปลงค่าตัวแปรตาม (เช่น log, square root) เพื่อลดความแปรปรวน</p></li>
<li><p>ใช้ Weighted Least Squares (WLS) เพื่อปรับน้ำหนักให้กับจุดข้อมูลที่มีความแปรปรวนต่างกัน</p></li>
<li><p>ใช้ heteroscedasticity-robust standard errors เพื่อปรับ standard errors ของโมเดล</p></li>
</ul>
<ol start="4" type="1">
<li>No Influential Ouliers</li>
</ol>
<ul>
<li><p>ลบหรือปรับค่าสังเกตที่ถูกระบุว่าเป็น influential outiers</p></li>
<li><p>ใช้ robust regression</p></li>
</ul>
</section>
<section id="model-selection" class="level2">
<h2 class="anchored" data-anchor-id="model-selection">Model Selection</h2>
<p>ในบริบทของการวิเคราะห์การถดถอย โดยปกติการคัดเลือกโมเดลส่วนหลัก ๆ จะเกี่ยวข้องกับการคัดเลือกตัวแปรอิสระเข้าสู่โมเดล และอีกส่วนหนึ่งคือการกำหนด functional form ของโมเดล ในบทเรียนนี้จะกล่าวถึงส่วน feature selection</p>
<p>การทำ feature selection คือการคัดกรองตัวแปรที่ไม่มีสาระสำคัญหรือมีความสำคัญน้อยในการพัฒนาโมเดลออกไป</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD

F1--&gt;X1((X))
F2--&gt;A[F2]
F3--&gt;B[F3]
F4--&gt;X2((X))
F5--&gt;X3((X))
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>การคัดเลือกตัวแปรอิสระเข้าสู่โมเดลมีหลายขั้นตอน อาจจะจำแนกออกเป็นสองประเภทใหญ่ ได้แก่ theory-driven และ data-driven โดยที่ theory-driven จะใช้ความรู้ที่มีอยู่จากงานวิจัยหรือทฤษฎีที่เกี่ยวข้องเพื่อกำหนดและคัดเลือกตัวแปร ในขณะที่ data-driven จะใช้ข้อมูลที่มีอยู่เพื่อคัดเลือกตัวแปรอิสระที่มีความเหมาะสมและมีประสิทธิภาพในการทำนายเข้าสู่โมเดล</p>
<ul>
<li><p>filter methods</p></li>
<li><p>wrapper methods</p></li>
<li><p>embedded methods</p></li>
</ul>
<section id="กจกรรมท-1-ทำลองวเคราะหการถดถอย" class="level3">
<h3 class="anchored" data-anchor-id="กจกรรมท-1-ทำลองวเคราะหการถดถอย">กิจกรรมที่ 1 ทำลองวิเคราะห์การถดถอย</h3>
<p>ลองทำ regression analysis เพื่อสร้างโมเดลทำนาย student_outcome_online แล้วพิจารณาผลลัพธ์ที่ได้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>large_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"/Users/choat/Downloads/onlinelearning_miss.csv"</span>)</span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>large_data <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,000
Columns: 50
$ ...1                                       &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, …
$ X                                          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, …
$ `ประเภทสถานศึกษา`                           &lt;chr&gt; "โรงเรียนมัธยมศึกษา", "โรงเรียน…
$ `ที่ตั้งสถานศึกษา`                              &lt;chr&gt; "กลาง", "กลาง", "กลาง", "กล…
$ `จำนวนรายวิชาที่ลงทะเบียน`                     &lt;dbl&gt; 8, 8, 8, 7, 7, 7, 8, 7, 8, …
$ `จำนวนรายวิชาonline`                        &lt;dbl&gt; 4, 8, 8, 7, 7, 7, 3, 7, 1, …
$ `จำนวนรายวิชาonsite`                        &lt;dbl&gt; 4, 0, 0, 0, 0, 0, 5, 0, 7, …
$ `ระดับความพร้อมสถานศึกษา`                     &lt;dbl&gt; 1, 3, 2, 3, 2, 2, 3, 3, 3, …
$ videoConference                            &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 1, 0, 1, …
$ Live                                       &lt;dbl&gt; 0, 1, 1, 1, 0, 0, 0, 1, 0, …
$ LMS                                        &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 0, …
$ groupChat                                  &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 0, 1, …
$ email                                      &lt;dbl&gt; 1, 0, 0, 1, 0, 0, 0, 0, 1, …
$ collapApps                                 &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ clipVideo                                  &lt;dbl&gt; 0, 1, 1, 1, 0, 1, 1, 1, 1, …
$ `อายุเฉลี่ยผู้สอน`                              &lt;dbl&gt; 1, 1, 2, 1, 1, 1, 1, 1, 1, …
$ `ภาพรวมความสามารถในการใช้สื่อเทคโนโลยีของผู้สอน` &lt;dbl&gt; 2, 2, 3, 3, 2, 3, 3, 3, 3, …
$ climate.online1                            &lt;dbl&gt; 3, 5, 3, 5, 5, 4, 4, NA, 3,…
$ climate.online2                            &lt;dbl&gt; 3, 5, 2, 5, 3, 5, 5, 5, 2, …
$ climate.online3                            &lt;dbl&gt; 2, 3, 5, 5, NA, NA, 5, 3, 3…
$ climate.onsite1                            &lt;dbl&gt; 1, 4, 5, 2, 4, 3, 1, 5, NA,…
$ climate.onsite2                            &lt;dbl&gt; 1, 2, 3, 4, 5, 3, 1, 5, 1, …
$ climate.onsite3                            &lt;dbl&gt; 1, 3, NA, 2, 4, 2, 1, 5, 1,…
$ `เพศผู้เรียน`                                 &lt;dbl&gt; 2, 1, 2, 1, 1, 2, 1, 1, 1, …
$ `ระดับชั้น`                                   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ `ภูมิลำเนา`                                  &lt;chr&gt; "กลาง", "กลาง", "กลาง", "กล…
$ `สไตล์การเรียนที่ชอบ`                          &lt;dbl&gt; 2, 2, 2, 1, 1, 2, 1, 1, 2, …
$ smartphone                                 &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ ipad                                       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, …
$ computer                                   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ `ความพร้อมของinternet`                      &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, …
$ `บรรยากาศที่พักอาศัย`                          &lt;dbl&gt; 1, 1, 1, 1, NA, 2, 1, 1, 1,…
$ `ความสามารถผู้เรียนในการใช้เทคโนโลยี`           &lt;dbl&gt; 1, 1, 2, 1, 2, 2, 1, 1, 2, …
$ `ความคิดเห็นต่อการเรียน`                       &lt;dbl&gt; 1, 2, 2, 3, 3, 3, 3, 2, 3, …
$ interaction.online1                        &lt;dbl&gt; 2, 3, 3, 2, 2, 3, 3, 4, NA,…
$ interaction.online2                        &lt;dbl&gt; NA, 3, 3, 2, 2, 2, 3, 3, 3,…
$ interaction.online3                        &lt;dbl&gt; 2, 3, 3, NA, 3, 3, 3, 3, 3,…
$ interaction.onsite1                        &lt;dbl&gt; 1, 2, 2, 2, 2, 3, 2, 2, 2, …
$ interaction.onsite2                        &lt;dbl&gt; 1, 2, 2, 2, 2, 1, 2, 2, 2, …
$ interaction.onsite3                        &lt;dbl&gt; 2, 2, 1, 2, 2, 2, 2, 2, 2, …
$ `ความเครียดขณะเรียนonline`                   &lt;dbl&gt; 5, 5, 1, 4, 5, 4, 2, 5, 5, …
$ `ความเครียดขณะเรียนonsite`                   &lt;dbl&gt; 1, 3, 3, 5, 1, NA, 5, 3, 4,…
$ outcome.online1                            &lt;dbl&gt; 2, 3, 2, 1, 2, 2, 1, 2, 2, …
$ outcome.online2                            &lt;dbl&gt; 2, 2, 2, 1, 2, 2, 1, 5, 2, …
$ outcome.online3                            &lt;dbl&gt; 1, 2, 3, 2, 1, 1, 2, 3, 1, …
$ outcome.online4                            &lt;dbl&gt; 39.75234, 46.50444, 40.6486…
$ outcome.onsite1                            &lt;dbl&gt; 1, 2, 1, 3, 1, 1, 2, 3, 3, …
$ outcome.onsite2                            &lt;dbl&gt; 1, 1, 1, 2, 2, 2, 1, 2, 2, …
$ outcome.onsite3                            &lt;dbl&gt; 1, 1, 1, 2, 1, 1, 1, 2, 1, …
$ outcome.onsite4                            &lt;dbl&gt; 41.34332, 22.67131, 43.0961…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a>large_data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="do">### ปรับชื่อตัวแปรใหม่</span></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">student_id =</span> X,</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">school_type =</span> <span class="dv">2</span>,</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">school_location =</span> <span class="dv">3</span>,</span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">num_subject =</span> <span class="dv">4</span>,</span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">num_online =</span> <span class="dv">5</span>,</span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">num_onsite =</span> <span class="dv">6</span>,</span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">school_readiness =</span> <span class="dv">7</span>,</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">avg_teacher_age =</span> <span class="dv">15</span>,</span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">avg_teacher_techcomp =</span> <span class="dv">16</span>,</span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_gender =</span> <span class="dv">23</span>,</span>
<span id="cb93-13"><a href="#cb93-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_level =</span> <span class="dv">24</span>,</span>
<span id="cb93-14"><a href="#cb93-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_location =</span> <span class="dv">25</span>,</span>
<span id="cb93-15"><a href="#cb93-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_learningstyle =</span> <span class="dv">26</span>,</span>
<span id="cb93-16"><a href="#cb93-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_internet_readiness =</span> <span class="dv">30</span>,</span>
<span id="cb93-17"><a href="#cb93-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_home_climate =</span> <span class="dv">31</span>,</span>
<span id="cb93-18"><a href="#cb93-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_techcomp =</span> <span class="dv">32</span>,</span>
<span id="cb93-19"><a href="#cb93-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_learning_attitude =</span> <span class="dv">33</span>,</span>
<span id="cb93-20"><a href="#cb93-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_stress_online =</span> <span class="dv">40</span>,</span>
<span id="cb93-21"><a href="#cb93-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_stress_onsite =</span> <span class="dv">41</span></span>
<span id="cb93-22"><a href="#cb93-22" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb93-23"><a href="#cb93-23" aria-hidden="true" tabindex="-1"></a><span class="do">### สร้างตัวแปรใหม่</span></span>
<span id="cb93-24"><a href="#cb93-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb93-25"><a href="#cb93-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb93-26"><a href="#cb93-26" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_climate_online =</span> <span class="fu">mean</span>(<span class="fu">c</span>(climate.online1, climate.online2, climate.online3)),</span>
<span id="cb93-27"><a href="#cb93-27" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_climate_onsite =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"climate.onsite"</span>))),</span>
<span id="cb93-28"><a href="#cb93-28" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_interaction_online =</span> <span class="fu">mean</span>(<span class="fu">c</span>(interaction.online1, interaction.online2, interaction.online3)),</span>
<span id="cb93-29"><a href="#cb93-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_interaction_onsite =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"interaction.onsite"</span>))),</span>
<span id="cb93-30"><a href="#cb93-30" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_outcome_online =</span> (outcome.online1<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.online2<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.online3<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span>outcome.online4)<span class="sc">/</span><span class="dv">4</span>,</span>
<span id="cb93-31"><a href="#cb93-31" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_outcome_onsite =</span> (outcome.onsite1<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.onsite2<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.onsite3<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span>outcome.onsite4)<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb93-32"><a href="#cb93-32" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb93-33"><a href="#cb93-33" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"interaction"</span>), <span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"outcome"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb93-34"><a href="#cb93-34" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"climate"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb93-35"><a href="#cb93-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">student_num_device =</span> <span class="fu">sum</span>(<span class="fu">c</span>(smartphone,ipad,computer),<span class="at">na.rm =</span> T))  <span class="sc">%&gt;%</span> </span>
<span id="cb93-36"><a href="#cb93-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,000 × 36
   student_id school_type     school_location num_subject num_online num_onsite
        &lt;dbl&gt; &lt;chr&gt;           &lt;chr&gt;                 &lt;dbl&gt;      &lt;dbl&gt;      &lt;dbl&gt;
 1          1 โรงเรียนมัธยมศึกษา กลาง                      8          4          4
 2          2 โรงเรียนมัธยมศึกษา กลาง                      8          8          0
 3          3 โรงเรียนมัธยมศึกษา กลาง                      8          8          0
 4          4 โรงเรียนมัธยมศึกษา กลาง                      7          7          0
 5          5 โรงเรียนมัธยมศึกษา กลาง                      7          7          0
 6          6 โรงเรียนมัธยมศึกษา กลาง                      7          7          0
 7          7 โรงเรียนมัธยมศึกษา กลาง                      8          3          5
 8          8 โรงเรียนมัธยมศึกษา กลาง                      7          7          0
 9          9 โรงเรียนมัธยมศึกษา กลาง                      8          1          7
10         10 โรงเรียนมัธยมศึกษา กลาง                      8          8          0
# ℹ 990 more rows
# ℹ 30 more variables: school_readiness &lt;dbl&gt;, videoConference &lt;dbl&gt;,
#   Live &lt;dbl&gt;, LMS &lt;dbl&gt;, groupChat &lt;dbl&gt;, email &lt;dbl&gt;, collapApps &lt;dbl&gt;,
#   clipVideo &lt;dbl&gt;, avg_teacher_age &lt;dbl&gt;, avg_teacher_techcomp &lt;dbl&gt;,
#   student_gender &lt;dbl&gt;, student_level &lt;dbl&gt;, student_location &lt;chr&gt;,
#   student_learningstyle &lt;dbl&gt;, smartphone &lt;dbl&gt;, ipad &lt;dbl&gt;, computer &lt;dbl&gt;,
#   student_internet_readiness &lt;dbl&gt;, student_home_climate &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>ผลการวิเคราะห์ที่ได้มีข้อสังเกตอะไรบ้าง</p>
</section>
<section id="filter-methods" class="level3">
<h3 class="anchored" data-anchor-id="filter-methods">Filter Methods</h3>
<p>Filter Methods เป็นหนึ่งในเทคนิคการคัดเลือกตัวแปร (Feature Selection) ที่ใช้ คุณสมบัติทางสถิติของตัวแปร ในการคัดกรองตัวแปรที่มีความสำคัญต่อการสร้างโมเดล โดยกระบวนการนี้จะไม่พึ่งพาโมเดลใด ๆ ในการประเมิน แต่จะใช้สถิติพื้นฐาน เช่น ความสัมพันธ์ (correlation) ระหว่างตัวแปรอิสระกับตัวแปรตาม และค่าสถิติอื่น ๆ เช่น Chi-square, ANOVA, Mutual Information เพื่อกรองตัวแปรที่มีความสำคัญสูงไว้</p>
<ul>
<li><p>filter zero or near-zero variance</p></li>
<li><p>correlation-based filtering</p></li>
</ul>
<p>จุดเด่นของวิธีการนี้คือทำได้อย่างรวดเร็ว แต่เป็นการวิเคราะห์ที่อาจจะละเลยความสัมพันธ์ที่ซับซ้อนระหว่างตัวแปรอิสระกับตัวแปรตาม นอกจากนี้ผลลัพธ์ที่ได้อาจจะไม่ได้เป็นผลลัพธ์ที่ดีที่สุดที่เป็นไปได้</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="do">### create predictor matrix</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>use_data <span class="ot">&lt;-</span> large_data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a><span class="do">### ปรับชื่อตัวแปรใหม่</span></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">student_id =</span> X,</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">school_type =</span> <span class="dv">2</span>,</span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">school_location =</span> <span class="dv">3</span>,</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">num_subject =</span> <span class="dv">4</span>,</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">num_online =</span> <span class="dv">5</span>,</span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">num_onsite =</span> <span class="dv">6</span>,</span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">school_readiness =</span> <span class="dv">7</span>,</span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">avg_teacher_age =</span> <span class="dv">15</span>,</span>
<span id="cb95-12"><a href="#cb95-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">avg_teacher_techcomp =</span> <span class="dv">16</span>,</span>
<span id="cb95-13"><a href="#cb95-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_gender =</span> <span class="dv">23</span>,</span>
<span id="cb95-14"><a href="#cb95-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_level =</span> <span class="dv">24</span>,</span>
<span id="cb95-15"><a href="#cb95-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_location =</span> <span class="dv">25</span>,</span>
<span id="cb95-16"><a href="#cb95-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_learningstyle =</span> <span class="dv">26</span>,</span>
<span id="cb95-17"><a href="#cb95-17" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_internet_readiness =</span> <span class="dv">30</span>,</span>
<span id="cb95-18"><a href="#cb95-18" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_home_climate =</span> <span class="dv">31</span>,</span>
<span id="cb95-19"><a href="#cb95-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_techcomp =</span> <span class="dv">32</span>,</span>
<span id="cb95-20"><a href="#cb95-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_learning_attitude =</span> <span class="dv">33</span>,</span>
<span id="cb95-21"><a href="#cb95-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_stress_online =</span> <span class="dv">40</span>,</span>
<span id="cb95-22"><a href="#cb95-22" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_stress_onsite =</span> <span class="dv">41</span></span>
<span id="cb95-23"><a href="#cb95-23" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span> </span>
<span id="cb95-24"><a href="#cb95-24" aria-hidden="true" tabindex="-1"></a><span class="do">### สร้างตัวแปรใหม่</span></span>
<span id="cb95-25"><a href="#cb95-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb95-26"><a href="#cb95-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb95-27"><a href="#cb95-27" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_climate_online =</span> <span class="fu">mean</span>(<span class="fu">c</span>(climate.online1, climate.online2, climate.online3)),</span>
<span id="cb95-28"><a href="#cb95-28" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_climate_onsite =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"climate.onsite"</span>))),</span>
<span id="cb95-29"><a href="#cb95-29" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_interaction_online =</span> <span class="fu">mean</span>(<span class="fu">c</span>(interaction.online1, interaction.online2, interaction.online3)),</span>
<span id="cb95-30"><a href="#cb95-30" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_interaction_onsite =</span> <span class="fu">rowMeans</span>(<span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">"interaction.onsite"</span>))),</span>
<span id="cb95-31"><a href="#cb95-31" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_outcome_online =</span> (outcome.online1<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.online2<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.online3<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span>outcome.online4)<span class="sc">/</span><span class="dv">4</span>,</span>
<span id="cb95-32"><a href="#cb95-32" aria-hidden="true" tabindex="-1"></a>         <span class="at">student_outcome_onsite =</span> (outcome.onsite1<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.onsite2<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span> outcome.onsite3<span class="sc">*</span><span class="dv">20</span> <span class="sc">+</span>outcome.onsite4)<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb95-33"><a href="#cb95-33" aria-hidden="true" tabindex="-1"></a>         ) <span class="sc">%&gt;%</span></span>
<span id="cb95-34"><a href="#cb95-34" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"interaction"</span>), <span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"outcome"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb95-35"><a href="#cb95-35" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">starts_with</span>(<span class="st">"climate"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb95-36"><a href="#cb95-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">student_num_device =</span> <span class="fu">sum</span>(<span class="fu">c</span>(smartphone,ipad,computer),<span class="at">na.rm =</span> T))  <span class="sc">%&gt;%</span> </span>
<span id="cb95-37"><a href="#cb95-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>แบ่งชุดข้อมูล online learning</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a>online_data <span class="ot">&lt;-</span> use_data <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="fu">contains</span>(<span class="st">"onsite"</span>))</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(online_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 1,000
Columns: 31
$ student_id                 &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, …
$ school_type                &lt;chr&gt; "โรงเรียนมัธยมศึกษา", "โรงเรียนมัธยมศึกษา", "โรงเ…
$ school_location            &lt;chr&gt; "กลาง", "กลาง", "กลาง", "กลาง", "กลาง", "กล…
$ num_subject                &lt;dbl&gt; 8, 8, 8, 7, 7, 7, 8, 7, 8, 8, 8, 9, 8, 9, 8…
$ num_online                 &lt;dbl&gt; 4, 8, 8, 7, 7, 7, 3, 7, 1, 8, 0, 9, 1, 8, 5…
$ school_readiness           &lt;dbl&gt; 1, 3, 2, 3, 2, 2, 3, 3, 3, 3, 1, 3, 1, 3, 2…
$ videoConference            &lt;dbl&gt; 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1…
$ Live                       &lt;dbl&gt; 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1…
$ LMS                        &lt;dbl&gt; 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0…
$ groupChat                  &lt;dbl&gt; 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1…
$ email                      &lt;dbl&gt; 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0…
$ collapApps                 &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1…
$ clipVideo                  &lt;dbl&gt; 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0…
$ avg_teacher_age            &lt;dbl&gt; 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ avg_teacher_techcomp       &lt;dbl&gt; 2, 2, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3…
$ student_gender             &lt;dbl&gt; 2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2…
$ student_level              &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ student_location           &lt;chr&gt; "กลาง", "กลาง", "กลาง", "กลาง", "กลาง", "กล…
$ student_learningstyle      &lt;dbl&gt; 2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2…
$ smartphone                 &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1…
$ ipad                       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0…
$ computer                   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1…
$ student_internet_readiness &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…
$ student_home_climate       &lt;dbl&gt; 1, 1, 1, 1, NA, 2, 1, 1, 1, 1, 1, 1, 2, 1, …
$ student_techcomp           &lt;dbl&gt; 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 3, 2…
$ student_learning_attitude  &lt;dbl&gt; 1, 2, 2, 3, 3, 3, 3, 2, 3, 1, 3, 2, 1, 2, 3…
$ student_stress_online      &lt;dbl&gt; 5, 5, 1, 4, 5, 4, 2, 5, 5, 5, 1, 1, 3, 2, 2…
$ student_climate_online     &lt;dbl&gt; 2.666667, 4.333333, 3.333333, 5.000000, NA,…
$ student_interaction_online &lt;dbl&gt; NA, 3.000000, 3.000000, NA, 2.333333, 2.666…
$ student_outcome_online     &lt;dbl&gt; 34.93808, 46.62611, 45.16217, 28.26696, 34.…
$ student_num_device         &lt;dbl&gt; 2, 2, 2, 2, 2, 2, 2, 3, 2, 0, 2, 2, 2, 3, 2…</code></pre>
</div>
</div>
<section id="near-zero-variance" class="level4">
<h4 class="anchored" data-anchor-id="near-zero-variance">Near-Zero Variance</h4>
<p>สร้างชุดข้อมูล predictor matrix ของ online learning</p>
<ul>
<li><p><code>freqCut</code> เปรียบเทียบความถี่ของค่าที่พบมากที่สุดกับค่าที่พบมากที่สุดเป็นอันดับสอง เพื่อดูว่าคอลัมน์นั้นมีการกระจายตัวของค่ามากน้อยเพียงใด</p></li>
<li><p><code>uniqueCut</code> เปรียบเทียบจำนวนค่าที่ไม่ซ้ำกันกับจำนวนตัวอย่างทั้งหมดในคอลัมน์</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a>predictor_online <span class="ot">&lt;-</span> online_data <span class="sc">%&gt;%</span> dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>student_outcome_online)</span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="do">## install.packages("caret")</span></span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nearZeroVar</span>(predictor_online, <span class="at">freqCut =</span> <span class="dv">95</span><span class="sc">/</span><span class="dv">5</span>, <span class="at">uniqueCut =</span> <span class="dv">10</span>, <span class="at">saveMetrics =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                           freqRatio percentUnique zeroVar   nzv
student_id                  1.000000         100.0   FALSE FALSE
school_type                 1.277904           0.2   FALSE FALSE
school_location             1.400000           0.4   FALSE FALSE
num_subject                 1.242424           0.8   FALSE FALSE
num_online                  1.282895           1.1   FALSE FALSE
school_readiness            1.142384           0.5   FALSE FALSE
videoConference             1.873563           0.2   FALSE FALSE
Live                        1.500000           0.2   FALSE FALSE
LMS                         1.237136           0.2   FALSE FALSE
groupChat                   3.081633           0.2   FALSE FALSE
email                       1.070393           0.2   FALSE FALSE
collapApps                  1.840909           0.2   FALSE FALSE
clipVideo                   1.118644           0.2   FALSE FALSE
avg_teacher_age             1.061162           0.3   FALSE FALSE
avg_teacher_techcomp        1.000000           0.3   FALSE FALSE
student_gender              1.188184           0.2   FALSE FALSE
student_level               2.660606           0.5   FALSE FALSE
student_location            1.697161           0.4   FALSE FALSE
student_learningstyle       1.041475           0.3   FALSE FALSE
smartphone                  9.326316           0.2   FALSE FALSE
ipad                        3.139241           0.2   FALSE FALSE
computer                   18.816327           0.2   FALSE FALSE
student_internet_readiness  3.358407           0.2   FALSE FALSE
student_home_climate        2.127796           0.2   FALSE FALSE
student_techcomp            1.333333           0.3   FALSE FALSE
student_learning_attitude   1.702422           0.3   FALSE FALSE
student_stress_online       1.080508           0.5   FALSE FALSE
student_climate_online      1.054054           1.3   FALSE FALSE
student_interaction_online  1.028986           1.3   FALSE FALSE
student_num_device          3.463918           0.4   FALSE FALSE</code></pre>
</div>
</div>
</section>
<section id="correlation-based-method" class="level4">
<h4 class="anchored" data-anchor-id="correlation-based-method">Correlation-based method</h4>
</section>
</section>
<section id="wrapper-methods" class="level3">
<h3 class="anchored" data-anchor-id="wrapper-methods">Wrapper Methods</h3>
<ul>
<li><p>สร้างโมเดลทำนายหลายชุด: ทดลองชุดของตัวแปรหลายชุด โดยเลือกเพิ่มหรือลบตัวแปรทีละตัว</p></li>
<li><p>ใช้เกณฑ์การประเมินโมเดลเช่น AIC, BIC, AUC, F1-score, RMSE, MAE, หรือค่าสถิติอื่น ๆ ในการประเมินความสามารถของโมเดล</p></li>
<li><p>เลือกชุดตัวแปรที่ดีที่สุด: ชุดตัวแปรที่ให้ประสิทธิภาพดีที่สุดจะถูกเลือกเพื่อใช้ในการสร้างโมเดลสุดท้าย</p></li>
</ul>
<section id="best-subset-regression" class="level4">
<h4 class="anchored" data-anchor-id="best-subset-regression">Best Subset Regression</h4>
<ul>
<li><p>วิธีการหนึ่งที่ใช้ค้นหาโมเดลที่ดีที่สุดคือ best subset regression ซึ่งจะทำการสร้างโมเดลทุกโมเดลที่เป็นไปได้จากตัวแปรอิสระที่มี จากนั้นเปรียบเทียบ empirical fit ระหว่างโมเดลดังกล่าว</p></li>
<li><p>อย่างไรก็ตามวิธีการดังกล่าวจะใช้ทรัพยากรค่อนข้างเยอะ เพราะจะต้องสร้างโมเดลจากทุกความเป็นไปได้ ยกตัวอย่างเช่น หากมีตัวแปรอิสระทั้งหมด p ตัว โมเดลที่มีเฉพาะ main effect ที่เป็นไปได้จะมีทั้งหมด 2^p โมเดล เทคนิคนี้จึงเหมาะสำหรับสถานการณ์ที่มีข้อมูลที่ขนาดไม่ใหญ่มากเกินไป</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("leaps")</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a>reg_model <span class="ot">&lt;-</span> <span class="fu">regsubsets</span>(student_outcome_online <span class="sc">~</span> . <span class="sc">-</span>student_id, <span class="at">data=</span>online_data , <span class="at">nbest =</span><span class="dv">1</span>, <span class="at">nvmax =</span> <span class="dv">10</span>,</span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">method =</span> <span class="st">"exhaustive"</span>)</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a>sum <span class="ot">&lt;-</span> <span class="fu">summary</span>(reg_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>ข้อมูลตัวอย่างสำหรับหัวข้อนี้คือ TeacherSalaryData.csv</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"TeacherSalaryData.csv"</span>)</span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 397
Columns: 7
$ ...1          &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1…
$ rank          &lt;chr&gt; "Prof", "Prof", "AsstProf", "Prof", "Prof", "AssocProf",…
$ discipline    &lt;chr&gt; "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "B", "…
$ yrs.since.phd &lt;dbl&gt; 19, 20, 4, 45, 40, 6, 30, 45, 21, 18, 12, 7, 1, 2, 20, 1…
$ yrs.service   &lt;dbl&gt; 18, 16, 3, 39, 41, 6, 23, 45, 20, 18, 8, 2, 1, 0, 18, 3,…
$ sex           &lt;chr&gt; "Male", "Male", "Male", "Male", "Male", "Male", "Male", …
$ salary        &lt;dbl&gt; 139750, 173200, 79750, 115000, 141500, 97000, 175000, 14…</code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="do">### visualize numeric variables</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>p1<span class="ot">&lt;-</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.numeric) <span class="sc">%&gt;%</span></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span><span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(value))<span class="sc">+</span></span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>)<span class="sc">+</span></span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb103-9"><a href="#cb103-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span>
<span id="cb103-10"><a href="#cb103-10" aria-hidden="true" tabindex="-1"></a><span class="do">### visualize categorical variables</span></span>
<span id="cb103-11"><a href="#cb103-11" aria-hidden="true" tabindex="-1"></a>p2<span class="ot">&lt;-</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb103-12"><a href="#cb103-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select_if</span>(is.character) <span class="sc">%&gt;%</span></span>
<span id="cb103-13"><a href="#cb103-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="fu">everything</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb103-14"><a href="#cb103-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> value))<span class="sc">+</span></span>
<span id="cb103-15"><a href="#cb103-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>)<span class="sc">+</span></span>
<span id="cb103-16"><a href="#cb103-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>name, <span class="at">scales =</span> <span class="st">"free"</span>)<span class="sc">+</span></span>
<span id="cb103-17"><a href="#cb103-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span>
<span id="cb103-18"><a href="#cb103-18" aria-hidden="true" tabindex="-1"></a>p1<span class="sc">/</span>p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="regression_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>