project:
  type: book

book:
  title: "R for Data Analysis in Education"
  author: "สิวะโชติ ศรีสุทธิยากร"
  date: "10/7/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    classoption: [12pt, b5paper]
    pdf-engine: xelatex
    include-in-header: "thai-preamble.tex"


editor: visual

