project:
  type: website

website:
  title: "DataKruRoo-Blog"
  favicon: datakruroo.png
  navbar:
    logo: datakruroo.png
    right:
      - icon: bi bi-house-door-fill  # https://icons.getbootstrap.com/
        href: index.html
      - icon: bi bi-file-person-fill
        href: about.qmd
      - icon: facebook
        href: https://www.facebook.com/Siwachoat
      - icon: github
        href: xxx
  description: "Educational Datascience Blog"
format:
  html:
    theme: night
    hightlight: textmate
    css: styles.css
    body-footer: footer.html

editor: visual

