---
title: "Untitled"
format: html
editor: visual
---

## Objective

- กิจกรรมทบทวน effective data visualization

  - ออกแบบ visualization (Mark + Attributes)
  
  - ปรับแต่ง plot (color or other attributes, legend, ticks, grid-lines, labels, axes, etc.)
  
  - ปรับแต่ง theme (font, background, etc.)

- Multiple Geometries

- Multiple Panels and customizing facets

- Exporting plots


## กิจกรรม: Effective Data Visualization (30 mins)

ในฐานะนักวิเคราะห์ข้อมูลที่ทำงานให้กับหน่วยงานรัฐบาลที่มุ่งเน้นการพัฒนาการศึกษา นิสิตได้รับมอบหมายให้สร้างภาพข้อมูลเพื่อระบุจังหวัดที่มีความเสี่ยงต่อปัญหาทางการศึกษา ซึ่งสัมพันธ์กับสภาพภูมิอากาศที่ผิดปกติ นิสิตได้รับข้อมูลชุดหนึ่งที่ประกอบด้วยตัวชี้วัดสองประเภทหลัก ได้แก่ ดัชนีความเสี่ยงทางการศึกษา CMER และ สัดส่วนโรงเรียนที่มีความเสี่ยงสูง พร้อมข้อมูลสถิติพื้นฐานที่เกี่ยวข้อง

ข้อมูลที่นิสิตได้รับมีรายละเอียดดังนี้:

1.	สถิติพื้นฐานของ cmer_risk: ซึ่งประกอบด้วยค่าเฉลี่ย (mean), ค่ามัธยฐาน (median), ค่าเบี่ยงเบนมาตรฐาน (sd), และช่วงเปอร์เซ็นไทล์ (Q25, Q75 เป็นต้น) ของดัชนี CMER ในแต่ละจังหวัด ข้อมูลเหล่านี้สามารถใช้ในการประเมินภาพรวมของความเสี่ยงทางการศึกษา หากค่าเฉลี่ยหรือค่ามัธยฐานของ cmer_risk สูง แสดงถึงความเสี่ยงที่สูงขึ้นในจังหวัดนั้น ซึ่งอาจสะท้อนถึงผลกระทบของสภาพภูมิอากาศที่ผิดปกติต่อระบบการศึกษา
	
2.	สัดส่วนของโรงเรียนที่มีความเสี่ยงสูง (high_risk_school_mean): ตัวชี้วัดนี้คือค่าเฉลี่ยของสัดส่วนโรงเรียนที่ถูกจัดให้เป็นโรงเรียนที่มีความเสี่ยงสูงในแต่ละจังหวัด พร้อมกับข้อมูลสถิติพื้นฐานอื่น ๆ เช่น ค่าเบี่ยงเบนมาตรฐาน (sd) 
	

**เป้าหมายหลักของนิสิตคือการสร้างภาพข้อมูลที่สามารถนำเสนอทั้งสองมุมมองนี้ได้อย่างชัดเจน เพื่อให้ผู้กำหนดนโยบายและผู้มีส่วนได้ส่วนเสียเข้าใจและสามารถระบุจังหวัดที่มีแนวโน้มจะมีความเสี่ยงทางการศึกษาสูง และสามารถเปรียบเทียบความเสี่ยงระหว่างจังหวัดได้**

วัตถุประสงค์ของการนำเสนอข้อมูลคือ:

- เปรียบเทียบความเสี่ยงทางการศึกษาในแต่ละจังหวัด

- ระบุจังหวัดที่มีสัดส่วนของโรงเรียนที่มีความเสี่ยงสูง (high_risk_school_mean) มากที่สุด เพื่อการวางแผนจัดลำดับความสำคัญในการให้ความช่วยเหลือ


## Multiple Geometries



คือการรวมรูปแบบการแสดงข้อมูล (geometries) หลายแบบในภาพเดียวหรือชุดของภาพที่เกี่ยวข้องกัน เพื่อเพิ่มมิติและความเข้าใจในข้อมูล

- Comparing Data

- Show Multiple Levels of Detail

- Enhance Perspective and Context

	
	
